### ISSUE TITLE
white-list: what's the value of this variable

### ISSUE THREAD

**Issue by MudNernst** [sandboxie-plus/Sandboxie#1029]
I want to add a item "$D:\Software\" in ClosedFilePaths to implement white-list, but i don't know the value of this variable (`patsrc = Pattern_Source(pat);`). Could you enlighten me?  And is my way right modifying this file `process_util.c` and this part `_FX const WCHAR *Process_MatchPath(`。

```
if (closed_list) {

        // 对于使用“$”前缀的列表项，放开限制
        BOOLEAN is_allowed = FALSE;
        pat = List_Head(closed_list);
        while (pat) {
            patsrc = Pattern_Source(pat);
            // TEST
            // Log_Msg(MSG_1203, patsrc, NULL);
            if (wcslen(patsrc) > 0 && patsrc[0] == L'$') {
                ULONG temp_patsrc_len = (wcslen(patsrc) - 1);
                WCHAR *temp_patsrc = Mem_Alloc(pool, temp_patsrc_len);
                if (! temp_patsrc) {
                    return NULL;
                }
                wmemcpy(temp_patsrc, (patsrc + 1), temp_patsrc_len);
                PATTERN *temp_pat = Pattern_Create(pool, temp_patsrc, TRUE);
                if (Pattern_Match(temp_pat, path_lwr, path_len)) {
                    is_allowed = TRUE;
                    Mem_Free(temp_patsrc, temp_patsrc_len);
                    Pattern_Free(temp_pat);
                    break;
                }
                if (path_lwr[path_len - 1] != L'\\') {
                    path_lwr[path_len] = L'\\';
                    if (Pattern_Match(temp_pat, path_lwr, path_len + 1)) {
                        path_lwr[path_len] = L'\0';
                        is_allowed = TRUE;
                        Mem_Free(temp_patsrc, temp_patsrc_len);
                        Pattern_Free(temp_pat);
                        break;
                    }
                    path_lwr[path_len] = L'\0';
                }
                Mem_Free(temp_patsrc, temp_patsrc_len);
                Pattern_Free(temp_pat);
            }
            pat = List_Next(pat);
        }
        if (is_allowed) {
            *is_closed = FALSE;
        } else {
            pat = List_Head(closed_list);
            while (pat) {

                if (Pattern_Match(pat, path_lwr, path_len)) {

                    *is_closed = TRUE;
                    patsrc = Pattern_Source(pat);
                    break;
                }

                if (path_lwr[path_len - 1] != L'\\') {
                    path_lwr[path_len] = L'\\';
                    if (Pattern_Match(pat, path_lwr, path_len + 1)) {

                        path_lwr[path_len] = L'\0';
                        *is_closed = TRUE;
                        patsrc = Pattern_Source(pat);
                        break;
                    }
                    path_lwr[path_len] = L'\0';
                }

                pat = List_Next(pat);
            }
        }

    }
```

**Comment by DavidXanatos** [comment]
So to clarify what you want to do:
You want add
ClosedFilePath=$D:\MyPath
to the closed files list in order to give them the meaning that its an exception from an otherwise closed file path.

First of all you should not create a pattern for each match operation that will be very CPU intensive, you should have them cached, like sandboxie does.

Second, changing this in the driver will not be enough you need to change it also in the SbieDll

last but not least you need to keep in mind that directory listings will omit the excempt folder in many scenatios, like
ClosedFilePath=D:\MyPath
ClosedFilePath=$D:\MyPath\foo\bar
listing of D:\MyPath will fail, listing of D:\MyPath\foo will fail to

you should look into the WriteFilePath option as well this at least allows the listing if you have a boxed copy of the paths.
So if you add an exception like the above when using WriteFilePath, and create C:\Sandbox\DefaultBox\drives\D\MyPath\foo\bar
possibly listing of D:\MyPath\foo\bar will work I'm not sure though.

you may consider waiting until I finish https://github.com/sandboxie-plus/Sandboxie/issues/890 which will allow many new scenarios probably also including yours.

**Comment by MudNernst** [comment]
> So to clarify what you want to do:
> You want add
> ClosedFilePath=$D:\MyPath
> to the closed files list in order to give them the meaning that its an exception from an otherwise closed file path.
> 
> First of all you should not create a pattern for each match operation that will be very CPU intensive, you should have them cached, like sandboxie does.
> 
> Second, changing this in the driver will not be enough you need to change it also in the SbieDll
> 
> last but not least you need to keep in mind that directory listings will omit the excempt folder in many scenatios, like
> ClosedFilePath=D:\MyPath
> ClosedFilePath=$D:\MyPath\foo\bar
> listing of D:\MyPath will fail, listing of D:\MyPath\foo will fail to
> 
> you should look into the WriteFilePath option as well this at least allows the listing if you have a boxed copy of the paths.
> So if you add an exception like the above when using WriteFilePath, and create C:\Sandbox\DefaultBox\drives\D\MyPath\foo\bar
> possibly listing of D:\MyPath\foo\bar will work I'm not sure though.
> 
> you may consider waiting until I finish #890 which will allow many new scenarios probably also including yours.

Thanks @DavidXanatos very much.
