### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by NikitaB5** [sandboxie-plus/Sandboxie#1062]
Hey. I am trying to figure out why my game app isn't opening with sand boxie. 
Chrome and other normal apps are opening up after a little wait, but the Arc app isn't.
It shows that the app is running in the default section but then after a few seconds it automatically terminates. 
![Screenshot (163)](https://user-images.githubusercontent.com/81454446/127714417-95a0f626-e201-4994-a4fa-62db38ae6f41.png)

**Comment by isaak654** [comment]
1) Do you have a download link for this Arc App?

2) Since 0.5.1 it's changed everything, including a lot of compatibility settings.
I would suggest to backup your sandboxie.ini elsewhere, uninstall your Plus version and install the latest [0.8.9c](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.8.9c).

**Comment by DavidXanatos** [comment]
since we don't know where to get the failing game I'll close this
