### ISSUE TITLE
Noticed some zh-CN translations issue

### ISSUE THREAD

**Issue by BlakeNeko** [sandboxie-plus/Sandboxie#1064]
When I'm using Sandboxie-plus, I noticed some zh-CN translation is missing or can be improved.
I tried walk through the source code and found the translation files but don't know how to get start.
Since I don't have any experience how to add/modify translations while using github or other tools, it's Is there any methods I can help to fix them?
(Not a native English speaker, sorry if I made some grammar mistakes)

**Comment by isaak654** [comment]
You might be interested to read the following comments / threads: 
1) https://github.com/sandboxie-plus/Sandboxie/pull/905#issuecomment-882049888
2) https://github.com/sandboxie-plus/Sandboxie/issues/885#issuecomment-858502218
3) https://github.com/sandboxie-plus/Sandboxie/issues/593#issuecomment-880562063

I don't recommend to use the standalone version of Linguist (the translation tool), because you can't use it to run the first command line that I found useful to translate all missing strings at 100%.

[Here](https://github.com/sandboxie-plus/Sandboxie/blob/master/SandboxiePlus/SandMan/sandman_zh-CN.ts) you can find the location of your language in the repository
[Here](https://github.com/sandboxie-plus/Sandboxie/blob/master/Installer/Languages.iss) you can find the location of the Plus installer translation
[Here](https://github.com/sandboxie-plus/Sandboxie/blob/master/Sandboxie/msgs/Text-SimpChinese-2052.txt) you can find the location of the Sandboxie Classic translation

I would also recommend [GitHub desktop](https://desktop.github.com/) to create new commits, it helps to manage a lot of strings.
