### ISSUE TITLE
Please add support to Sandboxie Windows 10 Insider Preview Builds 2004 and later

### ISSUE THREAD

**Issue by Karmakstylez** [sandboxie-plus/Sandboxie#107]
Sandboxie is not working on Windows 10 Insider Preview Builds 2004 and later. 

Insider Preview: Build 2004 version 20175.1000 (Latest)

Installing does work, but when trying to run a program it does not open nor give any error.

Also found out:

- Office Compatibility does not work Office365 Insider Fast

**Comment by 0m3rta13** [comment]
when you say it does not give an error is that in regular sandboxie control? 
then if trying in sandman are you getting the 1067 error?

**Comment by Karmakstylez** [comment]
> when you say it does not give an error is that in regular sandboxie control?
Yes
> then if trying in sandman are you getting the 1067 error?
Yes, sandboxieplus gives the 1067 error. :)

~Leonardo

**Comment by 0m3rta13** [comment]
Ah. Damn. Having the same issue (#104)

Sanboxie has always had issues on the insider build. 
Guess we can only hope and wait to see if it can be fixed. Not sure how to go (rather what to lol for) about debugging it but am going to be having a crack at it again shortly

**Comment by Karmakstylez** [comment]
> Ah. Damn. Having the same issue (#104)
> 
> Sanboxie has always had issues on the insider build.
> Guess we can only hope and wait to see if it can be fixed. Not sure how to go (rather what to lol for) about debugging it but am going to be having a crack at it again shortly.

At the moment I use the Windows Sandbox build-in which is actually a virtual machine that eats a lot of memory in the meantime. So hopefully sandboxie can be supported by 2004 or later. I really want to perform dynamic analysis myself :)

Indeed. Does build 2004 normall

**Comment by DavidXanatos** [comment]
Given my limited time budget I think the most reasonable approach is to look into the issue only once a particular windows build will be finalized.
I mean with the level of quality MSFT shows a 20H2 once it will become public may still be rather buggy and not ready for use, so there will be plenty time to adapt Sbie to it.
One shouldn't install every build MS releases right away but only after a few months of observing others stumbling over the new bugs ;)

**Comment by 0m3rta13** [comment]
> Given my limited time budget I think the most reasonable approach is to look into the issue only once a particular windows build will be finalized.
> 
> I mean with the level of quality MSFT shows a 20H2 once it will become public may still be rather buggy and not ready for use, so there will be plenty time to adapt Sbie to it.
> 
> One shouldn't install every build MS releases right away but only after a few months of observing others stumbling over the new bugs ;)

Indeed. That is the same general advice I also give most people. 

My primary OS is Linux.
Im only part of the Fast ring for insider because of certain business/work/testing/dev aspects that require it.

I've been digging into Sbie's processes and system calls as I think that may be where the issue lies as there were a few changes in some of the primary system calls within windows I think about +-6 updates (weeks) ago. Can't say for sure though

In the mean time I'm currently using Shadow Defender, Shade and Windows sandbox. Shade sucks though. Haha. It's not always functional but it does the job sometimes. And Windows sandbox can't run most .Net apps as it doesn't load the frameworks.

Crazy how sandboxie basically replaces and is so much more convenient than all 3 of those.

Fully understand the time constraints you have though.
Thanks for your work and your time. Looking forward to a possible update/fix in the future. 

Cheers man!

**Comment by 0m3rta13** [comment]
Well. I just finished updating to the new insider release and as per usual the first thing I try is installing Sandboxie. 

I have no idea yet what's changed but it works!!! 

For anyone using insider the build I'm referring to is:

Insider Fast Ring
Version: 2004
OS Build: 20197.1000

Happy days!
