### ISSUE TITLE
Suggested language files available for separate download

### ISSUE THREAD

**Issue by StrollStars** [sandboxie-plus/Sandboxie#1105]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The language file always does not exactly match the software, so it is recommended to be able to update and download language files separately to match the new version of the software as soon as possible.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by bastik-1001** [comment]
Is this still desired, considering there is a new workflow?

From my point of view, the release rate of Sandboxie is high enough that more and more accurate translations are provided, but of course due to changes, they still may lag behind. Provided downloading independent translations are still desired, there would need to be a workflow for that. Also, users had to check, download and replaces the translations.

**Comment by DavidXanatos** [comment]
I think an online update is not a bad idea but I would not implement such a thing just for languages.

What I was thinking for a while now is; since new core features/changes are usually switchable with a setting and since a few builds we have a default [DefaultTemplates] section in the templates.ini which is always included and allows us to change default presets by providing a new templates.ini, for example #2025 could have been fixed this way. It would be a nice feature to have an online updater for the Templates.ini and sinse we are at it, we could use this mechanism also for language files.

**Comment by bastik-1001** [comment]
That sounds interesting and some template updates may not justify that a new sandboxie version is released.
