### ISSUE TITLE
In windows 11 sandboxie can't open explorer

### ISSUE THREAD

**Issue by sixiansheng** [sandboxie-plus/Sandboxie#1127]
![Quicker_20210820_203059](https://user-images.githubusercontent.com/35787924/130233638-1e0dd13f-a4a7-451f-8ada-510094311e83.png)
In windows 11 sandboxie can't open explorer、
sandboxie：0.9.3

**Comment by Dyras** [comment]
Windows 11 isn't supported yet. I don't think it would be wise to support a beta either.

**Comment by isaak654** [comment]
I think it's related to the following support request: https://forum.xanasoft.com/viewtopic.php?f=16&t=124

> Yes, I can reproduce this on my test VM as well,
but I'm not sure if i should try fixing it now.
you see... the new windows ui is somehow hacked in as a overlay, like they needed to make it public right now and did not have time to do it properly, so I actually expect MSFT to change everything before a final release.
On the other hand its scheduled for in a month or so, so I'm not sure, may be they will leave the crappy solution in place because well more CPU and GPU usage means more PC sales LOL...
>
>Anyhow I'll look into that issue once W11 is finally final and released to the public.

**Comment by Crwmy** [comment]
Win 11 build 22000.348 still has that issue with 0.9.8d.  

Hope the insider build fix will be released soon. The [Optional November Update](https://support.microsoft.com/en-us/topic/november-22-2021-kb5007262-os-build-22000-348-preview-7f3e18d7-4189-4882-b0e9-afc920253aee), that had some explorer.exe fixes seem to not contain that particular fix.   

(to be clear: I don't expect a fix from Sandboxie, just looked if the issue is known and wanted to update for others.)

**Comment by fusionneur** [comment]
I think this issue is duplicate with https://github.com/sandboxie-plus/Sandboxie/issues/69

The explorer and right click on a folder load after waiting a lot of time even if initially explorer looks white and unresponsive

**Comment by isaak654** [comment]
#1628 #1652

**Comment by isaak654** [comment]
> Update: also insider build 22483.1011 works fine. I think I will not look into this issue on the current RTM build of windows 11, as MSFT will resolve it with an update as it seams. So I rather spent my time on fixing things that wont fix themselves.

It's been over six months, I would suggest to publish a new update about the current state of things: https://github.com/sandboxie-plus/Sandboxie/issues/1729

**Comment by isaak654** [comment]
> Update: also insider build 22483.1011 works fine. I think I will not look into this issue on the current RTM build of windows 11, as MSFT will resolve it with an update as it seams. So I rather spent my time on fixing things that wont fix themselves.

It's been months, I would suggest to publish a new update about the current state of things: https://github.com/sandboxie-plus/Sandboxie/issues/1729

**Comment by Nammehub** [comment]
when i start sandboxed Explorer - it looks stuck, like in screenshots above. But it loading after ~40 seconds.. Maybe it's for my system? Win21H2 Sandboxie v1.0.22

**Comment by isaak654** [comment]
It was fixed only in more recent Windows 11 builds, as mentioned earlier.

**Comment by isaak654** [comment]
#2010

**Comment by isaak654** [comment]
Update: the last Win 11 build where Explorer started is 25131.1000, since 25136.1000 it hangs.

**Comment by yusi1** [comment]
Idk if this is helpful, but after the hanging has finished and it loads in, it loads the "old" Windows 10 file manager instead of the new one.

**Comment by isaak654** [comment]
This may be fixed with the next build v1.3.4 / 5.58.4: https://github.com/sandboxie-plus/Sandboxie/issues/2109#issuecomment-1250126148

**Comment by isaak654** [comment]
While this issue is fixed, there is a new one between the hardened sandboxes and Windows 11 22H2 RTM:  https://github.com/sandboxie-plus/Sandboxie/issues/2341
