### ISSUE TITLE
Uninstalling Sandboxie Plus Leaves "Run Sandboxed" Context Menu Entry if Enabled

### ISSUE THREAD

**Issue by DavidBerdik** [sandboxie-plus/Sandboxie#1159]
**Describe the bug**
If you enable the "Run Sandboxed" context menu entry in Sandboxie Plus and later decide to uninstall Sandboxie, the context menu entry is retained, but obviously, not functional.

**To Reproduce**
1. Enable the "Run Sandboxed" context menu entry in Sandboxie Plus.
2. Uninstall Sandboxie Plus
3. The context menu will still have a "Run Sandboxed" entry.
![Untitled](https://user-images.githubusercontent.com/7663225/131725340-549d66f3-499e-49db-9809-b636b023a9ab.png)

**Expected behavior**
The entry should be removed as part of the uninstall process.

**System details and installed software (please provide the following information):**
 - Windows 10 Pro for Workstations x64 21H1 (OS Build 19043.1165)
 - Sandboxie Plus v0.9.4
 - I am not sure what version of Sandboxie Plus introduced this bug. My guess is that it's been present since the first release to support it. I should also note that I have not tried this with Classic Sandboxie, so I am not sure if the bug is present there.
 - In addition to Windows Defender, I use Malwarebytes Premium 4.4.4.

**Comment by isaak654** [comment]
I think this could help: https://github.com/sandboxie-plus/Sandboxie/discussions/1147#discussioncomment-1259921

**Comment by mpheath** [comment]
There was an issue about the context menu [fixed](https://github.com/sandboxie-plus/Sandboxie/pull/1037/files) on 26 July. If you have not updated since then and just done the uninstall of an old version from that time period, then that may explain why the orphan registry enties still exist after an uninstall.

The history of v0.8.9 on 29 July does list:

>fixed Inno Setup script not being able to remove shell integration keys during Sandboxie Plus uninstall (by mpheath) [#1037]

An install and uninstall of a v0.9.x installer should remove the *sandbox* registry keys recursively.

If you want to manually cleanup the keys, then in a command prompt, type:

```bat
reg delete HKCU\software\classes\*\shell\sandbox /f
reg delete HKCU\software\classes\folder\shell\sandbox /f
```

The v0.9.5 installer is more stable and is recommended. Older versions may have bugs like the one you have reported.

If possible, suggest system reboot and install [v0.9.5](https://github.com/sandboxie-plus/Sandboxie/releases/tag/0.9.5) or later. The reboot is not expected to remove the registry entries. The reboot will refresh the environment so that the v0.9.5 installer will have better success.

**Comment by DavidBerdik** [comment]
@isaak654 I did try to reboot, but it was still there. I removed it manually as per @mpheath's instructions and tried to reproduce this again just now under the same conditions, but it seems to have not happened this time. Perhaps it was a once-off thing. Since I can't reproduce it now, I will close this.
