### ISSUE TITLE
File_Api_GetBlockedDll should not be removed.

### ISSUE THREAD

**Issue by zhangshuangjun** [sandboxie-plus/Sandboxie#1170]
Hi, File_Api_GetBlockedDll is a very important feature to make compatibility with other software(such as Mcafee DLP, some anti-virus softwares . the use kernel driver inject dll to other process).

File_Api_GetBlockedDll configed can make compatibility when process run sandboxed. please don't remove this feature , thanks.

**Comment by DavidXanatos** [comment]
Well this feature was not used by sandboxie since its open sourcing, the driver part only collects DLL paths to be loaded later, and these are to be retrieved with SbieApi_GetBlockedDll but this is not used any ware in the code.
So removing this entirely does not change anything compatibility wise. 

Or am i missing something?

**Comment by DavidXanatos** [comment]
Ah I see... in that case I'll leave it in

**Comment by DavidXanatos** [comment]
its back in: https://github.com/sandboxie-plus/Sandboxie/commit/fecac5b805489de260f6d13568adf2e98d591ec2
thanks for catching this
