### ISSUE TITLE
Chromium browsers in Sandboxie can not access microphone

### ISSUE THREAD

**Issue by bill6248** [sandboxie-plus/Sandboxie#1208]
**Describe the bug**
chrome、opera in Sandboxie can not access microphone. my hardware is OK, since chrome\opera outside the sandboxie can use microphone successfully and wechat in sandboxie can access microphone.

version
Sandboxie-Plus-x64-v0.9.5.exe
Sandboxie-Classic-x64-v5.51.5.exe

**System details and installed software (please provide the following information):**
 - win 10

**Comment by isaak654** [comment]
I have the same issue with Ms Edge and [this](https://www.onlinemictest.com) site that triggers the microphone permission popup. If you allow it outside of the sandbox, the mic test will be allowed correctly, but not inside a clean sandbox.

I've tried `OpenDevCMApi=y`, but it didn't work.

**Comment by bill6248** [comment]
> I have the same issue with Ms Edge and [this](https://www.onlinemictest.com) site that triggers the microphone permission popup. If you allow it outside of the sandbox, the mic test will be allowed correctly, but not inside a clean sandbox.
> 
> I've tried `OpenDevCMApi=y`, but it didn't work.

i agree with you. OpenDevCMApi did not work

**Comment by MancioDellaVega** [comment]
> **Describe the bug** chrome、opera in Sandboxie can not access microphone. my hardware is OK, since chrome\opera outside the sandboxie can use microphone successfully and wechat in sandboxie can access microphone.
> 
> version Sandboxie-Plus-x64-v0.9.5.exe Sandboxie-Classic-x64-v5.51.5.exe
> 
> **System details and installed software (please provide the following information):**
> 
> * win 10

I have the same issue, for resolve it i use this comman line to load the sandbox...
C:\Program Files\Sandboxie-Plus\Start.exe Chrome.exe --no-sandbox

i don't know if is safe to use it..but seems that works fine..

**Comment by SoraKagami** [comment]
**It seems to be possible to get microphone and webcam/camera access inside a sandbox for messaging applications like "Line", Skype (PC build version) etc. but not chrome/chromium.**

For some unusual reason Chrome/chromium appears to be doing something different that appears to be incompatible with sandboxie?

**Extra info:**
Chrome (101.0.4951.54) inside a sandbox can see windows' microphone devices and can switch between them. However when attempting to access a mic using say, the web version of Discord, it'll report "Microphone Access is Denied". Same issue as what **KindaNeatdoe** and everyone above reported.

Turning on "Allow sandboxed programs to manage Hardware/Devices" (sandboxie-plus) does not appear to fix this.
I wonder if Chrome may be attempting to access the microphone/webcam "Settings" using the UWP system?

**Another relevant Sandboxie-Plus test result:**
Turning on "Disable Security Isolation" and "Disable Security Filtering" and reducing most (not all) of the sandboxie related protections did not allow chrome to successfully access the microphone.

**Comment by SoraKagami** [comment]
**The need for chromium to be able to access the mic/cam (while sandboxie'd) will only grow and become increasingly relevant and of importance to sandboxie going forward.**

**Google meet** has become widely used by companies (staff-meetings / shareholder-meetings) and individuals, while more and more high profile applications become based on chromium, switches to chromium or embed chromium.

There is also the large number of web applications requiring mic/webcam access which cannot be run while a browser is sandboxie'd, _forcing users to disable sandboxie for compatibility while throwing security out the front door_.

Is there anything us users of sandboxie can do to help with addressing this issue?

**Comment by isaak654** [comment]
> Is there anything us users of sandboxie can do to help with addressing this issue?

<img width="75%" src="https://user-images.githubusercontent.com/12372772/161425270-3fdc8304-d053-4fdb-9476-20237311e0fa.png">

See also the [SandboxieTrace](https://sandboxie-plus.github.io/sandboxie-docs/Content/SandboxieTrace.html) documentation.

**Comment by isaak654** [comment]
### Part 1 / 2 
Thank you for your effort. If possible, I would suggest to keep your [log](https://www.dropbox.com/s/47o0pzvd3ihkze3/Chrome%20Google%20Meet%20Trace%2C%20new%20sandbox%2C%20chrome%20forced%20only.log?dl=1) available for a future comparison.

The thing that bothers me most about this issue is that I just realized that the microphone issue reproduced in [this post](https://github.com/sandboxie-plus/Sandboxie/issues/1208#issuecomment-922281797) is not present on a Windows 7 VM (the same one I previously sent to @DavidXanatos for a different issue) and I cannot understand why the mic authorization doesn't seem to work for MS Edge  on Windows 10 or later. 👇

**Comment by isaak654** [comment]
Thank you for your effort and discoveries. If possible, I would suggest to keep your log available for a future comparison.

The thing that bothers me most about this issue is that I just realized that the microphone issue reproduced in [this post](https://github.com/sandboxie-plus/Sandboxie/issues/1208#issuecomment-922281797) is not present on a Windows 7 VM (the same one I previously sent to @DavidXanatos for a different issue) and I cannot understand why the mic authorization doesn't seem to work for the sandboxed MS Edge on Windows 10 or later. 

Here are the logs & Sandboxie.ini related to the working sandboxed Microsoft Edge on a W7 x64 system:
https://gist.github.com/isaak654/9905060b0936e6b2e051c0c1c2e5e941

**Comment by SoraKagami** [comment]
@isaak654 Ok I will keep the log there unless someone finds something private inside that should be removed, or until it's no longer needed.

Windows 10: From my research for other software incompatibilities, the windows 10 creator's update made some major updates to the security side of things and broke compatibility for some software until patched (VMWare player for one). My own guess is that this may be related?

Does your mic work in a sandboxed Edge if you change the selection to something other than one marked with "Default" ?

**Other relevant info**
My current windows is version 21H1 (19043.1165) with the "Windows Feature Experience Pack 120.2212.3530.0".
21H2 onwards may break some of the software that I need so I didn't venture to update beyond 21H1.

The mic issue with chromium is really weird since it appears to work if we manually select the non-default options. Anything assigned as "default" tends to fail (except for the speaker!). Unfortunately this manual selection process can be a bit finicky as I've seen it revert to "default" after being set (sandbox set to not auto delete).

Webcam: For my setup OBS studio works if selected, but EpocCam and nVidia Broadcast won't work inside a sandbox.

**Comment by isaak654** [comment]
> I have the same issue with Ms Edge and [this](https://www.onlinemictest.com) site that triggers the microphone permission popup. If you allow it outside of the sandbox, the mic test will be allowed correctly, but not inside a clean sandbox.
> 
> I've tried `OpenDevCMApi=y`, but it didn't work.

Update: this has been fixed for me with [Plus v.1.5.3](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.5.3) (using a clean standard sandbox without `OpenDevCMApi=y`).
