### ISSUE TITLE
When I install Sandboxie-Plus after Sandboxie have been installed, Sandboxie language changed to english

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#1241]
**Describe the bug**
When I install Sandboxie-Plus after Sandboxie have been installed, Sandboxie language changed to english. 

**To Reproduce**
1. Install Sandboxie and language choose chinese
2. Install Sandboxie-Plus and language choose chinese
3. Start Sandboxie
3. Language of Sandboxie change to english

**Expected behavior**

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? 
 Windows 10 Enterprise LTSC 2019.
 - What is your current Sandboxie edition and version? 
 Sandboxie 5.52.1
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.
 - Please mention any security software running in the background, even if the real-time protection is disabled.

**Comment by mpheath** [comment]
The *UI Language* in the Sandman UI is by default set to *Auto Detection*. I expect this would set the Sandman UI language by the Operating System locale/region setting. The Sandboxie-Plus installer currently does not set the language of the Sandman UI.

Expected behavior is not mentioned. If the Operating System locale/region setting is *english*, then Sandman UI *Auto Detection* is working as I would expect.

The context menu is already set to the install language with the custom message *RunSandboxedMenu* so it may seem reasonable to set the Sandman UI Language. Also, the portable install can set the Sandman UI Language to make it ready for the user.

This feature can be expected soon in the Sandboxie-Plus Installer.

**Comment by mpheath** [comment]
I have merged the changes to [Sandboxie-Plus.iss](https://github.com/sandboxie-plus/Sandboxie/blob/master/Installer/Sandboxie-Plus.iss).
Reference: Write to the ini file with [line 65](https://github.com/sandboxie-plus/Sandboxie/blob/18ff94486854218bfcb0050398dc2bb075221656/Installer/Sandboxie-Plus.iss#L65), using the *SandmanLanguage()* function at [line 182](https://github.com/sandboxie-plus/Sandboxie/blob/18ff94486854218bfcb0050398dc2bb075221656/Installer/Sandboxie-Plus.iss#L182).
Expected for the Sandboxie-Plus v0.9.8 release.
