### ISSUE TITLE
[metabug] CPU usage of SandMan vs SbieCtrl

### ISSUE THREAD

**Issue by VitRom** [sandboxie-plus/Sandboxie#129]
For a several releases in a row I see a very confusing picture. Because SB+ is still a bit in a testing stage I use both UIs at the same time. And CPU usage still very different between them over all this time. Very different.
![github-sandboxie](https://user-images.githubusercontent.com/453142/92516162-776fa400-f21d-11ea-8cc0-08300f04b473.png)
1st of all I can't see a sane reason to use the cross-platform UI framework for the program that's intended for Windows only by design. Except of very good knowledge of this FW by dev. But it's still a FW with everything going on after this.
So, in 2nd, please backpropagate all your additions and changes into this "good old" SbieCtrl UI.

**Comment by DavidXanatos** [comment]
1st, the reason is that Qt is a very powerful framework i.e. you can do a lot with very little code meaning that you can get more work done in much less time.

2nd, its a spare time project and my spare time is very valuable, I choose to use some of it for the public good and I will do that in the way most effective and most pleasant to me.

If you want anything that's more than a 15 minute effort to be back ported to the very painful to work with MFC based SbieCtrl I guess you could pay for the work to be done, or try doing it yourself. 
I will not do something in my spare time for free that I'm not passionate about and that I don't perceive as fun or entertaining.
I hope you can understand this philosophy I think its fair enough.

One thing I could do may be (at some point in the future) is to look into a .NET version of the SandMan UI, the UI will not be as versatile as the Qt one but still be better that the old SbieCtrl and most important new features would be quick to add.
But than you will need to have a compatible .NET framework installed to use it, and in my experience it will not be any lighter on the CPU than the Qt UI.
So no easy any ware runnable portable version anymore.

**Comment by henrikx** [comment]
Just want to add that most Windows computers have .NET Framework installed. Mono might be an option too.
