### ISSUE TITLE
Biglybt, a P2P app when opened in a sandbox... Opens outside of sandboxie.

### ISSUE THREAD

**Issue by Matblanket** [sandboxie-plus/Sandboxie#1299]
When I tried to open Biglybt in sandboxie, the application instead opened outside of sandboxue

1. Install biglybt outside sandboxie
2. Try to launch it from a hardened sandbox
3. See error

**Expected behavior**
I expected it to open inside the sandbox like all other apps do.

**System details and installed software**
 -Windows 10 home 10.0.19043
 -windows defender (real time protection is enabled)

**Sandboxie configuration**
The sandbox was a default hardened sandbox.

**Comment by DavidXanatos** [comment]
I have tested it and as far as I can tell everything works fine.
The opening outside sandbox happens only when you already have a un-sandboxed instance open and this as it looks to me is caused by the program using a localhost network socket to find already runnign instances.
This can not be blocked as when the port is blocked the tool does nto start at all.
So i would recommend to kill the un-sandboxed instance, and set it to be forced to always run sandboxed
