### ISSUE TITLE
A space is missing in the German translation during installation

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#1333]
Hello! I'm not filling out this form because this is a 5 sec issue, if that's OK?

![grafik](https://user-images.githubusercontent.com/12563436/138673904-ebc02d57-d1bc-4383-a199-43d70aa1bc15.png)
"Starte automatischSandboxie-Plus" is what it says. However it should definitely say
"Starte automatisch Sandboxie-Plus"
(A space is missing)

**Comment by bastik-1001** [comment]
Of course it is wrong to have the name being written next to the string without there being a space.

I am not even sure that the fix is sorting it out from a grammatical point of view.

> Automatically start %1

turns to

> Starte automatisch %1

while it would be better if it would be

> Starte %1 automatisch

so that it reads Starte Sandboxie-Plus automatisch

Alternatively one could have

> %1 automatisch starten

to have it read Sandboxie Plus automatisch starten

or

> Automatisch starten:  %1

Those would allow users to be able to read it without there being a grammatical 'concern'.

**Comment by mpheath** [comment]
@bastik-1001 

> Alternatively one could have
> 
> > %1 automatisch starten

Same as [dutch], is that preferred grammer as the temporary fix in Languages.iss?

 [dutch]: https://github.com/jrsoftware/issrc/blob/15db6745cd5480d06710a287afbf0ba8d45f6034/Files/Languages/Dutch.isl#L358

These are AutoStartProgram translations:

Language|Custom Message
-|-
english|Automatically start %1
ChineseSimplified|自动启动 %1
ChineseTraditional|自動開啟 %1
dutch|%1 automatisch starten
french|Démarrer automatiquement %1
german|Starte automatisch%1
italian|Esegui automaticamente %1
polish|Automatycznie uruchamiaj aplikację %1
portuguese|Iniciar %1 automaticamente
russian|Автоматически запускать %1
spanish|Iniciar automáticamente %1

 * dutch and german are similar.
 * portuguese and spanish are similar.

What this shows is that the order of the words can vary.

**Comment by isaak654** [comment]
> It's an automated process which is commonly used in many repositories.

In fact, I have changed my mind since then.
