### ISSUE TITLE
SteamVR?

### ISSUE THREAD

**Issue by DocMAX** [sandboxie-plus/Sandboxie#1361]
Has anyone managed to get SteamVR to work?
What are the correct pipes?
I use these ones but no game "detects" SteamVR.
```
OpenIpcPath=*\BaseNamedObjects\vrdashboard.exe
OpenIpcPath=*\BaseNamedObjects\VR_*
OpenIpcPath=*\BaseNamedObjects\VRBootstrapper
OpenIpcPath=*\BaseNamedObjects\SteamVR_*
OpenPipePath=\Device\NamedPipe\SteamVR_Namespace
OpenPipePath=\Device\NamedPipe\VR_CompositorPipe_*
OpenPipePath=\Device\NamedPipe\VR_ServerPipe_*
```

**Comment by isaak654** [comment]
See the following reply, basically it's a current Sandboxie limitation: https://github.com/sandboxie-plus/Sandboxie/issues/1243#issuecomment-1047252992

Another workaround is running SteamVR in the "App Compartment" sandbox type introduced since Plus 1.0.0.

For further news, make sure to follow the issue #1243.
