### ISSUE TITLE
JS failed: %windir%\sysnative\cmd.exe

### ISSUE THREAD

**Issue by yvzpjrpj** [sandboxie-plus/Sandboxie#1403]
**Describe the bug**
Some software (e.g. [AliDrive](https://yunpan.aliyun.com/)) use JS command `%windir%\sysnative\cmd.exe /c %windir%\System32\REG QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid` to get MachineGuid. It does not work.

![image](https://user-images.githubusercontent.com/83130601/143403250-f954bb5f-7641-44c7-ada5-33524aa9ef5c.png)

**To Reproduce**
1.Just Start it 

**System details and installed software**
 - Windows 10 Pro 21H1 64-bit
 - Sandboxie Plus 0.9.8d

**Software Link**
 - (https://yunpan.aliyun.com/downloads/apps/desktop/aDrive.exe)

**Sandboxie configuration**
Installed inside the Sandboxie with default configuration.

**Comment by DevSplash** [comment]
> Error: The system could not find the specified registry key or value

It looks like the following command failed to execute:
`%windir%\sysnative\cmd.exe /c %windir%\System32\REG.exe QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid`(in 64-bit operating systems)
The value of `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\MachineGuid` cannot be read. It was incorrectly redirected to `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Cryptography\MachineGuid`, there is no such key here.
***
There seems to be another problem. 
In some cases nodejs in sandbox can't find `cmd.exe` when executing commands using child_process. 

> 'C:\Windows\sysnative\cmd.exe' is not recognized as an internal or external command, operable program or batch file.

The reason is that `%windir%\sysnative` is not recognized in this case. 

@DavidXanatos

**Comment by isaak654** [comment]
#1566

**Comment by isaak654** [comment]
#1578
