### ISSUE TITLE
Unexpected administrative permission prompt out and it breaks installation

### ISSUE THREAD

**Issue by TooYoungTooSimp** [sandboxie-plus/Sandboxie#147]
For example, when I want to use SpotifySetup.exe in sandboxie, It requires admin right but when it running it says it needs no admin right to install. Unless I patched the admin right detection, It failed to install or update in sandbox.
So I'm wondering why this program requires admin right in sandbox but not do so in real machine.

**Comment by ProjectBacker** [comment]
@TooYoungTooSimp Did you use 00 Shutup by any chance or something similar?

I had that problem on my PC it was because I had Disable UAC and well I had leftover files that we're not running in Admin mode.

Did you try making a new Sandbox and making sure Sandbxie was running in Administrator mode?

Could be a old registry key left that is preventing the installation. also check to see if the windows store didn't leave any traces you can search your full hdd for spotify

mine shows up like this
C:\Users\shawn\AppData\Local\Microsoft\WindowsApps\SpotifyAB.SpotifyMusic_zpdnekdrzrea0
C:\Users\shawn\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0
C:\Users\shawn\AppData\Local\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache\100\SpotifyAB_SpotifyMusic_zpdnekdrzrea0!Spotify

Anything related to the Windows Store is going to be a pita to attempt to run correctly in a sandbox.

**Comment by TooYoungTooSimp** [comment]
@ProjectBacker No I haven't used similar software and I always keeps my UAC enable. I tried make a new sandbox but no help. And I also never installed spotify from microsoft store.

**Comment by NewKidOnTheBlock** [comment]
Soo, I went to https://www.spotify.com/us/download/windows/
And successfully installed Spotify with Sandboxie:
![spotify](https://user-images.githubusercontent.com/12411527/106299980-2efd6500-6256-11eb-870f-e2f09ed324da.png)
-> I think this can be closed then.

**Comment by hg421** [comment]
> I think this can be closed then.

Agree, I haven't experienced this with newer version anymore as well (I did see it in earlier version and had to work around it by injecting the environment variable `__COMPAT_LAYER=RunAsInvoker`). I suspect it was due to the external manifest hack that it not active by default now.

**Comment by TooYoungTooSimp** [comment]
It's 4 months after I opened this issue. I've tested newest spotify and it does works. I don't know why but it must be some commit in this time solved this problem. Thanks for your work.
