### ISSUE TITLE
Many old games (~10 years old) don't start

### ISSUE THREAD

**Issue by kolomeets80** [sandboxie-plus/Sandboxie#1504]
**Describe the problem**

Many old games (~10 years old) don't start. Looks like they are hanging trying to enumerate audio devices. Allowing access to MMDeviceEnumerator with OpenClsid={BCDE0395-E52F-467C-8E3D-C4579291692E} allows them to start but no sound will be produced.

**To Reproduce**
1. For example, install https://www.gog.com/game/kings_bounty_crossworlds_goty in Sandbox (but pretty much any game released more than 10 years ago has this issue).
2. Try to launch the game. 
3. It will hang. 
4. Terminate its process, allow access to MMDeviceEnumerator with OpenClsid={BCDE0395-E52F-467C-8E3D-C4579291692E}. and launch the game again. Now it will start but not sound will be produced.

To double check run the game outside of the sandbox. It works properly.

**Screenshots**

**Expected behavior**
The game should start and be able to enumerate audio devices.

**System details and installed software**
 - What is your Windows edition and version? (e.g. Windows 10 Pro 20H2 64-bit)

Windows 11 21H2 64-bit
 - What is your current Sandboxie edition and version? (e.g. Sandboxie Plus 0.9.6 64-bit)

Sandboxie Plus 1.0.5 64-bit
 - What was your previous Sandboxie version before the update, if any?
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers.

It has always existed as I can recall.

 - Please mention any security software running in the background, even if the real-time protection is disabled.

**If you had a compatibility issue or a crash**
 - Please add a download link to the program not working properly in Sandboxie.
 - Please consider to take a log and make it available for analysis: https://git.io/Jwj2y
 - Please attach the actual memory dump and NOT the simple output, which often turns out to be insufficient for a proper analysis.

**Additional context**

**Sandboxie configuration**
If applicable, consider to attach your Sandboxie.ini configuration by copying the content on https://gist.github.com and sharing the resulting link. If you decide to paste the configuration here, make sure to use the backticks around strings, like in this working example:

<details>

<summary>My initial sandboxie.ini settings</summary>

```

[GlobalSettings]
FileRootPath=D:\Sandbox\%SANDBOX%
SeparateUserFolders=y
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
NetworkEnableWFP=n
EnableObjectFiltering=n
EnableWin32kHooks=y
EditAdminOnly=n
ForceDisableAdminOnly=n
ForgetPassword=n
Template=WindowsRasMan
Template=WindowsLive
Template=OfficeLicensing
Template=OfficeClickToRun

.....

[UserSettings_24D403B5]
SbieCtrl_AutoStartAgent=SandMan.exe
SbieCtrl_EnableAutoStart=y

.....

[DefaultBox]
Enabled=y
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
BoxNameTitle=n
CopyLimitKb=-1
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
OpenClsid={BCDE0395-E52F-467C-8E3D-C4579291692E}

```

</details>

**Comment by mysteriously** [comment]
May I ask anyone to elaborate what is the point to use virtualization software run games?

**Comment by kolomeets80** [comment]
@mysteriously. First, this is not virtualization software. It's merely a sandbox. Second, I run everything (not only games) in sandboxes to keep OS clean from application leftovers and random files. If you bought an old game from gog.com then you'll find that it managed to install a few ancient runtimes that you never want to have on your host OS.

@DavidXanatos

I did a few more experiments and found out that games DO start if I patiently wait for ~15 minutes. So it looks to me as a timeout somewhere.

I have a naive theory. Can be  it related to "#define RPC_C_BINDING_TIMEOUT   4" defined in Sandboxie/core/dll/rpcrt.c.

Is there any way to make this configurable? I wonder if it would work if it's set to 0.

There's an option to skip it altogether but then it defaults to "5" according to https://docs.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-rpcmgmtsetcomtimeout that is even bigger.

**Comment by DaneXtream** [comment]
I'm also use Sandboxie for running games in a dedicated sandbox. This way helps us to not lose the save game or configuration files if for example we would need at some point to reinstall completely Windows.

I'm eager to see a solution, please @DavidXanatos investigate this problem.

**Comment by typpos** [comment]
Same usage scenario here. Virtually [pun[ all apps in sandboxes to keep OS clean.

**Comment by DavidXanatos** [comment]
I can confirm that with
OpenClsid={BCDE0395-E52F-467C-8E3D-C4579291692E}
no sound is produced,
how ever on my system the game in question, when installed into the sandbox, starts just fine with sound and no delays, without that OpenClsid

Do other people have issues with this game?

Can anyone create a list of not working games, with info's if it does not work for anyone or just for some, what hardware those affected users have, what the issue is, and if there is any workaround. 
I feal like buying games randomly only to find out that they work on my system is not the best strategy to pinpoint the issues.

Curating a list of working and non working games together with workarounds if available would be highly appreciated and a great opportunity to earn a contributors' supporter certificate ;)

**Comment by Gravityzwell** [comment]
Adding to the others, all my games are sandboxed with Sandboxie, and I have a lot.
I don't like game installers running on my main system and adding their clutter to the installed programs list, adding redists (unnecessarily) and other cruft.

Also a huge part is that Sandboxie runs games (in my tests) at the same speed as the host system.

**Comment by Gravityzwell** [comment]
Regarding the actual issue, I've run a lot of old games in Sandboxie (not plus) without issue. Doom3, Half-Life, Half-Life2, and their variants and mods. More than I care to list. I'm still using 5.53.3 if that matters.

**Comment by kolomeets80** [comment]
I reinstalled Windows from scratch. Now using Windows 10 21H2. Looks like the issue has gone. I'll slowly install drivers/system tools and check how Sandboxie works after every installation.

**Comment by Rngexile** [comment]
> Same usage scenario here. Virtually [pun] all apps in sandboxes to keep OS clean.

Same here since 15years, on Win XP (good old times playing with HIPS), Win 7, Win 10, always with Sandboxie then Sandboxie-Plus up to date. Sandboxie-Plus rocks !

Not a proper list of working/not working games but few things that helped me over the years :
- Avoiding games with anti-cheat systems and other spying bloatwares helps to avoid (most) problems
- Trying game with its made-for OSes (and not an newer one), or try to run it with an OS compatibility mod (to apply on the .exe), check for OS's update or specific problems (as usual, drivers, vc++)
- Run the installer/game.exe without network block blocknetdevices (network shares blocked, no problem) in sandboxie. Block fully or not (loopback, dns, ...) with a dedicated (or win's fw, or sandboxie-plus's fw) firewall if wanted. 
- game fully installed in a sandbox, try to run the game with a dedicated shortcut (manualy created or by sandboxie) : if it does not work, then try to run the game by explorer.exe sandboxed
- game fully installed in a sandbox, put the game's directory in a "real" directory, outside fileroothpath. Then apply a forcefolder rule to that directory or force game.exe. Run the game.exe by shortcuts or sandboxed explorer.exe.
If you locked-downed your box with only game.exe (and all its other exe and bin, ...) allowed to run (or to use network, and so on), then you can try to disable that config (then, time to verify what the exes do ...).
Sometimes, deleting (or just renaming the directory) sandboxed files in c:\windows\* and others annoying places can make it (conflicts ?) if you still have up to date (or compatible with the needs of the game) vc++ and other mandatory stuff installed unsandboxed. Sometimes, windows tries to apply a compatibility setting to a detected problematic specific exe (old or not so old) and things can go weird.
- lastly, thx to David, we can try various compatibility (or more) settings in sandboxie : RpcMgmtSetComTimeout, and other settings in advanced settings pannel and try to do more troubleshoots than ever with logs. Still have to find games that need to open holes. The worst case is a game made to not run in sandbox, get a refund.

**Comment by kolomeets80** [comment]
I can't repro this issue anymore. Resolving as it's unclear what went wrong.
