### ISSUE TITLE
Add ability to merge snapshot or delete snapshot

### ISSUE THREAD

**Issue by ukdoc** [sandboxie-plus/Sandboxie#151]
The snapshot feature is a great enhancement, however the ability to merge the snapshot with the layer below it would i think be a great enhancement, it addition to the delete function.

The scenario i see is for example:
1. Install application/game X
2. Create snapshot
3. Install patch to application/game
4. Test application/game

* If all OK merge the snapshot with the layer below,
* If there are problems at either install or runtime you can simply delete the snapshot without breaking the working application/game

**Comment by DavidXanatos** [comment]
I know, I'll add it soonisch

**Comment by ProjectBacker** [comment]
I've done this with batch files as long as you've defined the containers you can stop the sandboxie folder task clone it to Snapshot1 for example and re-launch your process.

However if DavidXanatos wants to make this automatic he will have succeeded in a request that was done since almost of the original Sandboxie owner.

If anyone wants me to post the batchfile code on how to do this let me know I won't clutter the repository for nothing.

Shawn.

**Comment by ukdoc** [comment]
@ProjectBacker Please do share your batch code as it will help us until David has time to work on an integrated solution.

**Comment by ProjectBacker** [comment]
@ukdoc I'll clean up the code to make it more user friendly I'll have it posted by tomorrow.  I'll see if I also have my regdiff and folder check tools on hand which makes re-installing and making just a patch diff for the sandbox.

The extra tool does a bit like https://bsa.isoftware.nl/ "Buster Sandbox Analyzer" but using simple batch files and a few public domain projects.

I'll get working on cleaning it asap and post as available.

**Comment by DavidXanatos** [comment]
The next build 0.5.0 will include snapshot merging features.
