### ISSUE TITLE
Firefox / Edge not responding (conflict with ESET)

### ISSUE THREAD

**Issue by Dmytro9099** [sandboxie-plus/Sandboxie#1545]
Hi. 
Windows 8.1 64-bit 
Firefox 96.0.1 
Sandboxie Classic 5.55.7
Firefox freezes and not responding when i run it in sandboxie. It appears after update to ver 96.0.1. Disabling extensions didn't help.
A clean reinstall Firefox, disabling antivirus protection didn't help
Here I find user with same problem ( but in german):  https://www.camp-firefox.de/forum/thema/134153-firefox-96-0-sandboxie-problem-ursachensuche/

**Comment by isaak654** [comment]
It's so weird to read about all these issues with Firefox and Thunderbird.... maybe some extra effort should be put to investigate about the update system (on both products) that seems to affect the sandboxes somehow.

**Comment by Rngexile** [comment]
FF + TB + sandboxie user here since +15 years. 
Lucky user, never had a problem.

Today : FF 96.01 + Win 10 last + sandboxie-plus 1.07 + many dedicated FF boxes (all hardened, some with new privacy mode) and many FF's profiles, many extensions + Win Defender AV + windows exploit protection with some tweaks from base config to add some (not all can be used with FF).
No problem at all.

I installed FF (and TB) outside sandboxie, without install update service and disabled updates with BITS (https://www.askvg.com/tip-block-firefox-to-download-updates-using-bits-on-windows/). FF is configured to check updates and let me chose when to install them (outside sandboxie, ofc), it may be related ?
Old gen CPU intel i7-3770K, without some new security stuff with new gen, it may be related ?

**Comment by isaak654** [comment]
I found out this portion of code that controls the browser updates inside the sandbox:

https://github.com/sandboxie-plus/Sandboxie/blob/0da573a7bdf34c69ef45d7f679a9c7322e609ddf/Sandboxie/core/dll/proc.c#L2224-L2228

I would suggest to replace the MatchDir line with:
`     MatchDir = L"\\Mozilla\\updates\\"; `

and adding below the Firefox code:

    } else if (Dll_ImageType == DLL_IMAGE_MOZILLA_THUNDERBIRD) {

        if (! Proc_IsProcessRunning(L"thunderbird.exe"))
            return FALSE;

        MatchExe = L"updater.exe";
        MatchDir = L"\\Mozilla\\updates\\";
        SoftName = L"Mozilla Thunderbird";

A long time ago, the updates folder was located in %ProgramFiles%\folder, but this doesn't seem the case anymore (at least on my setup).

**Comment by isaak654** [comment]
> A clean reinstall Firefox, disabling antivirus protection didn't help

Can you notice any difference with hardware acceleration disabled? Did you try to create a new sandbox too?

**Comment by Dmytro9099** [comment]
> 

I disabled hardware acceleration and created new sandbox ( after issue appeared, I updated to last SB ver with uninstalling previous one). But it didn't help. There is processes that created in sandbox, while FF freeze after launch
![image](https://user-images.githubusercontent.com/97784038/149658405-fed306f5-79ee-40f0-99be-0067c9511242.png)
It turned out, that 2-3 minutes later,  FF eventually runs, but it still freeze around 2 min every time i open new page.
In addition, FF Shut downs incorrectly. There is log from FF crashreporter:[CrashReporter.txt](https://github.com/sandboxie-plus/Sandboxie/files/7876897/CrashReporter.txt)

**Comment by Dmytro9099** [comment]
> > Hi.
> > Windows 8.1 64-bit
> > Firefox 96.0.1
> > Sandboxie Classic 5.55.7
> > Firefox freezes and not responding when i run it in sandboxie. It appears after update to ver 96.0.1. Disabling extensions didn't help.
> > A clean reinstall Firefox, disabling antivirus protection didn't help
> 
> Can you notice any difference with hardware acceleration disabled? Did you try to create a new sandbox too?

I disabled hardware acceleration and created new sandbox ( after issue appeared, I updated to last SB ver with uninstalling previous one). But it didn't help. There is processes that created in sandbox, while FF freeze after launch

 ![image](https://user-images.githubusercontent.com/97784038/149659716-1c77a921-347a-458b-bdcc-77d590efe375.png)

It turned out, that 2-3 minutes later, FF eventually runs, but it still freeze around 2 min every time i open new page.
In addition, FF Shut downs incorrectly. There is log from FF crashreporter:
[CrashReporter.txt](https://github.com/sandboxie-plus/Sandboxie/files/7876919/CrashReporter.txt)

**Comment by randyabr** [comment]
I too found Firefox either not opening or stop responding, etc. with Sandboxie Plus v 1.07. I too tried uninstalling and reinstlling everything. This is what worked instantly for me.

Uninstall Firefox and then install the Firefox enterprise version. The enterprise version is a stable version that only gets security updates on a regular basis and not feature updates. After doing this FF opened right up. In fact, perhaps a bit faster.
I was going to downgrade to a previous version but Mozilla recommended trying the enterprise version before downgrading due to security considerations.

hxxps://www.mozilla.org/en-US/firefox/enterprise/

**Comment by 0x391F** [comment]
> It turned out, that 2-3 minutes later, FF eventually runs, but it still freeze around 2 min every time i open new page. In addition, FF Shut downs incorrectly. There is log from FF crashreporter: [CrashReporter.txt](https://github.com/sandboxie-plus/Sandboxie/files/7876919/CrashReporter.txt)

![1](https://user-images.githubusercontent.com/56181919/149950183-3ab00409-fe53-4b89-a491-5f011cc6ff70.png)

+1, the same problem. Firefox works eventually after a few minutes. 
OS: Windows 10 Enterprise LTSC 2021 x64 (21H2)
Sandboxie 5.55.8 / Sandboxie-Plus v1.0.8

**Comment by mustwakeup** [comment]
Yes this issue came with 96 release, with older 95 no problems. 
BUT i have dual boot w7x64 and w10x64 and this issue is only in w 10x64. I try many other browsers and this is only in Firefox, include firefox based browsers.

**Comment by mustwakeup** [comment]
This issue came with 96 release, with older 95 no problems.

BUT i have dual boot w7x64 and w10x64 and this only occur in  w10x64. I try many other browsers, - include firefox based browsers - and this is only in firefox.

**Comment by 0x391F** [comment]
> @0x391F does deletign the box content solves your issue?

No, it doesn't.

**Comment by u20220618** [comment]
Win10 21H2 64Bit + Firefox 96.0.1/96.0.2 + Sandboxie Classic 5.55.7
I think this issue may caused by anti-virus software(I use the ESET Internet Security).
I found the issue solved in my computer after I disabled the "Banking & Payment Protection" function(must disable it in the standalone Advanced setup page, not only in the Main Window->Setup page).

**Comment by 0x391F** [comment]
> 

Yeah, it works! What a strange bug!

**Comment by mustwakeup** [comment]
Thanks, works now.

**Comment by Gishmasters** [comment]
> @0x391F does deletign the box content solves your issue?

Hello! Will you plane to fix it in future release? Disableing the "Banking & Payment Protection"  in Eset  is works, but this is temporary solution at this moment.

**Comment by Foosec** [comment]
Can confirm the Eset issue. Disabling Banking & Payment Protection works.
No such issue in Chrome however.

**Comment by 0x391F** [comment]
This bug seems doesn't reproduce anymore, now I using ESET Internet Security 15.1.12.0 and Sandboxie-Plus v1.1.3.

**Comment by isaak654** [comment]
This issue was reintroduced again in ESET Internet Security v16.0.22.0:
https://www.wilderssecurity.com/threads/eis-update-do-not-allow-ff-to-run-sandboxed.448495/

> Sandboxie PLUS 1.5.0
> Firefox v106.0.1
> EIS v16.0.22.0
> Windows 10 22H2 (OS Build 19045.2130)

<img src="https://user-images.githubusercontent.com/12372772/197859581-14afdc87-4f68-4d1b-8b83-8d6e173cf3d0.png" alt="ESET_conflict" height="250px">

**Comment by offhub** [comment]
[Disabling the feature solves the issue.](https://support.eset.com/en/kb5704-pause-or-disable-banking-payment-protection-in-eset-windows-home-products)

**Comment by gab12** [comment]
I confirm Disabling banking and payment protection fixes the problem on firefox and chrome (Workaround). Specifically  "Secure all browsers"  disabled suffices.

Thank you

**Comment by isaak654** [comment]
According to some feedbacks, this issue was fixed with the release of ESET 16.1.14.0.
