### ISSUE TITLE
Recovering a file from a Chrome download before the blue circle around the download icon leaves a copy in the Sandbox.

### ISSUE THREAD

**Issue by jedimasterspaz** [sandboxie-plus/Sandboxie#157]
Recovering a downloaded file from Chrome before the blue circle around the download icon at the bottom of Chrome stops blinking leaves a copy of the file in the Downloads directory in the sandbox.  So when I close Chrome, the Recovery window shows the same file that I already recovered.  If I wait until the blue circle stops blinking to click on the Quick Recover box then the file is recovered and a copy is not left in the sandbox.
This problem doesn't seem to happen in Firefox.

Thanks for looking into this when you have time.

**Comment by ProjectBacker** [comment]
Hi there I'm not the Dev however been using Sandboxie since the start of time so let's see if I can reproduce this with you and see what kind of fix is needed and at the same time give a break to the Dev that has been supporting this. Few Question''s Sandboxie Version : 
Chrome Version:
Did you change from original path for example D: instead of C: (as this might not let a recovery happen)

Do you have a download url example that does this issue? (If it's something that can be shared if not is it a program that may trigger chromes keep or delete feature such as sandboxies64 installation does?)


P.S: I'll gladly offer any help (What the heck am I going to do elsewise with all the covid lockdown's) 

Shawn

**Comment by kimski1** [comment]
How do you get files out of the new Sandbox?  The prior version was easy to use.  I'd open the tool from the tray and "recover".   Now I see the file in the folder I want it to go to but have no idea how to get it out of the sandbox.   I can't find any user guide info on the new version.  Please help!

**Comment by DavidXanatos** [comment]
sbie plus has now the same recovery features as the classic build had
