### ISSUE TITLE
Single App Sandbox / 1 click run

### ISSUE THREAD

**Issue by Chaython** [sandboxie-plus/Sandboxie#1570]
**Is your feature request related to a problem? Please describe.**
Convenience 
 
**Describe the solution you'd like**
I would like Sandboxie to detect installed app 
Make the installed app the default program to run
Single click in the GUI to run the program/box

**Describe alternatives you've considered**

**Additional context**
Instead of manually having to add program to run list / instead of having a run list, I would like a single click to run, single program box. So I can isolate each program to their own box and quickly launch them....

**Comment by Dyras** [comment]
I was thinking of something like this the other day. I think it could work great, especially for browsers, PDF readers and media players.

**Comment by DavidXanatos** [comment]
So 
1. make sbie+ detect links in the startmenu and or teh desktop and aut populate the run list <- all clear
2. "single click to run" <- what if thay are two links or more? do you want replace the box's double click action from open preferences to start one of the boxed programs? pelase be more clear with the 2nd part of your request

**Comment by Dyras** [comment]
I have no idea what he means but my suggestion for this is something like:

1. You install Sandboxie-Plus
2. A window pops up, asking which programs you want to run in a Sandbox
3. When you mark them, the templates for them are activated and they are forced into their own separate sandboxes.
4. The end result is that Sandboxie-Plus would be a lot easier to use. Fewer menus to go through, etc.

Possible collisions with software includes Firefox trying to update itself in the sandbox instead of outside of it.

**Comment by DavidXanatos** [comment]
one of the upcoming builds 1.2. or 1.4 wil auto scan the boxed start menu and populate the run sub menu.

So what you would want is to be able to switch the double click to open options to an arbitrary command form the run menu?
