### ISSUE TITLE
VLC freezes sometimes when skipping in a video - only while sandboxed

### ISSUE THREAD

**Issue by Dyras** [sandboxie-plus/Sandboxie#1636]
### What happened?

Hello! I've been running VLC in Sandboxie-Plus for quite some time now. And one thing has become certain:
There is definitely a freezing problem going on when it's used with Sandboxie-Plus. In fact, I remember this being a problem even with the pre-DavidXanatos versions of Sandboxie.

Will try to get a log for this tomorrow.

### To Reproduce

0. Run VLC in a sandbox. I run mine in a hardened Sandbox.
1. Open a long video. I noticed this while watching videos recorded by my professor at school. Around 1 hour in length
2. Skip back and forth as you naturally would do while trying to write something down
3. Sometimes it freezes 100%. Sometimes the video keeps playing but VLC thinks it's frozen. There seems to be no logic to it. However, it 100% never happens when run outside of Sandboxie-Plus.

### Expected behavior

It shouldn't freeze like this

### What is your Windows edition and version?

Windows 10 Edu 21h2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Windows Defender, Malwarebytes Anti-Exploit

### What version of Sandboxie are you running?

Latest Sandboxie-Plus at the time of writing

### In which sandbox type you have this problem?

In a Hardened sandbox (red sandbox icon).

### Is the sandboxed program also installed outside the sandbox?

Yes, it is also installed outside the sandbox.

### Can you reproduce this problem on an empty sandbox?

I can confirm it also on an empty sandbox.

### Did you previously enable some security policy settings outside Sandboxie?

Probably, but I don't think it's relevant

### Sandboxie.ini configuration

```shell
Enabled=y,User
AutoRecover=n
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,off,6
Template=SumatraPDF
Template=SumatraPDF_Folder
Template=VLC_DirectAccess_Photos
Template=VLC_DirectAccess_Profile
Template=Firefox_Force
Template=Firefox_Cookies_DirectAccess
Template=Firefox_Bookmarks_DirectAccess
Template=Firefox_Passwords_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=Firefox_Session_DirectAccess
Template=Firefox_Profile_DirectAccess
Template=Brave_Force
Template=Brave_Preferences_DirectAccess
Template=Brave_Profile_DirectAccess
Template=Brave_Sync_DirectAccess
Template=Brave_Passwords_DirectAccess
Template=Brave_Phishing_DirectAccess
Template=Brave_Cookies_DirectAccess
Template=Brave_Bookmarks_DirectAccess
Template=Brave_History_DirectAccess
Template=OpenBluetooth
Template=SkipHook
Template=FileCopy
Template=qWave
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=AutoRecoverIgnore
ConfigLevel=9
ClosePrintSpooler=y
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
BoxNameTitle=-
CopyLimitKb=81920
PromptForInternetAccess=y
ProcessGroup=<StartRunAccess>,vlc.exe,sumatrapdf.exe,firefox.exe,explorer.exe,brave.exe
ProcessGroup=<InternetAccess>,firefox.exe,brave.exe
OpenFilePath=<InternetAccess>,E:\
OpenFilePath=brave.exe,C:\Users\User\AppData\Local\BraveSoftware\
DropAdminRights=y
ClosedIpcPath=!<StartRunAccess>,*
LeaderProcess=<StartRunAccess>

(I don't have VLC set to forced at this moment, since this bug is getting annoying)
```

**Comment by Rngexile** [comment]
Hello,
I use VLC + sandboxie (and now VLC + sandboxie-plus) since the beginning of old Tzuk sandboxie and i can't remember a regular problem like yours.
Maybe few times with very old and broken avi/ogm files few years ago (way before David's sandboxie, and same behavior  inside/outside box). All fine with usual proper personnal encoded files or not, with various containers, codecs and lenghts, from cameras, smartphone, dvds, internet, ...

**Current config similar to yours :** 
windows 10 home x64 21H1 updated 
VLC 3.0.16 installed outside a sandbox
sandboxie-plus 1.0.15
Windows defender (+ few exploit mitigations that works for vlc.exe and vlc-gen-cache.exe)
UAC set to max
videos on hard disc drives, cpu intel i7-3770k

**I don't have "Malwarebytes Anti-Exploit" on my pc.**

**Just tested** with few files mp4, avi, mkv, 30min to 4h23 (lord of the ring 3 dc, 20Go), mostly h264/h265 encoded files.
Tested with my usual manually hardened box for VLC then tested with a new test "red" box+ some basic tweaks.
I have tested changes in "hardware decoding" parameter in VLC>codecs pannel (d3d11, dxva2, disabled / auto by default).
Many many skip back and forth.
**Result on my end : no issue, i can't reproduce your problem.**

**"red" (private hardened) test box :** 
```
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
BorderColor=#00ffff,ttl,6
Template=SkipHook
Template=FileCopy
Template=BlockPorts
Template=LingerPrograms
ConfigLevel=9
DropAdminRights=y
UsePrivacyMode=y
BoxNameTitle=n
ClosePrintSpooler=y
CopyLimitKb=81920
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
ClosedFilePath=<BlockNetDevices>,InternetAccessDevices
NormalFilePath=J:\VIDEOS
```

Maybe test without any **"Malwarebytes Anti-Exploit"** option ?
Or "hardware decoding" parameter in VLC>codecs pannel + new win32k hook option in sandboxie-plus ?

**Comment by Dyras** [comment]
I've been thinking about this and I think my old issues with the Tzuk version of Sandboxie was with MPC-HC or SMPlayer. Those years of my life are just a big blur.

Anyway, I've been trying to reproduce this while getting a trace log and I just can't get it to crash while the trace log is running.

It might very well be that my Windows install is weird. If this was an issue affecting everyone, there should be at least 1 other post in here about it.

I'll switch to MPC-HC and hope that solves the issue, if not I'll try to get that trace log again.

Thanks for testing!!
