### ISSUE TITLE
remove russian language from sbie in response to the country's invasion of Ukraine

### ISSUE THREAD

**Issue by diieg707** [sandboxie-plus/Sandboxie#1662]
### Is your feature request related to a problem or use case?

remove russian language from sbie in response to the country's invasion of Ukraine

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by diieg707** [comment]
> I think a solidarity message in russian on the "About Sandboxie-Plus" window would be much better (in case @lufog is interested):
> 
> https://github.com/sandboxie-plus/Sandboxie/blob/5b21ae4ce9f5fa9cdfcc5a6785cd5a29b054ca9c/SandboxiePlus/SandMan/sandman_ru.ts#L1570

preferably put this "solidarity message" up front in the gui so everybody can see it, as we don't usually click on the  "About Sandboxie-Plus"

**Comment by DavidXanatos** [comment]
Russian citizens are not the only people who speak Russian...
I mean if Spain would invade Portugal, we would not remove Spanish, because of all the other not Spanish people still using Spanish, right?

According to this wikipedia map: https://en.wikipedia.org/wiki/Russian_language#/media/File:Russian_language_status_and_proficiency_in_the_World.svg there are a few other countries that have Russian as the official language or > 30% of its population speaks Russian, 2 of them even EU member states.

Also I don't think its a good idea to add contemporary messages to software, these get old quick, but software may be used for decades.

**Comment by lufog** [comment]
I am a Russian speaking Ukrainian. Many post-Soviet countries that are not part of Russia also use Russian in everyday life. I consider it wrong to remove the Russian language, or add any notifications, pop-ups and other things. Moreover, the Ukrainian translation of this program is based on the Russian translation, since all my mistakes and features, such as hot keys in brackets, have migrated to it.

I my opinion, open source is not a place for politics, and discrimination based on language, race, etc.

**Comment by diieg707** [comment]
> Soviet countries that ar



> 



> Russian citizens are not the only people who speak Russian... I mean if Spain would invade Portugal, we would not remove Spanish, because of all the other not Spanish people still using Spanish, right?
> 
> According to this wikipedia map: https://en.wikipedia.org/wiki/Russian_language#/media/File:Russian_language_status_and_proficiency_in_the_World.svg there are a few other countries that have Russian as the official language or > 30% of its population speaks Russian, 2 of them even EU member states.
> 
> Also I don't think its a good idea to add contemporary messages to software, these get old quick, but software may be used for decades.

turns out a agree with you, but let's not forget russian people are sponsoring this war with that lunatic as president, i thought some sort of boycott would be needed

**Comment by isaak654** [comment]
As reported above, there is no consensus on this.
