### ISSUE TITLE
Block (All) Internet Access (ini) Bug

### ISSUE THREAD

**Issue by Coverlin** [sandboxie-plus/Sandboxie#185]
created ini entry
- Sbie+ 0.4.3 Preset or checkbox in box Options 
`ClosedFilePath=!<InternetAccess>,InternetAccessDevices`
- Sbiectrl Block All programs button
`ClosedFilePath=InternetAccessDevices`

If set by sbie+ , it won't show as blocked in ctrl cause there is no process set, visual "downside" only
If set by sbiectrl , sbie+ can't toggle the state using the preset or the options -> net access -> block checkbox (will also show unchecked) to fix it the user has to use sbiectrl to reverse the block or edit the ini themselves
Can be a problem for ppl switching to sbie+ with existing settings

Fix
Sbie+ should read if theres a process (example `ProcessGroup=<InternetAccess>,proc1.exe,proc2.exe`....) and if no process is set , create the same config entry as sbiectrl instead

Related bug: Using sbie+ to remove all processes leaves a empty entry `ProcessGroup=<InternetAccess>,` but has no downsides to it

Offtopic : my sbie+ title shows wrong driver #   "Sandboxie-Plus v0.4.3   -   Driver: v5.43.5"

**Comment by DavidXanatos** [comment]
thanks you are right, will fix that in the next build....

About sbie+ title shows wrong driver,
that's a bit confusing I admit, the title is not supposed to show the actual binary version of the driver but the version of the drivers ABI interface. And since 5.43.5 I haven't changed anything in the driver that would make it incompatible with the later versions untill 5.44.0 that is that's changing things hence its changed.

I probably should eider remove this info or use a separate naming scheme for it.
