### ISSUE TITLE
OpenFilePath no longer works on file level - bug still exists in 5.43.7 x64

### ISSUE THREAD

**Issue by otto1984** [sandboxie-plus/Sandboxie#187]
Hi,

thx for trieing to fix the bug, but it still exists  also in version 5.43.7 x64 can you please check it  again? 

I used the OpenFilePath parameter to allow access to the bookmarks file and block other changes in the profile.

OpenFilePath=%UserProfile%\AppData\Local\Microsoft\Edge\User Data\Default\Bookmarks

When I add a new bookmark, it is not saved in the Bookmars file and is removed after closing the sandbox.
If I set the OpenFilePath to

OpenFilePath=%UserProfile%\AppData\Local\Microsoft\Edge\User Data\Default\

The Browser can save the new bookmarks
The setting works for years with the original sandboxie software.
I have the same behavior with the Brave Browser.

Thx

**Comment by DavidXanatos** [comment]
That is strange I have tested the current build again with the option
OpenFilePath=%Local AppData%\Google\Chrome\User Data\Default\Bookmarks*
and the original google chrome and it was saving the bookmarks fine.

What I have noticed though is that the parent folder must exist on the PC for this in order to work.

I have tried the old 5.33.6 Sophos build and it expressed the same behavior if the path wasn't there the operation failed.

I agree that this behavior is not what the user might expect so I'll look into changing that...

**Comment by otto1984** [comment]
Hi DavidXanatos,

what did you mean exactly with?

"What I have noticed though is that the parent folder must exist on the PC for this in order to work."

Does the parent folder have to exist inside the sandbox? 

%Local AppData%\Google\Chrome\User Data\Default

**Comment by DavidXanatos** [comment]
No it has to exist in the real user profile, otherwise chrome is unable to save the bookmarks outside the sandbox, even though it is permitted to do so.

**Comment by otto1984** [comment]
Hi DavidXanatos,

I have upgraded to version 5.44.1. Now it works as expected.
From my side you can close the issue.

Thx
