### ISSUE TITLE
How to restrict File Access to the most of my drives?

### ISSUE THREAD

**Issue by macruspareto** [sandboxie-plus/Sandboxie#194]
Hello everyone!
Sandboxie is working great so far! 

But is there an option to selectively allow access to the bare minimum of locations on my HDDs?
I can restrict certain directories through "Settings - Resource Access - File Access - Blocked Access" and add as many entries as I want. But can I do it in reverse - "whitelist" only a few and deny the rest?

In this case, if malware strikes me inside the sandbox, it won't steal any cookies or certificates or config files scattered across my C:, D:, E: etc ...

**Comment by LakeishaKowalczyk** [comment]
+1
Resource access restrict WhiteList Mode is one of the most needed features

@DavidXanatos 
Please consider it, thanks, love you

**Comment by DavidXanatos** [comment]
I know and such a feature is already in planning.

**Comment by LakeishaKowalczyk** [comment]
> 
> 
> I know and such a feature is already in planning.

love you

**Comment by lwcorp** [comment]
Since there are duplicates of this ticket (this one seems to be the original), can you close them and mark them as duplicates?

In any case, the open source [DOSBox](https://www.dosbox.com) has had isolation technology since its foundation 20 years ago.
You basically decide in advance to which path a launched program is allowed to access, up to only the launched program's own folder.
Is it possible for you to borrow this code to achieve the same effect?

**Comment by isaak654** [comment]
Update: if you have new suggestions, please post on the new issue #890, thanks.
