### ISSUE TITLE
Chrome crashing - 

### ISSUE THREAD

**Issue by bjm234** [sandboxie-plus/Sandboxie#198]
I'm curious regarding >
https://www.wilderssecurity.com/threads/sandboxie-plus-sbie-fork.427755/page-32#post-2965457

**Comment by bjm234** [comment]
adding 
https://www.wilderssecurity.com/threads/sandboxie-plus-sbie-fork.427755/page-33#post-2967501

**Comment by DavidXanatos** [comment]
hmm... this issue is really particularly annoying I have debugged it yesterday all day long and here is what it happens the website's js invokes some chrome function that than wants to get a list of registered URI handles using "FindAppUriHandlers"
This call goes through the COM system and that's where everything goes horribly wrong, sandboxie fails to proxy the operation properly.
Returning an error, and chrome instead of properly handling that error just crashes with NULL pointer exception. 

First of all chrome should validate the result and not just run with it:
in chrome 86: .\chromium\src\content\browser\installedapp\installed_app_provider_impl_win.cc
line 48:   HRESULT hr = found_app_list->get_Size(&found_app_url_size);
found_app_list is NULL and than chrome crashes,
chrome should check if the variable is not null before de referencing it!

Now this particular functionality is part of the WinRT subsystem, so as sandboxie does not support modern apps making this work is probably futile.

So her comes a sledgehammer workaround, add
ClosedFilePath=*\Windows.System.Launcher.dll
to your sandboxie.ini

with that any process trying to load that particular interface will fail and if its not a pile of garbage not crash but accept the fact that this one is not available, like its for example the case on all Win7 machines.

Now should I put that into a template for chrome and alike or hard code it in the SbieDLL... wouldn't be first of such fixes Sophos and Co added very many hard coded workarounds...

**Comment by kimski1** [comment]
My problem with Chrome crashing happens just with LinkedIn and it started about 2 weeks ago.  Is this related?

I see the note about "fixed in next build".  When is that?   How do I get SB to update?  I don't see an option to check for version in the tool?

**Comment by qazero** [comment]
Looks like this issue has come back and the workaround isn't working anymore. I noticed that Brave web browser (chromium based) automatically closes randomly when going to app.plex.tv. Sometimes it works and sometimes it doesn't. Any ideas what may be causing it?

**Comment by qazero** [comment]
Any update regarding this?
