### ISSUE TITLE
Spotify crashes on launch when sandboxed

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#2035]
_Originally posted by @TooYoungTooSimp_

> I encontered this problem in ~an electron based~ a CEF based app (Spotify), it flickers on start, then disappeared.
>
> I noticed a change of chrome_elf.dll, so I think it may be a election (upstream) bug.
>
> I tried [this solution](https://github.com/sandboxie-plus/Sandboxie/issues/2023#issuecomment-1186537910) on Spotify.exe, unfortunately, it makes my PC BSOD with the error `PAGE_FAULT_IN_NONPAGED_AREA`
> <a name="beginning"></a>
> ### minidump file provided below
> [Minidump.zip](https://github.com/sandboxie-plus/Sandboxie/files/9127939/Minidump.zip)

### Download link
https://www.spotify.com/us/download/windows/

### Where is the program located?

It is installed only inside a standard box.

### Affected Sandboxie version
[Sandboxie Plus 1.2.3 x64](https://github.com/sandboxie-plus/Sandboxie/releases/tag/v1.2.3)

### Windows system

W10 21H2 x64

### Workaround that doesn't work reliably

- [ ] I added `SpecialImage=chrome,spotify.exe` to my clean standard sandbox.
It works fine on my system, except the following errors in the notification popup:
![Spotify_inside_the_sandbox](https://user-images.githubusercontent.com/12372772/179411372-f006f14a-a165-4dc0-aa5c-54fa70714948.png)

### When the workaround doesn't work at all

- [ ] In some odd systems, the workaround will cause a BSOD: see the [Minidump.zip](#beginning) provided in the initial quote.

**Comment by APMichael** [comment]
Thanks for the issue report. Then I'm not the only one with a BSOD caused by the latest versions 1.2.x!

For me, launching an Opera browser installed directly into a sandbox causes the BSOD.
https://www.wilderssecurity.com/threads/sandboxie-plus-v1-2-1-v1-2-2-v1-2-3.445923/#post-3092407

(Electron is Chromium based and Opera is also Chromium based. Whether this is the cause or maybe the reworked hook management, only David can find out.)

**Comment by DavidXanatos** [comment]
Is this issue new with 1.2.x or if you go back to older builds it is also present?

**Comment by APMichael** [comment]
The BSODs are caused only by versions 1.2.0, 1.2.1, 1.2.2 and 1.2.3. 

With the still current release version 1.1.3 and all older versions a BSOD was never caused.

**Comment by DavidXanatos** [comment]
are you running the 32 or 64 bit version of opera / spotify?

**Comment by APMichael** [comment]
A big apology, I was under the impression that I had Opera then installed in the 64-bit version, but it is the 32-bit version! (I must have used the wrong offline installer).

Have now installed Opera in my VM as 32-bit version and Windows crashes here now too! So the issue seems to be related to 32-bit.

(I emailed you the link to the memory dump this afternoon. The memory dump is then also the 32-bit version of Opera.)

**Comment by DavidXanatos** [comment]
I think I found the bug there was a minor issue with the driver that manifests itself when running 32 bit code and using win32 hooks

**Comment by hjkltop** [comment]
![image](https://user-images.githubusercontent.com/47598373/182803302-ab7eaecd-1f68-4063-a829-f42b4ab03821.png)

![image](https://user-images.githubusercontent.com/47598373/182803571-0e7d952e-a002-4951-8222-6174152c6ef7.png)

1.2.7 is still wrong

**Comment by isaak654** [comment]
It does not seem to be the same as the BSOD issue that was fixed here, so you may want to open a new issue with the most accurate details (including the logs shown in your second screen).

**Comment by isaak654** [comment]
It does not seem to be the same as the BSOD issue that was fixed here, so you may want to open a new issue with the most accurate details (including the logs shown in your second screen). It is not even similar to the unfixed task (lack of details affects reports as well).

**Comment by hjkltop** [comment]
> It does not seem to be the same as the BSOD issue that was fixed here, so you may want to open a new issue with the most accurate details (including the logs shown in your second screen). It is not even similar to the unfixed task (lack of details affects reports as well).
[WXWorkWeb3ef251.zip](https://github.com/sandboxie-plus/Sandboxie/files/9258429/WXWorkWeb3ef251.zip)
