### ISSUE TITLE
Disable the EditAdminOnly message(s) for UAC users

### ISSUE THREAD

**Issue by Luro223** [sandboxie-plus/Sandboxie#2239]
### Is your feature request related to a problem or use case?

After upgrading from version 1.3.2 some users noticed the constant messages for UAC users with standard rights
It would be more convenient if these messages could be disabled

### Describe the solution you'd like

The feature under `Config Protection` to hide all warning messages or hide the specific message

**Comment by APMichael** [comment]
This is a side effect of this issue: #2195
(Should be finally fixed with the next version.)

**Comment by Luro223** [comment]
@APMichael I think it's side effect of update 1.3.3 #2237 it started happening after this: "improved SandMan settings behaviour for non admin users #2123"

**Comment by APMichael** [comment]
Just for information:

With version 1.3.3 the issue #2195 was tried to be fixed. However, this failed unfortunately and the issue occurs since then even with all Sandboxie users.

Since SandMan does not find the DefaultBox, there is always a write access to the Sandboxie.ini at startup and therefore the message is now always displayed for non-administrator users.

If the issue is fixed with the next version, then there is no more write access to the Sandboxie.ini and therefore there will be no more message.

**Comment by Luro223** [comment]
Closing the issue as dupe of #2123 and #2195 
@APMichael I think it's better to hide the message(s) instead disabling the feature "Watch Sanboxie.ini for changes"

**Comment by APMichael** [comment]
> @APMichael I think it's better to hide the message(s) instead disabling the feature "Watch Sanboxie.ini for changes"

You don't have to disable the option "Watch Sandboxie.ini for changes" if the issue #2195 is fixed in the next version.

And I am not against your feature request! I just wanted to inform you that the messages are currently caused by the issue #2195.

**Comment by Luro223** [comment]
@APMichael It's ok I just closed because of dupe
Have a great time
