### ISSUE TITLE
SBIE2224 Sandboxed program has crashed: steamerrorreporter.exe

### ISSUE THREAD

**Issue by idimo** [sandboxie-plus/Sandboxie#231]
can someone help me fix this error?

**Comment by roflankotan** [comment]
same problem @DavidXanatos

**Comment by cocofz** [comment]
Please tell me here if you solve that :( PLEASE  SBIE2224 Sandboxed program has crashed

**Comment by idimo** [comment]
noticed that this crash steamerrorreporter.exe occurs when one of the games in the library tries to download a game update or download the account configuration from the cloud. please help me fix it

**Comment by idimo** [comment]
ok I have even more errors due to running DotA 2 in the sandbox

19:03:12.502   Sbie Directory: C:\Program Files\Sandboxie-Plus                                                                     
19:03:12.502   Loaded Config: C:\Windows\Sandboxie.ini                                                                             
19:20:57.799   steamerrorreporter.exe (7504): SBIE2224 Sandboxed program has crashed: steamerrorreporter.exe [01]                  
19:26:37.494   WerFault.exe (4304): SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1   
19:26:38.056   WerFault.exe (4304): SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1   
19:26:41.462   WerFault.exe (6292): SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1   
19:26:41.972   WerFault.exe (6292): SBIE2101 Object name not found: , error OpenProcess (C0000022) access=001FFFFF initialized=1   
19:26:46.039   steamerrorreporter.exe (12424): SBIE2224 Sandboxed program has crashed: steamerrorreporter.exe [03]                 
19:26:52.163   steamerrorreporter.exe (13136): SBIE2224 Sandboxed program has crashed: steamerrorreporter.exe [02]

**Comment by cocofz** [comment]
I uninstal game and sanboxie  and i get out internet cable. When i instal Sanboxie 5.31.6 Multilingual , cracked not buyed , but first today work verry well and virustotal says dont has virus , so , when i instal sanboxie i get two identic messages from windows :
 PROGRAM COMPATIBILITY ASISTANT - "This app can't run because it causes security or performance issues on windows. A new version may be available. Check  with your software provider for an updated version that runs on this version of windows.  "  after i close two mesages instaling continue like everytime , when i open DEFAULTBOX from SANBOXIE and i push RUN ANY PROGRAM and i chose my game , appear this error SBIE2224 Sandboxed program has crashed 'and name of my game' . So is posible to get this errors from new updates windows ??? I try to reinstal another version windows from decembre 2019 because This Sanboxie 5.31.6 worked verry well on year , but today when i reinstal windows wiht new version windows from microsoft with all updates , Sanboxie dont work :(

**Comment by cocofz** [comment]
I uninstal game and sanboxie and i get out internet cable. When i instal Sanboxie 5.31.6 Multilingual, but first today work verry well and virustotal says dont has virus , so , when i instal sanboxie i get two identic messages from windows :
PROGRAM COMPATIBILITY ASISTANT - "This app can't run because it causes security or performance issues on windows. A new version may be available. Check with your software provider for an updated version that runs on this version of windows. " after i close two mesages instaling continue like everytime , when i open DEFAULTBOX from SANBOXIE and i push RUN ANY PROGRAM and i chose my game , appear this error SBIE2224 Sandboxed program has crashed 'and name of my game' . So is posible to get this errors from new updates windows ??? I try to reinstal another version windows from decembre 2019 because This Sanboxie 5.31.6 worked verry well on year , but today when i reinstal windows wiht new version windows from microsoft with all updates , Sanboxie dont work :(

**Comment by cocofz** [comment]
Hey Guys , i reinstaled windows 10 Pro from Decembre 2019 and Sanboxie work . So problem i think is from security windows udpates.  GL

**Comment by idimo** [comment]
> Привет, ребята, я переустановил Windows 10 Pro с декабря 2019 года, и Sanboxie работает. Так что проблема, я думаю, связана с обновлением окон безопасности. GL
soooo now we know that crashes are related to the latest Windows 10 updates, nice

**Comment by idimo** [comment]
> Hey Guys , i reinstaled windows 10 Pro from Decembre 2019 and Sanboxie work . So problem i think is from security windows udpates. GL
soooo now we know that crashes are related to the latest Windows 10 updates, nice

**Comment by cocofz** [comment]
what is wrong for me is i see mesages with this error from last year , but to me work verry well from december until today when i wanna reinstal Windows with all updates , i reinstaled windows 10 again whitout updates , i havedm stick with windows from  2 months ago , i instaled dont work . I haved saved windows from december 2019 on extern hdd , i instaled and work like in December :) So from now i know , dont update , i stoped updatet from group policy , and now i instal all my stuff. I dont know if someone solved this ,I searched for about 5 hours continuously today, youtube, google, I didn't find anything, what I found didn't work for me or for others who commented in the comments. If you get another solve , please write there.I know what do you say ,and for me it was hard to reinstall windows and all Sandboxie settings, I lost all day today just for that to look for a solutions and reinstall windows and then the settings, I couldn't find another way, it was definitely easier. Thanks and GL.

P.S. IF SOMEONE GET SOLUTION PLEASE WRITE THERE> THANKS>

**Comment by me-20201219** [comment]
I have Windows 8.1 , and I have the same problem since the last Windows update:
SBIE2224 Sandboxed program has crashed: ffmpeg.exe [JDownloader]

I wasn't sure if it was Sandboxie because I updated to version 5.45 the same day, but even after I reinstalled Verion 5.43.7, the problem persists.

**Comment by cocofz** [comment]
Hey guys , i dont know the reasons but Sandboxie is Free now. So i instaled and work ...

**Comment by cocofz** [comment]
with multiple Box . Sanboxie Plus i have now ... G L

**Comment by genesisvlzqz** [comment]
Does anyone know if this problem has been fixed?

**Comment by cocofz** [comment]
> 
> 
> Does anyone know if this problem has been fixed?


Sandboxie now is free , whitout problems ;)

**Comment by ntx2611** [comment]
> 
> 
> > Hello I have the same problem in Windows 11, with Bandicam. `bdcam.exe (1016): SBI2224 Sandboxed program has crashed: bdcam.exe [Bandicam]`
> > Is there any FIX?
> 
> Bro the crushes was when i get sanboxie cracked , now is FREE sanboxie and i dont have issue. ;) Gl

Hello,
Normally, I can open Teams client in windows 10 without any issue
but i got error message : SBIE2224 with windows 11
The current version I'm using: sandboxie-plus 0.9.6

**Comment by Arslan30** [comment]
I was using it for csgo and was easily able to run 3-4 instances (i5-4570+750ti+16GB RAM+30GB paging) but now as soon as a map finishes loading, it crashes. 

Is it also related to security updates or am I having a different problem?

**Comment by isaak654** [comment]
> I was using it for csgo and was easily able to run 3-4 instances (i5-4570+750ti+16GB RAM+30GB paging) but now as soon as a map finishes loading, it crashes.
> 
> Is it also related to security updates or am I having a different problem?

Currently this repository contains 61 releases, so it would be preferable to know which release introduced this regression for the first time.

**Comment by Arslan30** [comment]
> > I was using it for csgo and was easily able to run 3-4 instances (i5-4570+750ti+16GB RAM+30GB paging) but now as soon as a map finishes loading, it crashes.
> > Is it also related to security updates or am I having a different problem?
> 
> Currently this repository contains 61 releases, so it would be preferable to know which release introduced this regression for the first time.

I have been using Sandboxie-Plus-x64-v0.9.6 from day 1 and haven't upgraded or downgraded

**Comment by Arslan30** [comment]
> I was using it for csgo and was easily able to run 3-4 instances (i5-4570+750ti+16GB RAM+30GB paging) but now as soon as a map finishes loading, it crashes.
> 
> Is it also related to security updates or am I having a different problem?

Also, I have tried running 2 instances; one normally and 2nd in sandboxie and sandboxie one always crashes

**Comment by isaak654** [comment]
If you never moved from Sandboxie-Plus-x64-v0.9.6, then I doubt it's related to security updates... more likely this is about some csgo update happened outside or inside the sandbox. It would be interesting to know if you can reproduce the same in a new clean sandbox to better define your issue.

**Comment by the-ch8** [comment]
There are some similar sandbox messages causing the new version **[2.5.4]** of **PromptOptimizer** to fail to open correctly and crash, whereas it opens successfully on older versions **[e.g., PromptOptimizer 2.2.1]**.

```text
12.02.2026 16:54:22.719   PromptOptimizer.exe: SBIE2224 Sandboxed program has crashed: PromptOptimizer.exe [PromptOptimizer]
12.02.2026 16:55:42.667   PID: 2848: SBIE2205 Service not implemented: WMI IWbemServices 19
```
