### ISSUE TITLE
Failed to communicate with Sandboxie Service: *GUIPROXY_00000001 Error!

### ISSUE THREAD

**Issue by kimpurcell** [sandboxie-plus/Sandboxie#233]
Hi, I keep getting these errors whenever I hit the keyboard or move the mouse in a Sandboxed window.

SBIE2203 Failed to communicate with Sandboxie Service: *GUIPROXY_00000001 - <processname here>

I get multiple of these errors. Please help!

**Comment by DavidXanatos** [comment]
do you have any other security software installed that ma interferer?

**Comment by kimpurcell** [comment]
No I don't have any other security software installed. It happens whenever I move the mouse or hit the keyboard after launching a game. The message doesn't happen when I'm using a gamepad.

**Comment by typpos** [comment]
I get this error with some Unity-based games. Application runs and shows strange behaviour: Mouse/keyboard actions work on UI-elements like buttons and menus, but not on "main game area", eg, objects on maps.  Example: Torchlight III. Unable to get past "select class" intro screen because unable to select a class from map, but able to select menu options to start of exit game.

**Comment by kimpurcell** [comment]
yes, that's exactly what I"m facing. It's a 3D game, and mouse doesn't respond. Moving the mouse or hitting the keyboard triggers the GUIPROXY error.

**Comment by typpos** [comment]
@kimpurcell do you find that at app-startup in full-screen your mouse cursor is at the top-left corner and not responding until you either click the mouse or ALT-TAB out then back?

I wonder if the issue is related to user input or actually the result of screen coordinate mapping to world space. From distant memory, the Game APIs have different pathways for determining mouse positions in world space vs UI elements. Either way, many other games work just fine, so it's confusing (and frustrating).

Another one that does not work is Tropico 6. Game starts fine; can click around on menus to configure and start a game; but once the world map shows it's impossible to select buildings. Popup dialogs work fine. Zooming in/out works fine.

**Comment by kimpurcell** [comment]
For me it's Cyberpunk 2077. I have my scaling set at 150% since I have a huge monitor. I have to ALT-TAB out of that annoying Sandboxie window and use my gamepad for it to work.

**Comment by typpos** [comment]
Same. Can't even "press space to continue" during intro video.

**Comment by kimpurcell** [comment]
Yeah ☹️

**Comment by isaak654** [comment]
@DavidXanatos You can remove the "more info needed" label, as the info was effectively provided by the author of the issue.

**Comment by DavidXanatos** [comment]
> 
> 
> For me it's Cyberpunk 2077. I have my scaling set at 150% since I have a huge monitor. I have to ALT-TAB out of that annoying Sandboxie window and use my gamepad for it to work.

So... to get rid of the annoying window you should be able to set the message to be always ignored.
The message is related to cursor position clipping and does not seam to cause any other problems.

The not working input is a unrelated issue, it is caused by the sandbox isolation,
you can work that around by adding `NoAddProcessToJob=y` to the particular box in which you are running the game,
but WARNING that will weaken the sandbox isolation!!!

Is that an workable solution for you?

**Comment by typpos** [comment]
> you can work that around by adding `NoAddProcessToJob=y` to the particular box in which you are running the game,
> but WARNING that will weaken the sandbox isolation!!!

I can't find any documentation for that setting. It's noted as a new debug-option for v.0.3.5, but what does it do and how does it lower security? The apps I run tend to be fully dis/untrusted.

**Comment by kimpurcell** [comment]
> > For me it's Cyberpunk 2077. I have my scaling set at 150% since I have a huge monitor. I have to ALT-TAB out of that annoying Sandboxie window and use my gamepad for it to work.
> 
> So... to get rid of the annoying window you should be able to set the message to be always ignored.
> The message is related to cursor position clipping and does not seam to cause any other problems.
> 
> The not working input is a unrelated issue, it is caused by the sandbox isolation,
> you can work that around by adding `NoAddProcessToJob=y` to the particular box in which you are running the game,
> but WARNING that will weaken the sandbox isolation!!!
> 
> Is that an workable solution for you?

Thanks, David! I’m afraid I need the sandbox isolation. May I know how NoAddProcessToJob weakens the isolation?

**Comment by kimpurcell** [comment]
> > you can work that around by adding `NoAddProcessToJob=y` to the particular box in which you are running the game,
> > but WARNING that will weaken the sandbox isolation!!!
> 
> I can't find any documentation for that setting. It's noted as a new debug-option for v.0.3.5, but what does it do and how does it lower security? The apps I run tend to be fully dis/untrusted.

I have the same question and concerns. I hope Sandboxie is secure, so many hacking incidents nowadays can’t trust any executable. Malware can be hidden so well it’s 99% undetectable.

**Comment by DavidXanatos** [comment]
Having the process in a job adds the following restrictions:
info.UIRestrictionsClass = JOB_OBJECT_UILIMIT_EXITWINDOWS
                         | JOB_OBJECT_UILIMIT_HANDLES
                         | JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS
                         | JOB_OBJECT_UILIMIT_READCLIPBOARD;

EXITWINDOWS and READCLIPBOARD is quite self explanatory
these are user handles: https://docs.microsoft.com/en-us/windows/win32/sysinfo/user-objects this restriction primarily prevents processes from sending window messages across the sandbox boundary 
and those are the system parameters https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfoa

Now, being in a job is not the only thing that prevents processes from sending window messages to un sandboxed processes, the UIPI mechanism https://en.wikipedia.org/wiki/User_Interface_Privilege_Isolation also prevents sending messages to most un sandboxed processes, except when they have the integrity level set to un-trusted.

So the job object isolates here mostly one sandbox from an other, as all sandboxed processes have un-trusted integrity level.

I think for running games it in a dedicated sandbox it is fairly reasonable to specify `NoAddProcessToJob=y` for that game box.

**Comment by typpos** [comment]
Thanks, @DavidXanatos. Interesting details.

I can confirm Tropico 6 works with Sandboxie v5.45.0 x64 if "NoAddProcessToJob=y" is set. The GUI Proxy errors still pop up but can seemingly be ignored. Tropico 6 does not work without this setting.

@kimpurcell: I now got Cyberpunk to work in v5.45.0 WITHOUT the "NoAddProcessToJob" setting. Puzzling because it didn't work previously when I tried a new version of sandboxie.

**Comment by DavidXanatos** [comment]
I suspect the issue is related to #176 the proper fix for it will be to hook the troublesome functions and proxy all the requests through the helper service.

**Comment by DavidXanatos** [comment]
It indeed was related to #176 I have fixed it and now i.e. with the next build you will be able to have working space bar, and other input without  "NoAddProcessToJob=y"

**Comment by kimpurcell** [comment]
That’s excellent news David! Thank you!
