### ISSUE TITLE
[REQUEST] Icon themes

### ISSUE THREAD

**Issue by Valinwolf** [sandboxie-plus/Sandboxie#235]
First I would like to say that I love the new SandMan interface. The only issue I have is the purple-blue gradient icons. They seem very out of place. I would like to see the ability to "skin" the icons with resource packs.

**Comment by DavidXanatos** [comment]
You can find all the used icons here: https://github.com/sandboxie-plus/Sandboxie/tree/master/SandboxiePlus/SandMan/Resources/Actions
I use icons from https://icons8.com/ if you find there better once I can use those.

If you provide me a alternative set of icons I'll implement a mechanism to load them instead of the default once.

Deal?

**Comment by Valinwolf** [comment]
Mission accepted! 😁

**Comment by Valinwolf** [comment]
Here are the icons I picked out.
https://icons8.com/icons/share-collections/LvQ5M6wFuLzN

**Comment by DavidXanatos** [comment]
thanks I'll look into adding a loading mechanism soon :)

**Comment by Valinwolf** [comment]
Awesome! I look forward to it!

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/102780553-6bf05500-4396-11eb-839b-528646db18eb.png)

**Comment by Valinwolf** [comment]
Looks great, but I would switch Terminate All Programs and Remove Sandbox icons in the context menu though.

**Comment by DavidXanatos** [comment]
I'll improve the selection a bot and will make it i think the default icon set :-)
