### ISSUE TITLE
On Vintage View when the some menus are clicked the SandMan.exe crashes

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#2380]
### Describe what you noticed and did

1. Set the view as Vintage View
2. Open the box settings
3. Click on the `General Options` > `Box Options` or `Restrictions`
4. SandMan.exe crashes.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

It should work without crashing.

### What is your Windows edition and version?

Windows 10 Pro 21H2 64-bit and Windows 11 Pro 21H2 64-bit

### In which Windows account you have this problem?

User account with UAC protection set to Always notify.

### Please mention any installed security software

Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.4.2 and 1.5.0

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

### Crash dump

[SandMan-v1.5.0 22.10.2022 18-33-21,168.dmp.zip](https://github.com/sandboxie-plus/Sandboxie/files/9844794/SandMan-v1.5.0.22.10.2022.18-33-21.168.dmp.zip)

https://user-images.githubusercontent.com/6871698/197349564-d1e9db78-1d43-4a47-bfad-a249e04c95f5.mp4

**Comment by bastik-1001** [comment]
I can reproduce that with 1.5.0 (64bit) on Windows 7 (64bit), if the tree view is used and the vintage view. Vintage view and tabbed options interface do not trigger a crash.

**Comment by okrc** [comment]
Already reproduced

The reason is that when `iViewMode ! = 1`, the advanced security tag is removed.
https://github.com/sandboxie-plus/Sandboxie/blob/a65e06b99857b8d118b4167ff08e15462d85794e/SandboxiePlus/SandMan/Windows/OptionsWindow.cpp#L275

which raises an exception in `ui.chkAddToJob->setChecked(bool)`.

https://github.com/sandboxie-plus/Sandboxie/blob/a65e06b99857b8d118b4167ff08e15462d85794e/SandboxiePlus/SandMan/Windows/OptionsWindow.cpp#L965-L974

**Comment by bastik-1001** [comment]
@okrc Are there ways to find these flaws by some sort of automatic analysis?

Unless I had toyed around with Sandboxie's display options, I never had produced the issue myself, since that isn't how I am using Sandboxie. That's why I am asking if there is something that can detect the broken logic of the code.

**Comment by okrc** [comment]
@bastik-1001 I'm sorry, I don't know if there is a better tool than GUI Testing.

**Comment by APMichael** [comment]
JFYI: For me it also crashes when adding a new entry under "Resource Access", as soon as "Apply" is clicked.
