### ISSUE TITLE
[1.7.0b] Sandboxie-Plus-x64-v1.7.0.exe crash when open

### ISSUE THREAD

**Issue by blap** [sandboxie-plus/Sandboxie#2636]
### Describe what you noticed and did

Open SandMan.exe and it crash but open.
.dmp file(s):
[Sandboxie-Plus.zip](https://github.com/sandboxie-plus/Sandboxie/files/10520131/Sandboxie-Plus.zip)

### How often did you encounter it so far?

Only Open SandMan.exe

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Open SandMan.exe without crash.

### What is your Windows edition and version?

Not relevant

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

Not relevant

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.7.0 portable

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
I have updated the installers please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0a

**Comment by blap** [comment]
> I have updated the installers please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0a

Solved.

**Comment by blap** [comment]
I got more random crashes in 1.7.0a.

[Sandboxie-Plus.zip](https://github.com/sandboxie-plus/Sandboxie/files/10523073/Sandboxie-Plus.zip)

**Comment by DavidXanatos** [comment]
I have updated the installers once again please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0b

**Comment by blap** [comment]
> I have updated the installers once again please re download and re install to solve the sandman issue, or use the live updater in the preview channel to get 1.7.0b

I got more random crashes in 1.7.0b
[Sandboxie-Plus.zip](https://github.com/sandboxie-plus/Sandboxie/files/10523155/Sandboxie-Plus.zip).

**Comment by blap** [comment]
More dmp files.
[Sandboxie-Plus.zip](https://github.com/sandboxie-plus/Sandboxie/files/10523184/Sandboxie-Plus.zip).

**Comment by DavidXanatos** [comment]
this is strange, I don't think your issue is related to the problems other users had with 1.7.0

your crash originates with pcacli.dll which ist a part of windows's compatibility assistant,
have you tried cleanly rebooting your windows?


´´´
 	KERNELBASE.dll!RaiseException()	Unknown	Symbols loaded.
 	rpcrt4.dll!RpcpRaiseException()	Unknown	Symbols loaded.
 	rpcrt4.dll!RpcRaiseException()	Unknown	Symbols loaded.
 	rpcrt4.dll!NdrpClientCall3()	Unknown	Symbols loaded.
 	rpcrt4.dll!NdrClientCall3()	Unknown	Symbols loaded.
 	pcacli.dll!PcaMonitorProcess()	Unknown	Symbols loaded.
 	windows.storage.dll!CInvokeCreateProcessVerb::CallCreateProcess(void)	Unknown	Symbols loaded.
 	windows.storage.dll!CInvokeCreateProcessVerb::_PrepareAndCallCreateProcess(void)	Unknown	Symbols loaded.
 	windows.storage.dll!CInvokeCreateProcessVerb::_TryCreateProcess(void)	Unknown	Symbols loaded.
 	windows.storage.dll!CInvokeCreateProcessVerb::Launch()	Unknown	Symbols loaded.
 	windows.storage.dll!CInvokeCreateProcessVerb::Execute(void)	Unknown	Symbols loaded.
 	windows.storage.dll!CBindAndInvokeStaticVerb::InitAndCallExecute(struct IExecuteCommand *,struct IShellItemArray *,bool)	Unknown	Symbols loaded.
 	windows.storage.dll!CBindAndInvokeStaticVerb::TryCreateProcessDdeHandler()	Unknown	Symbols loaded.
 	windows.storage.dll!CBindAndInvokeStaticVerb::Execute()	Unknown	Symbols loaded.
 	shell32.dll!CShellExecute::_ExecuteAssoc(struct IAssociationArray *)	Unknown	Symbols loaded.
 	shell32.dll!CShellExecute::_DoExecute()	Unknown	Symbols loaded.
 	shell32.dll!CShellExecute::ExecuteNormal()	Unknown	Symbols loaded.
 	shell32.dll!ShellExecuteNormal()	Unknown	Symbols loaded.
 	shell32.dll!ShellExecuteExW()	Unknown	Symbols loaded.
 	shell32.dll!ShellExecuteW()	Unknown	Symbols loaded.
>	SandMan.exe!CFileView::OnFileDblClick(const QModelIndex & __formal) Line 296	C++	Symbols loaded.

´´´

**Comment by blap** [comment]
> this is strange, I don't think your issue is related to the problems other users had with 1.7.0
> 
> your crash originates with pcacli.dll which ist a part of windows's compatibility assistant, have you tried cleanly rebooting your windows?
> 
> ´´´ KERNELBASE.dll!RaiseException�() Unknown Symbols loaded. rpcrt4.dll!RpcpRaiseException() Unknown Symbols loaded. rpcrt4.dll!RpcRaiseException�() Unknown Symbols loaded. rpcrt4.dll!NdrpClientCall3() Unknown Symbols loaded. rpcrt4.dll!NdrClientCall3() Unknown Symbols loaded. pcacli.dll!PcaMonitorProcess() Unknown Symbols loaded. windows.storage.dll!CInvokeCreateProcessVerb::CallCreateProcess(void) Unknown Symbols loaded. windows.storage.dll!CInvokeCreateProcessVerb::_PrepareAndCallCreateProcess(void) Unknown Symbols loaded. windows.storage.dll!CInvokeCreateProcessVerb::_TryCreateProcess(void) Unknown Symbols loaded. windows.storage.dll!CInvokeCreateProcessVerb::Launch() Unknown Symbols loaded. windows.storage.dll!CInvokeCreateProcessVerb::Execute(void) Unknown Symbols loaded. windows.storage.dll!CBindAndInvokeStaticVerb::InitAndCallExecute(struct IExecuteCommand *,struct IShellItemArray *,bool) Unknown Symbols loaded. windows.storage.dll!CBindAndInvokeStaticVerb::TryCreateProcessDdeHandler() Unknown Symbols loaded. windows.storage.dll!CBindAndInvokeStaticVerb::Execute() Unknown Symbols loaded. shell32.dll!CShellExecute::_ExecuteAssoc(struct IAssociationArray *) Unknown Symbols loaded. shell32.dll!CShellExecute::_DoExecute() Unknown Symbols loaded. shell32.dll!CShellExecute::ExecuteNormal() Unknown Symbols loaded. shell32.dll!ShellExecuteNormal() Unknown Symbols loaded. shell32.dll!ShellExecuteExW() Unknown Symbols loaded. shell32.dll!ShellExecuteW�() Unknown Symbols loaded.
> 
> > SandMan.exe!CFileView::OnFileDblClick(const QModelIndex & __formal) Line 296	C++	Symbols loaded.
> 
> ´´´

Tried now.
Same problem, I think.

[Sandboxie-Plus.zip](https://github.com/sandboxie-plus/Sandboxie/files/10523250/Sandboxie-Plus.zip)

**Comment by blap** [comment]
I found this service here now.
In this notebook windows compatibility assistant is disable and I can not enable it.

**Comment by DavidXanatos** [comment]
Try re installing sandboxie from the newest installer and rebooting windows

**Comment by blap** [comment]
> Try re installing sandboxie from the newest installer and rebooting windows

Version 1.7.0c solved.
For now I did not find more crashes related.
Thanks!
