### ISSUE TITLE
Sanboxie Installer fails to overwrite SbieDrv.sys when Overwrite option is chosen

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#271]
I'm using Windows10 64bit 20H2 and Sandboxie Classic 64bit.
I was trying to upgrade from 5.45.0 to 5.45.1, so I selected Overwrite/Update

Then this happened:
![upgrade not possible](https://user-images.githubusercontent.com/12411527/103041909-14a9da80-4578-11eb-8280-ff41ca8c162b.png)

The installer fails to complete the upgrade process.
You are left with a half-finished job though.

As I was expecting this, I had created checksums before my attempt and compared them afterwards:
![upgrade not possible2](https://user-images.githubusercontent.com/12411527/103041988-5044a480-4578-11eb-847c-7a7946479731.png)
The installer was able to successfully overwrite everything except the **SbieDrv.sys**

**Comment by NewKidOnTheBlock** [comment]
See also #220

**Comment by DavidXanatos** [comment]
No this is normal when upgrading from an old build on a windows 2004 or later as the old driver even from sophos times, under sertain conditions onthis systems couldn't be unloaded.
That issue is fixed and wil not happen in future, here a reboot is in order to resolve the issue
i.e. reboot, and than uverwrite the driver when it wasnt used can be uloaded still
