### ISSUE TITLE
systray controls missing

### ISSUE THREAD

**Issue by KlausiMeier** [sandboxie-plus/Sandboxie#272]
Hi,
just switched from Sandboxie 5.33.6 to Sandboxie Plus 0.52.
Feeling very well with the new UI.

I am just missing the former possibility of controlling my sandboxes directly from the systray by right mouse click, like starting of browser/programs, delet content,..
In fact what I can do by right click on a sandbox in the Manager, which is a bit unconfortable for me to open it each time.

Can you bring this back to the tray, please?
Or maybe I am just blind to see the option in the control panel?

Thanks a lot!

**Comment by DavidXanatos** [comment]
That is not great to implement, you see the old UI is creating a menu element for very sandbox and keeping it, resulting in when you have more around 700 boxes it fails due to limited windows resources.
Qt rendering everything on its own wouldn't have this limitation but would probably performance wise grind to a halt.
So its not good and for users with 100ths of boxes this tray menu is really useless.

So what we need is some sort of smart compromise or solution.
Something that allows you to achieve what you want without having to have a menu for every box in existence permanently.

You see the UI has one menu and to which box the clicked option applies is deiced based on what items were selected in the tree, so for every box you see the exact same menu with possibly on demand some items hidden/showed enabled/disabled.

**Comment by 0x391F** [comment]
Eh, could you add a option so that user could choose show this menu or not? It's really convinent because user needn't open the main interface of Sandboxie to 

- Run from Start Menu
- Delete contents
- Do a quick recovery
...

**Comment by quangkieu** [comment]
I would suggest systray only have recent used (or newly created) boxes, and another list of frequent boxes. Max of each lists is 10. More than that, user need open main windows

**Comment by NyarlathotepZERO** [comment]
> I would suggest systray only have recent used (and newly created) boxes, and another list of frequent boxes. Max of each lists is 10. More than that, user need open main windows

I like this idea. Perhaps to expand upon it, rather than have the software automatically 'detect' and offer sandboxes based on conditions, the user would be given an option to choose the boxes which are offered.
