### ISSUE TITLE
Shell New Sandbox Block Network not getting set

### ISSUE THREAD

**Issue by FtrSpec** [sandboxie-plus/Sandboxie#2729]
### Describe what you noticed and did

Sandboxie Plus 1.7.2
In windows right click on setup.exe say run Sandboxed, 
select create new sandbox
Check Advanced
Turn off Network Access
Setup.exe launches and has network access
Right click on New Sandbox and look at network settings and it's set to Allow not Block

### How often did you encounter it so far?

Everytime

### Affected program

Any Newly created Sandbox via Windows Shell

### Download link

N/A

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

Block Network Access should be set on new sandboxes when selected in Advanced Settings.

### What is your Windows edition and version?

Windows 10 Pro 21H2

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

ESET, Malwarebytes

### What version of Sandboxie are you running?

1.7.2

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by offhub** [comment]
I can confirm this. This issue occurs when `WFP` setting is not enabled.

#### The new box wizard is setting incorrect values for the selected block type. [***](https://github.com/sandboxie-plus/Sandboxie/issues/1312#issuecomment-947382979)

1.  Allow network/internet access
    > Value assigned by selection: `-`

2. Block network/internet by denying access to Network devices [WRONG value: This selection sets `WFP` instead of `NDev` value.]
    > Value assigned by selection: `AllowNetworkAccess=!<InternetAccess>,n` [This is the WFP setting.]

3. Block network/internet using Windows Filtering Platform [NOT VISIBLE when WFP is not enabled! WRONG value: This selection sets `NDev` instead of `WFP` value.]
    > Value assigned by selection: `ClosedFilePath=!<InternetAccess>,InternetAccessDevices` [This is the NDev setting.]
