### ISSUE TITLE
msedge.exe does not terminate when Edge is closed

### ISSUE THREAD

**Issue by ghost** [sandboxie-plus/Sandboxie#2731]
### Describe what you noticed and did

Create new sandbox (Hardened or Standard). Configure msedge.exe as the only one app which can run in the sandbox, access the Internet and as LeaderProcess.

Run Edge in this sandbox.
If it is running for long enough (dunno how long), close it.

![image](https://user-images.githubusercontent.com/17072890/224824428-6a3edc73-06b2-434d-9307-767bb20fd0b6.png)

Those processes will never be terminated.

If you run and close Edge once again in the same sandbox, another instance of msedge.exe process and msedge.exe subprocess will be stuck.

This issue can not be reproduced on demand.

It _may_ be related to Edge trying to check for updates. However, if you manually enter about page and close the msedge.exe, it might seem "you reproduced the issue". In fact, you didn't as msedge.exe will be terminated within 30 seconds.

"Continue running background extensions and apps when Microsoft Edge is closed" is turned off

The issue will eventually occur when you use set up new Edge sandbox and use it for a few days or so

### How often did you encounter it so far?

Randomly, but quite often

### Affected program

Edge 109.0.1518.78 x64

### Download link

Not relevant

### Where is the program located?

The program is installed only outside the sandbox.

### Expected behavior

msedge.exe is terminated when Edge GUI closes

### What is your Windows edition and version?

Windows 11 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

ESET Endpoint Security 10.0.2045.0

### What version of Sandboxie are you running?

Sandboxie-Plus v1.6.6

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

My sandbox contains existing programs or data.

**Comment by DavidXanatos** [comment]
can anyone else reproduce this?

**Comment by githubusername2024** [comment]
This issue was fixed for 23H2 long time after releasing it. It started occurring right after updating Win11 to 24H2. It happens every time I close MS Edge

[GlobalSettings]
ProcessGroup=<StartRunAccess>,Start.exe
ForceDisableSeconds=2147483647
#ClosedFilePath=%SystemDrive%\Dane
WriteFilePath=%userprofile%\Desktop
WriteFilePath=%userprofile%\Documents
WriteFilePath=%userprofile%\Downloads
WriteFilePath=%userprofile%\Pictures
WriteFilePath=%userprofile%\Videos
WriteFilePath=%userprofile%\Favorites
WriteFilePath=%userprofile%\Music
ClosedFilePath=%SystemRoot%\Sandboxie.ini
ClosedFilePath=D:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll
ClosedFilePath=G:\
ClosedFilePath=E:\
ClosedFilePath=D:\
ClosedFilePath=%localappdata%\Mozilla\Firefox\Profiles\cache2\trash
WriteFilePath=msedge.exe,%localappdata%\Microsoft\Edge\User Data\Default\Sessions
WriteFilePath=chrome.exe,%localappdata%\Google\Chrome\User Data\Default\Sessions
BlockNetworkFiles=y
ReadFilePath=%SystemRoot%\
ProcessLimit1=100
ProcessLimit2=200
AllowSpoolerPrintToFile=n
FileRootPath=D:\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
EditAdminOnly=y
ForceDisableAdminOnly=y
NotifyStartRunAccessDenied=n
NotifyInternetAccessDenied=n
CopyLimitKb=81920
DefaultBox=DefaultBox
Template=7zipShellEx
Template=NotepadPlusPlus_fix
Template=OfficeClickToRun
Template=OfficeLicensing
Template=RTSS
Template=WindowsLive
Template=WindowsRasMan
Template=Edge_Fix

[Edge]
Enabled=y
ConfigLevel=10
Template=Edge_Force
Template=Chrome_Phishing_DirectAccess
Template=LingerPrograms
Template=BlockPorts
Template=qWave
Template=SkipHook
Template=FileCopy
BorderColor=#027df7,ttl,6
ProcessGroup=<InternetAccess>,msedge.exe
ProcessGroup=<StartRunAccess>,msedge.exe,CompPkgSrv.exe
ProcessGroup=<InternetAccessDisabled>,
AutoExec=reg import %SystemRoot%\SBIE.reg
ClosedFilePath=!<InternetAccess>,InternetAccessDevices
BoxNameTitle=n
CopyLimitKb=81920
OpenFilePath=msedge.exe,E:\temp\*
UseSecurityMode=y
ClosedIpcPath=!<StartRunAccess>,*
UseFileDeleteV2=y
UseRegDeleteV2=y
LeaderProcess=msedge.exe
