### ISSUE TITLE
New price for Small certificate is a bit much

### ISSUE THREAD

**Issue by p0358** [sandboxie-plus/Sandboxie#2840]
### Describe what you noticed and did

So my certificate valid for "at least a year" has expired and disabled all features in Sandboxie *exactly* one year after I got it, and now I see that it's €20 instead of €10 like before. I feel like that's way too much now and don't really want to renew it at this price anymore, while previous €10 was just about reasonable enough for home users...

In current shape, I will probably instead be looking at some vulnerable drivers to load an unsigned recompiled driver instead...

### Affected program

-

### Download link

-

### Where is the program located?

Not relevant to my request.

### Expected behavior

Being able to renew at the same old price...

### What is your Windows edition and version?

-

### In which Windows account you have this problem?

Not relevant to my request.

### Please mention any installed security software

-

### What version of Sandboxie are you running?

-

### Is it a new installation of Sandboxie?

I have been using the same version for some time.

### Is it a regression?

yes

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by mysteriously** [comment]
I am not a fan of subscriptions plans either. Especialy that there is no discount for lifetime license users who bought this license when tzuk was the only dev.

I care only about compatibility with MS supported Windows versions, windows updates and main web browsers. Some Edge features don’t work at all.

For apps there is Hyper-V. For games… gimme a break…

On the other hand, SBIE is complicated piece of software and requires fixes to keep compatibility even if we are talking about Win updates, web browsers and AV software.

There is no real alternative.

Cracking SBIE driver is not that hard. The thing is that to load recompiled driver you can either run the OS with very insecure settings or go insane way to do not pay for MS certificate.

**Comment by Rngexile** [comment]
> I am also not a fan of subscription plans. Especially that there is no discount for lifetime license users who bought this license when tzuk was the only developer.
> 

Not fan neither and avoiding as much as i can. But i think there are legitimate reasons to pay one (more than a symbolic 1-10€ per year) in the case of sandboxie & sandboxie-plus.
I was one of the first happy client of the lifetime license from Tzuk and he probably shote him in his feet with that business plan (even with minimal goals), considering the small community of real clients he had and the constant updates he shoud have done with the new windows (win7+) and apps ... it was an other era. In the current situation, i don't even see why i should ask or deserve a discount from David. 
Licenses are fairly priced imho.

> I only care about compatibility with MS supported Windows versions, Windows updates and major web browsers. Some Edge features don't work at all.
> 
> For applications, there is Hyper-V. For games... give me a break...
> 

You consider only your "basics" needs (in term of possibilities and in term of security). I won't thank you to forget mines and others which were too part of the legacy sandboxie small community and helped it to grow and get some attention and respect in regards of its various habilities.
It's not a pure "pro" software, never was.

> On the other hand, SBIE is a complicated piece of software and requires fixes to maintain compatibility, even when we are talking just about Windows updates, web browsers and AV software.
> 
> There is no real alternative.

Precisely. And i don't think we are multi millions David's clients yet (hope for the best). That's why a symbolic 1-10€ lifetime or annual license is nonsense imho.
We get way more than just "fixes" with sandboxie-plus dev.

Long live and prosperity !

**Comment by mysteriously** [comment]
> 20$ is also what invincia asked last time for a 1 year sandboxie, not giving the customers an option for a perpetual license at all.

They did, price was 30 euros net

**Comment by DavidXanatos** [comment]
> > 20$ is also what invincia asked last time for a 1 year sandboxie, not giving the customers an option for a perpetual license at all.
> 
> They did, price was 30 euros net

No they did not, not at the end see the last way back machine entry: https://web.archive.org/web/20190905201830/https://www.sandboxie.com/HomeUse
![grafik](https://user-images.githubusercontent.com/3890945/233553949-46347474-bc00-4746-a677-7e53f4442d62.png)
1 year subscription for $20.95 FOR ONLY ONE PC!!!
a perpetual option was gone from at least 2018 

The plus certificates for personal use cover your entire private PC museum, no limits no mater how many PC's you have you can personally use the one certificate on all of them.

So its actually quite a bit better offering.

I think its time to close this issue as its not really going anywhere anyway...
