### ISSUE TITLE
Run Menu doesn't work in Sandboxie Plus

### ISSUE THREAD

**Issue by blap** [sandboxie-plus/Sandboxie#2895]
### Describe what you noticed and did

I can not run anything in the run menu and inside Standard Applications.
Simply nothing happens when clicked in any box.

![run](https://github.com/sandboxie-plus/Sandboxie/assets/913963/b021b287-9432-4b32-b8f8-4e9541c35866). 

### How often did you encounter it so far?

Always when I click in something in run menu

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Open system thing when click in something in run menu and inside Standard Applications.

### What is your Windows edition and version?

Windows 10 Home 22H2 64-bit

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

None

### What version of Sandboxie are you running?

Sandboxie Plus 1.9.3 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by isaak654** [comment]
I'm unable to reproduce it, same OS version and Sandboxie version.

**Comment by blap** [comment]
How can I get a proper log for this?

**Comment by isaak654** [comment]
> How can I get a proper log for this?

[CONTRIBUTING.md#how-to-help-with-sandboxie-issues](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md#how-to-help-with-sandboxie-issues)

**Comment by isaak654** [comment]
> How can I get a proper log for this?

[CONTRIBUTING.md#how-to-help-with-sandboxie-issues](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md#how-to-help-with-sandboxie-issues)

P.S. I expect some support from you in the SandboxToys2 repo.

**Comment by blap** [comment]
> > How can I get a proper log for this?
> 
> [CONTRIBUTING.md#how-to-help-with-sandboxie-issues](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md#how-to-help-with-sandboxie-issues)
> 

I think the problem would be sandboxie is portable here.
I don't got any internal traces.
Procmom didn't give me any lucky too.

> P.S. I expect some support from you in the SandboxToys2 repo.

What kind of support?

**Comment by isaak654** [comment]
> > P.S. I expect some support from you in the SandboxToys2 repo.
> 
> What kind of support?

A reply or two there.

**Comment by isaak654** [comment]
The only things I can think of:
- uninstallation + reinstallation + reboot
- since you can reproduce this in all your sandboxes, you may want to check any Sandboxie.ini setting in [GlobalSettings]
- possible third-party conflict and/or some advanced Microsoft Defender setting that in most systems is not enabled by default

**Comment by isaak654** [comment]
The only things I can think of:
- uninstallation + reinstallation + reboot
 (for Sandboxie Plus portable, there is the Maintenance entry in the Sandbox menu)
- since you can reproduce this in all your sandboxes, you may want to check any Sandboxie.ini setting in [GlobalSettings]
- possible third-party conflict and/or some advanced Microsoft Defender setting that in most systems is not enabled by default

**Comment by isaak654** [comment]
The only things I can think of:
- uninstallation + reinstallation + reboot
 (even for Sandboxie Plus portable, there are the Maintenance entries in the Sandbox menu)
- since you can reproduce this in all your sandboxes, you may want to check any Sandboxie.ini setting in [GlobalSettings]
- possible third-party conflict and/or some advanced Microsoft Defender setting that in most systems is not enabled by default

**Comment by blap** [comment]
> The only things I can think of:
> 
> * uninstallation + reinstallation + reboot
>   (even for Sandboxie Plus portable, there are the Maintenance entries in the Sandbox menu)

Tried this now with a clean install. Same error...

> * since you can reproduce this in all your sandboxes, you may want to check any Sandboxie.ini setting in [GlobalSettings]

Disable all advanced configs in [GlobalSettings], close Sandboxie, start it again. Same error...

> * possible third-party conflict and/or some advanced Microsoft Defender setting that in most systems is not enabled by default

I removed Microsoft Defender from my system and I don't have any antivirus here. But I think now the problem would probably be here in a setting that I don't know...

**Comment by blap** [comment]
Solved.
I need to run sandboxie with an administrator.
Sorry.

**Comment by bastik-1001** [comment]
Does it hold true that for versions of Windows after Windows 7, admin rights are required for the run menu?

Since I run an installed Sandboxie 1.9.3 (64bit) on Windows 7 (64bit) as a regular user and can still use entries in the run menu. Those things just open the tools in the sandbox as the limited user. When I launch the "command prompt (admin)" I get prompted that Sandboxie will ask for elevation, for the process it is starting under its supervision, stating that approval or denial can be expressed through the appearing UAC dialog. The UAC dialog appears and ask for the admin password. Dismissing the dialog, results in the process not being launched and entering the password starts it under the control of Sandboxie.

This was the case whenever I started something via the run menu. That did not change for me.
