### ISSUE TITLE
Remember size of Sandboxie-Plus main window

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#2917]
### Is your feature request related to a problem or use case?

(Low priority)

Problem: I need to resize the window everytime I open the main window in order to see the fields I wish to see.

### Describe the solution you'd like

When user closes main window, remember not just location, but also size of the main window and its restored/maximised state.

Repro:
* Show Sandboxie-Plus Main Window
* Resize & move
* Close window
* TaskTray > Sandboxie Icon > Double Click

Actual: Window shows at previous position with default size
Expected: Window shows at previous position with previous size

Special cases:
* Screen resolution, scaling, orientation, layout changed
* Display(s) added/removed

Related issues:

2. Controls layout fails when main window was maximised
* Maximise main window
* Close main window
* Double click on Tray Icon
Actual: Bug. Window shows maximised, but controls inside window are sized & positioned as if window was default size
Expected: Layout is per actual size

3. Minimized window should show, not close when tray icon is double-clicked
* Minimize main window
* Double click tray icon
Actual: Window closes
Expected: Window shows restored/maxed

4. Window does not recall restored position when it was maximised and closed
* Maximise main window
* Close main window
* Double-click tray icon
* Window shows maximised
* Restore main window
Actual: Window shows restored at top left corner
Expected: Window shows at previous restored location & size subject to display changes

**Comment by bastik-1001** [comment]
It appears as if you have encountered some sort of bug.

Previously, I had not noticed anything strange about the window and its size, but as I saw that issue, I tried to reproduce it.


    Show Sandboxie-Plus Main Window
    Resize & move
    Close window
    TaskTray > Sandboxie Icon > Double Click

Produces, the same result as using the tray icon and clicking "Show/Hide" or when I end Sandman and start it again. Sandman shows up at the location I moved it to, with the window size I resized it to.

2.  This is not something I see, either. This is my way of using Sandman, having it maximized, closing its window and later restoring it, via the tray icon. (In other instances, I minimize to the taskbar and return to it being maximized again).
3. I can reproduce this one, but for me that is the expected result, as it just toggles show/hide. Sandman is shown, while being minimized, when I click Show/Hide it gets hidden and when I click Show/Hide again, it gets shown again, albeit in the taskbar. When double-clicking the tray icon, while being minimized to the taskbar, Sandman gets hidden, double-clicking it again, shows the window maximized, brought to the front. There is a mismatch between the double click and using Show/Hide, since that only restores it to the minimized state.
4. Works just fine for me, I close it maximized, it opens back up as maximized and when I restore its window it returns to the size and position I changed it to. This is even true when ending Sandman.

**Comment by typpos** [comment]
Items (1), (2), (4):
Well, today I can't reproduce it anymore. The window recalls its size correctly, etc.

I guess it might relate to an old sandboxie-plus.ini that was left behind when I fully uninstalled (not upgraded) the old version before installing 1.9.3. Just tried:
* Close 1.9.3
* Copy sandboxie-plus.ini from version 0.9.6 to 1.9.3
* Start 1.9.3
* Resize
* Tray icon double-click to close
* Tray icon double-click to open
* Size is reset

Item (3): 
Yes, it's a matter of preference. The alternative used by various other apps is to divert "minimize" to "close" when there is a clickable tray icon.

I'm closing this. Thanks, bastik-1001.

**Comment by bastik-1001** [comment]
3) I am not sure, if it is part of Qt or if Sandman itself contains code to handle this, but when it is the latter, it can be unified or included as an option to suit different preferences. To me, it does not matter. :)
