### ISSUE TITLE
RecoverFolder shows GUID instead of folder name

### ISSUE THREAD

**Issue by typpos** [sandboxie-plus/Sandboxie#2918]
### Describe what you noticed and did

(Low priority)

When creating a new sandbox, the RecoverFolder list includes a GUID. I assume this is meant to be %Downloads%.
![image](https://github.com/sandboxie-plus/Sandboxie/assets/28550406/4b87bf06-3169-45c5-a6da-d9bea2f3fbf2)

I am using a custom folder location for Downloads:
Registry entries for Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders:
![image](https://github.com/sandboxie-plus/Sandboxie/assets/28550406/aaffaa50-2e73-40a3-b179-86e6726a82db)

### How often did you encounter it so far?

Always

### Affected program

n/a

### Download link

n/a

### Where is the program located?

Not relevant to my request.

### Expected behavior

%Downloads% or "D:\Downloads" is shown.

### What is your Windows edition and version?

Windows 10 Pro 22H2

### In which Windows account you have this problem?

A local or Microsoft account without special changes.

### Please mention any installed security software

n/a

### What version of Sandboxie are you running?

1.9.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a security hardened sandbox (orange sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### Sandboxie.ini configuration

```shell
[Box5]
Enabled=y
BlockNetworkFiles=y
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Desktop%
```

**Comment by bastik-1001** [comment]
I have seen those GUIDs before and assumed those were used for every installation and that they being used for technical reasons.

**Comment by DavidXanatos** [comment]
usually only the downloads folder is reffered to by its  guid in teh registry 

![grafik](https://github.com/sandboxie-plus/Sandboxie/assets/3890945/e4f4ef9e-ed27-49b1-9e7b-61d3dbfe1c4b)

So resolving folder names to guids would not be easy,
technically internally all shell foders have guids but the resolution mechanism is one way guid -> folder,
we could always resolve all and then see what matches but thats not pretty.


I assume you are actually requesting the opposite, as you wrote Expected behavior: %Downloads% or "D:\Downloads" is shown.

I don't think %Downloads% is actually valid at all, so the only thing we could do is to replace the GUID with the resolved path or better read the value from registry and show %USERPROFILE%\Downloads

**Comment by typpos** [comment]
So, yes, display folder names ordinary users would know.
* Absolute paths won't move along when user changes their folder location in Shell.
* I'd store in config and display in UI: absolute paths for fixed stuff, friendly names ("Downloads", "Favorites", etc) for Shell-lookups.
* Code can distinguish the two on use and trigger lookup as needed.
* Instead of reg-lookup, SHGetKnownFolderPath or similar
* Not sure if "%USERPROFILE%\Downloads" is right. Documented as "default path". File Explorer maps it correctly without a junction in my %USERPROFILE%, but cmd.com does not. Magic!
