### ISSUE TITLE
before you endlessly nag about payments, you should grandfather those who have already paid for it in the distant past

### ISSUE THREAD

**Issue by hundreAd100** [sandboxie-plus/Sandboxie#2926]
### Describe what you noticed and did

before you endlessly nag about payments, you should grandfather those who have already paid for it in the distant past

am i NOT paying for this twice

### Affected program

n/a

### Download link

n/a

### Where is the program located?

Not relevant to my request.

### Expected behavior

enough with the nags!
or give certificates to people who have already purchased this when this was commercial

### What is your Windows edition and version?

windows 10 pro 21h2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

n/a

### What version of Sandboxie are you running?

5.60.3

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by bastik-1001** [comment]
There are a few options:
- Use the version you have purchased from whomever sold it to you
- Use the version that got released before that screen has been added **
- Build your own Sandboxie
- Maybe there are other ways that I miss

** Those versions include being able to have multiple sandboxes and use the "force processes" feature, that were not available to everyone, before the sources got released.

I understand that there might be some frustration on having to pay for something you already payed for, but in this instance it is different, IMO, since the source code was released and this is a fork of said code. If there would have been some purchase or merger, where person/company A sold it to person/company B it would be reasonable to have the list of customers to be handed over, so they don't have to pay again. Legally there might not even be a requirement to do that, but I am not a lawyer, nor does such a case apply, here. (There is a company that has rights to a franchise and if they desire they are probably able to make the dark lord wear pink.)

Everything that requires a supporter certificate has been added to the code after that went open source. Everything else can be used without it, for personal use. There is the support reminder, which might be annoying to some. It should not be shown that often, but I can understand that it being shown is not adding something positive to the usage experience. (I tried some other tool and it showed me a reminder to buy pro every time, I started it, the first day I tried it and the next day, so that was nagging me.)

Whenever or not there should be such a screen is debatable. [I worried about it as it got added](https://github.com/sandboxie-plus/Sandboxie/discussions/2107). The level of annoyance is probably subjective.

**Comment by DavidXanatos** [comment]
I think all was already said, not being a legal successor or invincia/sophos I'm not bound by any obligations they may be under, its as simple as that. 
Also I have no way to validate any claim that someone purchased Sandboxie in the past.

btw this is the code which determins how often a reminder is being shown
```
	// Note: the old sandboxie showed a message after 30 days every 12 hours for 5 seconds
		
	int Interval;
        if (Days > 730) Interval = 5 * 24;
        else if (Days > 365) Interval = 10 * 24;
        else if (Days > 180) Interval = 20 * 24;
        else Interval = 30 * 24;

```
the value is in hours so it starts at once per month and goes to once every 5 days after 2 years of usage,
that is IMHO a good balance between reminding people to support the project and not being obtrusive.

**Comment by isaak654** [comment]
> Also I have no way to validate any claim that someone purchased Sandboxie in the past.

What about contacting Sophos for it?
I think it would be good to have a statement from them, either a positive or negative response, to present publicly.

**Comment by DavidXanatos** [comment]
> > Also I have no way to validate any claim that someone purchased Sandboxie in the past.
> 
> What about contacting Sophos for it? I think it would be good to have a statement from them, either a positive or negative response, to present publicly.

Eider way it would not be relevant, I'm not bound by any obligations they may be under.

People paid for sandboxie in the distant past and that sandboxie can still be downloaded and used for example here: https://github.com/sandboxie-plus/sandboxie-old/blob/main/5.x/Sandboxie-5-33-6.exe
They paid invincia/sophos for their work and their got what they payed for they can use it in all perpetuity, on the old platforms it still works on. 

If they want to benefit from my work I need to be payed as well. Why should I provide my work for free to people whom have payed someone else, that wouldn't be fair, as simple as that.

Now if invincia/sophos would have given me some exclusive license to the source code than things would be different, than having received something of monetary value it would be justifiable that this comes with some obligations. But that's not what happened.

**Comment by isaak654** [comment]
> am i NOT paying for this twice

@hundreAd100 By the way, you don't have to: [CONTRIBUTING.md#non-monetary-contributions](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md#non-monetary-contributions)
