### ISSUE TITLE
Request: Brave Browser exclusion templates

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#301]
Brave browser is one of the most popular browsers out there, far more than srware Iron which is supported by sandboxie. Please add web browser exclusion templates for brave browser, to force it to run and allow direct access to profile/cookies (etc).

Thank youuu!

**Comment by NewKidOnTheBlock** [comment]
You could use Brave Portable:
https://github.com/portapps/brave-portable

I'm running that in Sandboxie and it works fine.

**Comment by bjm234** [comment]
Sandboxie-Plus does not include Edge template.  Edge is the second most popular browser after Chrome. 
Hopefully, Sandboxie-Plus in time will update Templates for modern browsers and maybe remove out-dated Templates.  
$.02

**Comment by DavidXanatos** [comment]
may be @isaak654 could create the appropriate template entries

**Comment by isaak654** [comment]
@DavidXanatos It's done! I've added Brave template, Edge template, improved Firefox support, restored Opera support in a proper template, replaced Maxthon 2 with Maxthon 6, removed outdated firefox addons, restored phishing database access in all browsers, introduced data sync in more browsers.

Could I upload it here for testing purposes or it's better to write a commit first and include the committed changes here?

**Comment by DavidXanatos** [comment]
I think uploading for testing is fine as its always good to test things as thoroughly as possible before even a pre release

**Comment by isaak654** [comment]
> 
> 
> I think uploading for testing is fine as its always good to test things as thoroughly as possible before even a pre release

https://gist.github.com/isaak654/aec7207d28683a5cde58687da8f4804b

Any report would be appreciated.

**Comment by bjm234** [comment]
@isaak654 
Might you know how to allow Microsoft Defender SmartScreen to work in my Edge sandbox. 
![image](https://user-images.githubusercontent.com/25015553/103481697-b1574e00-4daa-11eb-9206-94caa70618b7.png)
https://www.wilderssecurity.com/threads/sandboxie-plus-sbie-fork.427755/page-33#post-2967102
Thank You!

**Comment by isaak654** [comment]
@DavidXanatos Microsoft Defender Smartscreen doesn't work in sandboxed Edge with my templates enabled, but it appears to work in unsandboxed Edge if you visit the Phishing Page available on this test: https://demo.smartscreen.msft.net/

I tried this additional rule, but it's not enough:
`OpenFilePath=<ChromePrograms>,%Local AppData%\Microsoft\Edge\User Data\SmartScreen\*`

According to [this](https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic408c408c.html) previous developer, a Windows SmartScreen template was introduced with Sandboxie beta 5.21.7, but it was removed in 5.22 because now Sanboxie handles this at the code level.

Please let me know if you're willing to take a look at it.

**Comment by rugabunda** [comment]
Excellent work! Thank you isaak! Great job!
