### ISSUE TITLE
Sandboxie-Plus: Suggestion for improvements

### ISSUE THREAD

**Issue by Francesco-Cocchioni** [sandboxie-plus/Sandboxie#303]
Hi, 

in versione 0.5.3a: "by default when started in portable mode the sandbox folder will be located to the parent directory of the sandboxie instance". The sandbox root file system is automatically set equal to  ..\SandBoxes\. I think it's better if also the %SANDBOX% parameter is automatically added (..\SandBoxes\%SANDBOX%\), so that multiple sandboxes can exists simultaneously, each one independent from the others, when sanboxie-plus is used portable mode .

Another cool feature would be if sandboxie-plus could use a unique "windows user" inside the sandbox. For example, if i launch a program inside the sandbox on a machine with the windows user named for example "USER1", inside the same sanbox under \drive\C\Users\ a folder named USER1 is created with the application settings saved. If i move this instance of sanboxie-plus portable to another machine, with the windows user named "USER2", and i launch the same application, a new folder named USER2 is created under \drive\C\Users\. So the application settings must be recreated or copied from USER1. It would be nice if sandboxie-plus could always use internally the same "windows username" (manually defined in the ini file) so that inside \drive\C\Users\ only one user folder is created and used indipentently of the real windows username.

One last cool feature, and least important, is the possibility for each sandbox to define one or more application (installed inside or outside the sanbox) to be launched automatically when sandman.exe is launched

Sorry for the long request list and thanks for taking them into consideration.

**Comment by DavidXanatos** [comment]
The portable issue is fixed now %SANDBOX% is added

About the user thing, if you have the default behavior unchanged to separate user folder the user specific files are located in [box]\user\current this way no mater with which user you start the program the actual user location gets redirected to this locations.

About auto launch, may be but rather no, you can instead of auto starting sandman just point to a batch file that would start it and a few sandboxed aplpications.
