### ISSUE TITLE
watermark function

### ISSUE THREAD

**Issue by muxq** [sandboxie-plus/Sandboxie#3096]
### Is your feature request related to a problem or use case?

Whether the application running in the sandbox can add a watermark to the window？

### Describe the solution you'd like

watermark function

**Comment by bastik-1001** [comment]
It is unclear to how this might look like. When it is for indicating that some window is in a Sandbox, there are already possible clues, like the window having a border (always or when the mouse it at the title bar), having `[#]` being added to the title, or having the name of the box displayed in the title.

That said, other visual clues, like a watermark, might be better suited for certain people. Like seeing the boxname as overlay/watermark in the right or left corner of a window, to tell windows (processes) from different boxes apart.

**Comment by muxq** [comment]
As shown below, the form knows which box it belongs to

![image](https://github.com/sandboxie-plus/Sandboxie/assets/10087906/ce8363da-1b74-4d72-a2b6-45bdaee5dcc6)

**Comment by muxq** [comment]
As shown below, the form knows which sandbox it belongs to
![image](https://github.com/sandboxie-plus/Sandboxie/assets/10087906/b98c686e-6c66-4f27-946b-8f6e28920531)

**Comment by bastik-1001** [comment]
This appears to be something that can be provided as an addon for Sandboxie Plus. Someone could create a DLL that draws an overlay over windows in a sandbox, in one way or another.

I for once, would not find it appealing to have the name written across the window multiple times, but there are surely use-cases for it. Something that is closer to the border being drawn around the window frame, like the name being overlaid in one of the corners, is something I can see as functional for getting which sandbox I am handling without it being too intrusive.

Additionally, I want to point out that some software gets rid of the title bar and that Windows defaults to showing icons instead of taskbar elements with the full name.
