### ISSUE TITLE
Remove Sandbox only deletes the contents of the sandbox when an application is running in the sandbox

### ISSUE THREAD

**Issue by offhub** [sandboxie-plus/Sandboxie#3118]
### Describe what you noticed and did

1. Run a program in the sandbox.
2. Remove Sandbox
    - The sandbox is not removed after the sandbox contents are deleted.

### How often did you encounter it so far?

Every time

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

Once the contents of the sandbox have been deleted, the sandbox must be removed.

### What is your Windows edition and version?

Windows 10 Pro 22H2 64-bit (19045.3208)

### In which Windows account you have this problem?

A Microsoft account (Administrator)., An account with UAC protection set to Always notify.

### Please mention any installed security software

Microsoft Windows Defender

### What version of Sandboxie are you running?

Sandboxie-Plus 1.10.0e 64-bit

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I remember which one it is).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

Not relevant to my request.

**Comment by wilders-soccerfan** [comment]
Could this be related to the fix offered in #3104 ?

**Comment by bastik-1001** [comment]
While the feature does not seem to be in the user interface, I can kind of reproduce this.

When I create a new box with 1.10.0e, launch a program, select to remove the box, while the process is running, Sandman tells me that it will remove the content and the box. Approving the dialog, will terminate the process, but neither the content is deleted nor the box being removed. Trying to remove the box again, shows the same messages, deletes the content and removes the box.

Since I did not try before, in that way, I can't tell if that is a new behavior.
