### ISSUE TITLE
Pausing Process or Container or all Processes and Container simultaneously

### ISSUE THREAD

**Issue by PARAViRTUALiZATiON** [sandboxie-plus/Sandboxie#3126]
**There is a Way in Process-Monitor to pause Processes from taking System-Resources:
This could be useful in many different Scenarios ...**

_Like if an Application runs out of Control, could it be possible to get back Control of it instead of terminate all other Processes and downgrade the actual Workflow_

![ ](https://github.com/sandboxie-plus/Sandboxie/assets/140122360/35444afb-c9c9-4aeb-a71e-2535b961ffa8)

Therefore **:**

**•** It would be great if this Function could be reachable in a direct Access over the SandBoxie+ GUI

**•** Also would it be great, if there were an Option to automatically freeze an Application when it exceeds a certain Limit of user-defined System-Resources (RAM, CPU or GPU) usage

**[** OR **]**

**•** A small Task-Managing-Tool for SandBoxie+

**Comment by DavidXanatos** [comment]
We actually had the a process pause option at a point in time in sandman.exe
but the thing is under windows a paused process is defined by all its threads being paused, 
so to determine if a process is really paused we needed to list all threads for all processes runnign in the sandbox and that significantly increased sandman's CPU usage, so the feature was removes.

But I guess I could re enable it perhaps with a switch so that its off by default but who wants can enable it.

**Comment by bastik-1001** [comment]
The easiest way to add something to make it easier to a user, is by pointing to the tool via a shortcut in Sandman's right-click menu for a process. This may not satisfy the feature request, but can be done quickly and does not require resources.

The next step can be to suspend/resume a process via the right-click menu in Sandman, when right-clicking on a process by invoking that tool for the selected process. You would need an indicator in the UI if a process is suspended, what could be determined by the tool. This may require some resources.

Building that into Sandman, surely can be optional and the user be told that this will have an impact on the amount of CPU resources that will be consumed. The same goes for monitoring the resources, which isn't a new idea either, but apparently also not trivial, when it comes to acting on measured values.

Since upcoming releases have an addon manager it might be possible to provide a (open source) tool for these needs.

**Comment by DavidXanatos** [comment]
the next build will add this functionality on a per process basis, do we need that also working on a per sandbox basis?
