### ISSUE TITLE
The QtCreator installer nested running in Sandboxie

### ISSUE THREAD

**Issue by rcdevice** [sandboxie-plus/Sandboxie#3153]
### Describe what you noticed and did

I want to install QtCreator in sandbox, but get the nested processes running in Sandboxie !

### How often did you encounter it so far?

every time

### Affected program

qt-creator-opensource-windows-x86_64-11.0.0.exe

### Download link

https://download.qt.io/official_releases/qtcreator/11.0/11.0.0/qt-creator-opensource-windows-x86_64-11.0.0.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

I want to install QtCreator normally, like outside the sandbox.

### What is your Windows edition and version?

Windows 10 LTSC 21H2 64bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

360

### What version of Sandboxie are you running?

Sandboxie-Plus-x64-v1.9.8.

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by rcdevice** [comment]
![Snap1](https://github.com/sandboxie-plus/Sandboxie/assets/30013680/017b2d73-895b-4a7c-a99f-820c4ba9459f)

**Comment by okrc** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/2493

**Comment by rcdevice** [comment]
Oh, my God! The Great DavidXanatos  reply  my post, It's exciting.

**Comment by DavidXanatos** [comment]
It was a pretty funny bug actually, the Qt installer uses GetConsoleProcessList to determine if its running in a cmd console or was open from explorer.
When opened standalone GetConsoleProcessList returns 1 when runnign fromm an existing console it returns at least 2 (cmd.exe and theinstaller and may be whatever else uses this console)
the way sbie allocated the console window using a helper service had a short moment where the service and the applications were attached at the same time and GetConsoleProcessList returned 2 and qt's installer tryed to restart itself out of teh console but to no avail.
The fix was to add a short wait when the connect is done and check GetConsoleProcessList untill it returns 1 before returning control to the installer.
and at voila, it works :D
