### ISSUE TITLE
Add flags to some Sandboxie-Plus > Settings > Advanced Options

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#337]
You seem to be creating a number of flags, even on the newer versions of Sandboxie (even though you usually urge against them, but they might be having their uses). I was wondering if you'd like to migrate from the manual `Edit Sandboxie.ini` format to a more UI-centric configuration dialog.

Especially for all those `y/n` flags, an "Advanced Options" tab with a checkmark and some documentation (full-text, tooltip, read-the-docs URL, link-to-release-adding-it etc etc)

Especially if Qt has some magic "documentation markup format (directly from code? markdown?) to UI elements" automation, you could be writing those flags just once.

**Comment by DavidXanatos** [comment]
you mean like this: 
![grafik](https://user-images.githubusercontent.com/3890945/103938888-3f289580-512b-11eb-8b97-250e523bb292.png)

well since I'm advising usually against using those I don't want to make it to easy to set them ;)

For flags that are intended to be used its not so easy to automatize as you also need to find a place to put them and possibly make one contingent on others, etc.

**Comment by stdedos** [comment]
Yeah, exactly! Although, I thought those flags were global; not per-sandbox (which I guess is more awesome!)

Of course, I was imagining a more chrome-flags-like interface (for more documentation, because I thought you might need to explain what is behind this flag, good usecases, bad usecases etc), but I was merely trying to add a placeholder feature.

**Comment by DavidXanatos** [comment]
Especially dangerous flags should be per sandbox as if you want to enable something risky for compatibilities sake you probably only want to do that for a single sandbox.

That said if you put those values into the global section they would apply globally.
