### ISSUE TITLE
What to do with /nosbiectrl traces?

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#3391]
See the following references:
- https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/viewtopic19871987.html?f=17&t=25537
- #3335

In order to maintain consistency with the source code, I think a decision has to be made between the following choices:

1. - [x] Remove or comment out `/nosbiectrl` leftovers:  [(1)](https://github.com/sandboxie-plus/Sandboxie/blob/9cb2462b043cbc0b73e7e6805a58e3cfce511b80/Sandboxie/apps/start/start.cpp#L95) [(2)](https://github.com/sandboxie-plus/Sandboxie/blob/9cb2462b043cbc0b73e7e6805a58e3cfce511b80/Sandboxie/apps/start/start.cpp#L581-L589) [(3)](https://github.com/sandboxie-plus/sandboxie-docs/blob/fbf482eead4b374c0d03377dbce78f817896c102/Content/StartCommandLine.md?plain=1#L41-L44) [(4)](https://github.com/sandboxie-plus/sandboxie-docs/blob/fbf482eead4b374c0d03377dbce78f817896c102/Content/StartCommandLine.md?plain=1#L85)

2. - [ ] Restore `/nosbiectrl` in a working state and provide a `/nosandman` command with the same logic

3. - [ ] Provide a common command compatible for both Sandboxie UIs

**Comment by DavidXanatos** [comment]
sandboxie control (or sandman) is started using the sbiesvc by the sandboxed rpcss this is done imho to ensure when a program is started forced it will end up invoking sbiectrl as well.
If I would have to guess I would say that the /nosbiectrl option was broken since the introduction of forced processes.

Like so many things in sbie it was implemented in a very roundabout fashion...

Since the box encryption feature was added we have a nice callout function in the service SVC_MOUNTED_HIVE which gets invoked by the driver whenever a reg hive for a box gets mounted, it is analogues to the SVC_UNMOUNT_HIVE which was part of the original sbie mechanics.

It would be generally more elegant to use the new function to make the service start the session agent (sbiectrl, sandman,...) instead of going round about through sandboxed rpcss.

This does not solve the issue of /nosbiectrl though the process creation procedure looks the following way:
start.exe creates a suspended process,
then it invokes Process_Api_Start which calls Process_NotifyProcess_Create
Process_NotifyProcess_Create calls Process_Low_Inject which invokes in the service a routine to inject sbiedll.dll into the process, it also when needed moutns an encrypted box image
then the process gets resumed this triggers in the driver an image load notification callback Process_NotifyImage
this is responsible for setting up most of the sandboxing, including loading the registry hive if one is not already loaded for the used sandbox.
hence now HiveMounted in the service gets invoked.

So as you see its till quite a complex process to come from start.exe knowing what we want to the service doing its thing.

Doing it correctly we would need to pass a flag to Process_Api_Start which gets saved on the box object for the process and can be communicated by Process_NotifyImage to the service, would be a nice mechanism.

Doing it cheaply we could maintain a map in the sbiesvc in which we would mark boxes by name to suppress session agent start once, not pretty but would do the job.

The general behavior we would be looking towards would be that if a process is started in a yet not active box using start.exe with /nosbiectrl it would ignore the sandboxie.ini preset to start sandboxie control and that choice would persist for the rest of that box activity starting more programs in it no mater how would not start the session agent, starting a process in an other not yet active box without /nosbiectrl or through forced process however would.


So its not a very definitive mechanism to determine if sandboxie control (or sandman) gets started or not, for that we have 
SbieCtrl_EnableAutoStart=n
requiring the user to start the session agent manually if its presence is desired.

A simple and predictable mechanism, hence i would opt for option 1 "Remove or comment out /nosbiectrl leftovers"
