### ISSUE TITLE
Steam launches in infinite loop in Standard (yellow) box without Admin privileges

### ISSUE THREAD

**Issue by Mitch037** [sandboxie-plus/Sandboxie#3484]
### Describe what you noticed and did

1. Create a brand new Standard box and set its Preset to "_Drop_" or "_Emulate Admin Rights_"
2. Download and install the latest version of [Steam](https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe)
3. Launch Steam
---
1. Steam gets launched, closed, launched again ad infinitum
2. The only way to get around it is to launch Steam with Admin privileges - "**Ask for UAC Elevation**" Sandbox preset enabled
3. Steam works fine in Application Compartment (green) box, to be precise all a box requires is a following line in its INI config:
`NoSecurityIsolation=y`
4. Alternatively it is possible to launch Steam properly in Standard box via Run Menu using `-cef-disable-sandbox` parameter

### How often did you encounter it so far?

Always

### Affected program

Steam

### Download link

https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe

### Where is the program located?

The program is installed only inside a sandbox (NOT in the real system anyway).

### Expected behavior

It would be expected to be able to launch Steam properly.

### What is your Windows edition and version?

Windows 7 x64

### In which Windows account you have this problem?

An account with UAC protection completely turned off.

### Please mention any installed security software

Microsoft Security Essentials

### What version of Sandboxie are you running?

Sandboxie Plus 1.12.3 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by e-t-l** [comment]
I cannot reproduce this problem. I have Steam installed in a standard yellow sandbox and it launches without issue. I'll share my config below, and you can see there's nothing I had to do regarding admin rights. I do not run Steam as administrator. 

> ### What is your Windows edition and version?
> Windows 7 x64
> 
> ### In which Windows account you have this problem?
>An account with UAC protection completely turned off. 

I suspect this is your problem. You are running a pretty outdated version of Windows that Steam does not support. You also have UAC completely disabled, which, 1) Why would you even do that? Why are you using Sandboxie? Any "security" it might offer you is *completely negated* by disabling UAC. 2) Disabling UAC may be interfering with some process that expects it, maybe that's causing some of your admin-related Steam problems.

Anyway, to reiterate, this issue is not reproducible running Sandboxie 1.12.6 on Windows 11.

**Comment by e-t-l** [comment]
Then it probably has something to do with using a 15-year-old operating system. A lot of the under-the-hood OS stuff of Windows 7 is significantly different from Win 8, which is significantly different from Win 10-11.  I imagine that some of the developments in Sandboxie that make Steam work in a standard box for modern OSes involve some components that simply aren't present in Win 7.

**Comment by DavidXanatos** [comment]
I would normally look into a win 7 issue but given that steam announced their software being discontinued on windows 7 entirely there is no point.
I assume steam wont allow you to use an outdated steam client indefinitely hence steam on windows 7 is very soon very dead, no mater what sandboxie does.
