### ISSUE TITLE
On Windows Server 2016, opening a call to the ShellExecute function in a sandbox will fail to open a website address

### ISSUE THREAD

**Issue by pangshangji** [sandboxie-plus/Sandboxie#3543]
### Describe what you noticed and did

1. Running cmd in sandbox
2. cmd.exe /c start “” “https://www.google.com”   or  cmd.exe /c start “” “https://www.baidu.com”   Unable to call default browser to open webpage

### How often did you encounter it so far?

100% probability of occurrence

### Affected program

Not relevant

### Download link

Not relevant

### Where is the program located?

Not relevant to my request.

### Expected behavior

on windows server 2016,  Use the following command to open the default browser
cmd.exe /c start “” “https://www.google.com”      

### What is your Windows edition and version?

Windows Server 2016  1607 64-bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Microsoft Defender Antivirus

### What version of Sandboxie are you running?

Sandboxie Plus 1.12.6 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

**Comment by DavidXanatos** [comment]
For me this works fine and opens firefox,
I think your issue is that server 2016 is windows 8 based which came with an Modern App version of MS Edge which is not supported by sandboxie hence your issue.
This will not be fixed anytime soon, see the various UWP incompatibilities already tracked: https://github.com/sandboxie-plus/Sandboxie/labels/uwp
especially #19 hence I'll close this issue.
The simplest fix for you will be to install some 3rd parts non UWP browser.
