### ISSUE TITLE
[Feature] "Delete files/folders of currently-sandboxed program" function

### ISSUE THREAD

**Issue by Coldblackice** [sandboxie-plus/Sandboxie#3576]
### Is your feature request related to a problem or use case?

AFAIK, currently the sandbox cleaning function removes _all_ files/folders from the sandbox. However, I have files/folders I need to remain inside the sandbox. It would be great if there was a function/ability for the sandbox to remove files added only by the currently-running sandboxed program _only_.

### Describe the solution you'd like

A function to clean/remove files/folders added by the currently-running sandboxed process only.

**Comment by hg421** [comment]
Just for reference, have you tried out the snapshots feature already? If you create a snapshot and mark it as "default" then cleaning the box will revert to that snapshot instead of deleting everything. (It doesn't do exactly what you're asking as it's not program specific but could be useful in such situations)

**Comment by DavidXanatos** [comment]
I think the snapshot mechanism is exactly whats needed here, adding some sort of keep or clear list would add unnecessary complexity to the clean up routine.
