### ISSUE TITLE
Add "On Terminate" trigger

### ISSUE THREAD

**Issue by e-t-l** [sandboxie-plus/Sandboxie#3584]
### Is your feature request related to a problem or use case?

Just as the trigger "On Box Start" very helpfully runs commands when the first program starts in a box, an "On Terminate" trigger would run commands when programs in a box **terminate**.

### Describe the solution you'd like

It would suffice to add a general "On Box Terminate" trigger that runs when all programs have terminated, but if possible a more granular "On _Program_ Terminate" that runs on the termination of specific programs would be great!

Sandboxie has a Stop Behavior feature, so there's already infrastructure for performing actions based on program termination events. This proposal would simply provide an interface for users to add their own actions.

### Describe alternatives you've considered

AutoHotKey is the only other solution I can think of.

**Comment by bastik-1001** [comment]
I think that a trigger that runs something once the last process in a box has terminated, is very useful.

On the aspect of granularity, I am not sure how difficult that is, for some software, like those that spawn child processes, maybe even with different names or when two instances of the same software are run, but it appears indeed similar to the stop behavior, so that the same logic applies.
