### ISSUE TITLE
Virtualization scheme Version 2 causing extremely slow file deleting speed using del /f /s /q /A:- ::::C

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#3650]
### Describe what you noticed and did

Virtualization scheme Version 2 causing extremely slow speed when using `del /f /s /q /A:- ::::C` to delete files  (**!!!Warning!!! DO NOT run it in REAL system!!!** Replace ::::C with C:)

### Expected behavior

It should as fast as Virtualization scheme Version 1. 

### Affected program

cmd.exe 

### Download link

N/A

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie v1.13.0

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Enterprise LTSC 2021 x64 (21H2)

### In which Windows account you have this problem?

An account with UAC protection set to Always notify.

### Please mention any installed security software

ESET Internet Security 17.0.16.0

**Comment by bastik-1001** [comment]
Just for my curiosity, did you notice other performance degradation from scheme 1 to scheme 2?

**Comment by offhub** [comment]
The problem is that the time increases exponentially as the number of files/folders processed increases.


`UseFileDeleteV2=n`
![sbie3650-n2](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/033355c9-ab07-4c9f-8945-a0ce10db461b)
![sbie3650-01](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/dca0c5a0-1373-40f8-8d5d-10b3b4ebe294)

`UseFileDeleteV2=y`
![sbie3650-y2](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/e8637a3d-2a6f-45a2-a2c3-8308a5c04081)
![sbie3650-00](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/ee52530d-b125-490a-8de2-90ee44b99eae)

**Comment by DavidXanatos** [comment]
Yea, I'm not sure how to easily fix this, the issue is that each time something gets deleted we need to update the FilePaths.dat file.

The proper fix would be to let the service maintain a cached database but then we would need to query the service on every file operation, or alternatively keep a per process cache but use the service to maintain the FilePaths.dat file and push updates to all running processes. That would be overall slower but would have constant performance no mater how many files get deleted.

In my opinion deleting a lot of host files within the sandbox is a rare use case hence the current tradeoff overall is beneficial.

That said assuming no contention for the FilePaths.dat we could improve the update procedure to not re create the entire file from scratch, but only append entries if the file was not modified in the mean time.

**Comment by bastik-1001** [comment]
Thank you for the explanation.

> That said assuming no contention for the FilePaths.dat we could improve the update procedure to not re create the entire file from scratch, but only append entries if the file was not modified in the mean time.

While I don't know how much of a reduction this will bring, it sounds like an improvement.

**Comment by DavidXanatos** [comment]
It would help a lot, and now that I think of it, we should improve also on the edge case of thousands of files on one directory, this is also not handled ideally

**Comment by bastik-1001** [comment]
@offhub, Can you give some examples again, to show by how much it was improved?

**Comment by DavidXanatos** [comment]
Not its as fast as scheme V1 the differenc is withing the error margin.

**Comment by offhub** [comment]
### Old (~319 secs)
![sbie3650old](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/dab6b654-24c9-4f3e-897a-0ace37e68ba1)

### New (~24 secs)
![sbie3650new](https://github.com/sandboxie-plus/Sandboxie/assets/6871698/85702626-5b73-4808-9367-d9567551a61c)
