### ISSUE TITLE
Can Sandboxie Destroy your computer?

### ISSUE THREAD

**Issue by User5959** [sandboxie-plus/Sandboxie#366]
The title says it all.

**Comment by BurntDog** [comment]
What are you asking? Are you asking if you run a infected file will that virus harm your system or just Sandboxie itself?

**Comment by User5959** [comment]
I am asking will Sandboxie destroy my computer if I do something wrong

**Comment by BurntDog** [comment]
I am sure someone that is directly working on this project will give you a better answer I'll just say this:
First use the correct installer, 32bit installer for a 32bit system and a 64bit installer on a 64bit system. 
As long as the installation completes with no errors (I never had any issues) all should be fine with this app.
Playing safe ----> _If you edit (this app) any critical settings or ini files Don't, unless you know what you're doing._ <---Playing safe
To help you better understand. I made a quick batch file that would download several files from the web then run one of the files.
Now, If I did that on my normal drive/desktop that file once run would add/delete a registry  value, add exclusions to Defender Antivirus and install a remote administration tool . 

None of this happened cause I ran it in Sandboxie keeping my system and normal drive untouched. After I always "Delete  Content" from Sandboxie  environment.  Hope this helps you understand a little better. Sandboxie is a safe app and has been around for years.

**Comment by bastik-1001** [comment]
Destroying your computer as in damaging your hardware is very unlikely as the software itself does not do anything critical, like software that tries to overclock your processor to make it faster. Overclocking software can make system unstable and damage hardware, even when Sandboxie is used, but Sandboxie in itself does nothing critical like that.

Destroying your computer as in damaging your operating system is also unlikely to happen by Sandboxie on its own, but if you would configure a sandbox with direct write access to system critical files and some software inside that sandbox would be messing with those files then the software could be damaging your system on a software level. However that software would be doing that without Sandboxie anyway, so that you are not worse off.

**Comment by CoolDude562** [comment]
I got a virus when downloading Sandboxie which is weird because I used it on another pc and it had no virus.

**Comment by isaak654** [comment]
> 
> 
> I got a virus when downloading Sandboxie which is weird because I used it on another pc and it had no virus.

It has been explained here:
https://github.com/sandboxie-plus/Sandboxie/issues/387#issuecomment-761609888
