### ISSUE TITLE
Show tooltips for checkboxes when cursor hover

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#379]
For example, when cursor hover at:
![1](https://user-images.githubusercontent.com/56181919/104573584-f7cf6700-564c-11eb-8d83-1c3c784894d8.PNG)
Then show detail: 
![2](https://user-images.githubusercontent.com/56181919/104573729-24837e80-564d-11eb-96e6-213a101927a3.PNG)

**Comment by 0x391F** [comment]
By the way, it's better to introduct setting's default value in detail, for example, default status of checkbox (selected or not).

**Comment by DavidXanatos** [comment]
Yea some verbose tool tips for the Plus UI sound like a good idea, but its tedious birring work so I'll put it on the very bottom of my todo pile ;)

**Comment by darkred** [comment]
@DavidXanatos 
Regarding Options|Global Settings|'General Option' tabs  (Sandboxie Plus),
there are 4 entries that have 3-state checkboxes (Default -> On -> Off) :
- `Use Dark Theme`
- `Check periodiocally for updates`
- `Add 'Run Sandboxid' to the explorer context menu`
- `Open urls from this ui sandboxed`

<details>
<summary>Screenshot</summary>

![2021-02-02_163004](https://user-images.githubusercontent.com/723651/106614370-ef938900-6573-11eb-850f-df87c9048e45.jpg)
</details>

I find the 'Default' state not as self-explanatory as the other two.
that's why I'd suggest that, if you added tooltips for these specific settings (showing the default value in each one), 
then to also change their checkboxes to 2-state (On -> Off).

Thank you

PS. By the way, thanks a lot for your hard work continuing Sandboxie as free source !!

**Comment by DavidXanatos** [comment]
as we have a new alive request for tooltips I'll close this one
