### ISSUE TITLE
How to connect sandboxied programs through proxy?

### ISSUE THREAD

**Issue by Kuhicop** [sandboxie-plus/Sandboxie#3982]
### Describe what you noticed and did

I'm reading the sandboxie-docs and I don't find how to use proxy through the apps running under sandboxie

Trying to run proxifier it runs in my host machine instead of the sandbox

### Expected behavior

Proxifier should run sandboxed	

### Affected program

Proxifier

### Download link

https://www.proxifier.com/

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie Control v5.68.7

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro 10.0.19045 x64

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Windows defender (default)

**Comment by Kuhicop** [comment]
I'm trying to setup a socks5 proxy with authentication user&pass

**Comment by bastik-1001** [comment]
There is no stable release that contains that feature, so that it won't work with the version you use. This is included in the pre-release 1.14.0 / 5.69.0 and newer.

An example line in the Sandboxie.ini is build like this:
`NetworkUseProxy=*,Address=IPpointingtoproxy;Port=portnumber;Auth=No/Yes`
for example with data
`NetworkUseProxy=*,Address=192.0.2.0;Port=24;Auth=no`

Sandboxie-Plus (starting with 1.14.0) has a user interface at Network Options > [Internet Proxy] where you can set it, so it will add the line automatically, like:
`NetworkUseProxy=*,Address=192.0.2.0;Port=24;Auth=Yes;Login=usermane;EncryptedPW=onlqiA`
The proxy can be used for anything in that box or for defined processes, like "program.exe":
`NetworkUseProxy=program.exe,Address=192.0.2.0;Port=24;Auth=Yes;Login=name;EncryptedPW=onlqiA`

**Comment by ccchan234** [comment]
> There is no stable release that contains that feature, so that it won't work with the version you use. This is included in the pre-release 1.14.0 / 5.69.0 and newer.
> 
> An example line in the Sandboxie.ini is build like this: `NetworkUseProxy=*,Address=IPpointingtoproxy;Port=portnumber;Auth=No/Yes` for example with data `NetworkUseProxy=*,Address=192.0.2.0;Port=24;Auth=no`
> 
> Sandboxie-Plus (starting with 1.14.0) has a user interface at Network Options > [Internet Proxy] where you can set it, so it will add the line automatically, like: `NetworkUseProxy=*,Address=192.0.2.0;Port=24;Auth=Yes;Login=usermane;EncryptedPW=onlqiA` The proxy can be used for anything in that box or for defined processes, like "program.exe": `NetworkUseProxy=program.exe,Address=192.0.2.0;Port=24;Auth=Yes;Login=name;EncryptedPW=onlqiA`


Hi all,

Can anyone update me on the current functionality of 3rd party proxy software like Proxifier when used inside a Sandboxie environment? Despite setting up Proxifier with a USA proxy and verifying its rules inside the sandbox, my IP still appears as Asian. I've installed both Proxifier and Chrome on the host, then ran them inside the sandbox. Is this a known limitation of Sandboxie or might I be missing a step?

Proxy support in Sandboxie seems relatively new and I couldn't find detailed info in the manual, so I'm seeking insights here. Thanks!

P.S. I'm looking to run multiple instances of Proxifier in separate sandboxes to isolate them from the Win10 host. Any advice on this would also be appreciated.
