### ISSUE TITLE
Can't run any .exe file in sandboxie-plus

### ISSUE THREAD

**Issue by UnrealKaraulov** [sandboxie-plus/Sandboxie#4150]
### Describe what you noticed and did

1. Install latest release (or previous)
2. Create default sandbox with default settings
3. Try to run any .exe file

### How often did you encounter it so far?

100% cases

### Expected behavior

Run program

### Affected program

Counter-Strike 1.6.exe

### Download link

https://dl.cs-all-servers.ru/14/Counter-Strike%201.6.exe

### Where is the program located?

Not relevant to my request.

### Did the program or any related process close unexpectedly?

Yes, it did, but no .dmp file has been created in the system.

### What version of Sandboxie are you running now?

Release v1.14.6 / 5.69.6 Sandboxie-Plus-x64-v1.14.6.exe

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### In which sandbox type you have this problem?

All sandbox types (I tried them all).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 x64 23H2

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Kaspersky Free

### Did you previously enable some security policy settings outside Sandboxie?

No

sorry for bad english language

### Sandboxie.ini configuration

```ini
DefaultBox=DefaultBox
FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX%
KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX%
IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION%
Template=7zipShellEx
Template=Edge_Fix
Template=Kaspersky
Template=NotepadPlusPlus_fix
Template=OfficeLicensing
Template=WindowsLive
Template=WindowsRasMan
```

**Comment by love-code-yeyixiao** [comment]
I can't reproduce it on my Windows10 20H2 physical system with the same sandboxie version,because it works well so far.






---Original---
From: "Unreal ***@***.***&gt;
Date: Wed, Aug 14, 2024 19:42 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [sandboxie-plus/Sandboxie] Can't run any .exe file in sandboxie-plus(Issue #4150)




 
Describe what you noticed and did
  
Install latest release (or previous)
 
Create default sandbox with default settings
 
Try to run any .exe file
  
How often did you encounter it so far?
 
100% cases
 
Expected behavior
 
Run program
 
Affected program
 
Counter-Strike 1.6.exe
 
Download link
 
https://dl.cs-all-servers.ru/14/Counter-Strike%201.6.exe
 
Where is the program located?
 
Not relevant to my request.
 
Did the program or any related process close unexpectedly?
 
Yes, it did, but no .dmp file has been created in the system.
 
Crash dump
 
No response
 
What version of Sandboxie are you running now?
 
Release v1.14.6 / 5.69.6 Sandboxie-Plus-x64-v1.14.6.exe
 
Is it a new installation of Sandboxie?
 
I recently did a new clean installation.
 
Is it a regression from previous versions?
 
No response
 
In which sandbox type you have this problem?
 
All sandbox types (I tried them all).
 
Can you reproduce this problem on a new empty sandbox?
 
I can confirm it also on a new empty sandbox.
 
What is your Windows edition and version?
 
Windows 11 x64 23H2
 
In which Windows account you have this problem?
 
A local account (Administrator).
 
Please mention any installed security software
 
Kaspersky Free
 
Did you previously enable some security policy settings outside Sandboxie?
 
No
 
sorry for bad english language
 
Trace log
 
No response
 
Sandboxie.ini configuration
 DefaultBox=DefaultBox FileRootPath=\??\%SystemDrive%\Sandbox\%USER%\%SANDBOX% KeyRootPath=\REGISTRY\USER\Sandbox_%USER%_%SANDBOX% IpcRootPath=\Sandbox\%USER%\%SANDBOX%\Session_%SESSION% Template=7zipShellEx Template=Edge_Fix Template=Kaspersky Template=NotepadPlusPlus_fix Template=OfficeLicensing Template=WindowsLive Template=WindowsRasMan

**Comment by rakakarakaka** [comment]
Есть проблема какая-то, ни одна программа не запускается в песочнице, кроме стандартных, если открыть в песочнице проводник, то пишет "ресурс не доступен" при попытке открыть любую папку.

**Comment by UnrealKaraulov** [comment]
@love-code-yeyixiao 

![image](https://github.com/user-attachments/assets/d9d99b42-c1c5-4d69-8825-80fab24e892c)

Can't run any .exe file with sandboxie-plus

**Comment by UnrealKaraulov** [comment]
@isaak654 but in [Sandboxie-Classic-x64-v5.69.6.exe](https://github.com/sandboxie-plus/Sandboxie/releases/download/v1.14.6/Sandboxie-Classic-x64-v5.69.6.exe) no issue with run any .exe files! I has this issue only with sandboxie-plus.

Maybe problem is not Kaspersky?

**Comment by isaak654** [comment]
Sandboxie Plus has more DLL files that may be blocked than Classic edition, the only way to know for sure is to uninstall Kaspersky and install the Plus edition.

**Comment by isaak654** [comment]
Sandboxie Plus has more files that may be blocked than Classic edition, the only way to know for sure is to uninstall Kaspersky and install the Plus edition.

**Comment by UnrealKaraulov** [comment]
@isaak654 problem solved...

1. Remove sandboxie-plus
2. Install sandboxie-classic
3. Install sandboxie-plus in sandboxie-classic directory 

....
