### ISSUE TITLE
Internet Proxy not working

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#4197]
### Describe what you noticed and did

[https://forum.xanasoft.com/threads/internet-proxy-not-working.860/](https://forum.xanasoft.com/threads/internet-proxy-not-working.860/)

> Running a sandboxed app ( any app) with proxy doesn't work for me. My home IP is still showing on browsers whenever i try to run it via proxy. 

### How often did you encounter it so far?

Every time.

### Expected behavior

Proxy to work properly.

### Affected program

Any

### Download link

Any should do the trick

### Where is the program located?

This was not stated, The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus 1.14.6

### Is it a new installation of Sandboxie?

This was not stated, just that previous versions did not work either.

### Is it a regression from previous versions?

Previous versions did not work either.

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 22H2

### In which Windows account you have this problem?

This was not stated, but I hope it is going to be not relevant to the request.

### Please mention any installed security software

This was not stated.

### Sandboxie.ini configuration

```ini
Enabled=y

BlockNetworkFiles=y

RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%

RecoverFolder=%Personal%

RecoverFolder=%Desktop%

BorderColor=#02f6f6,ttl

Template=OpenBluetooth

Template=SkipHook

Template=FileCopy

Template=qWave

Template=BlockPorts

Template=LingerPrograms

Template=AutoRecoverIgnore

ConfigLevel=10

UseFileDeleteV2=y

UseRegDeleteV2=y

AutoRecover=y

ClosedFilePath=!<InternetAccess>,InternetAccessDevices

PromptForInternetAccess=y

NetworkUseProxy=*,Address=5.252.188.xxx;Port=62xxx;Auth=Yes;Login=xxx;EncryptedPW=8vu/teXRlolLRS5lN6NL/A;Bypass=

---

I added x's so i dont reveal my proxy here...
```

**Comment by DavidXanatos** [comment]
the password was inproperly stored we were missing the tailing == once it is resaved with the latest commited version it should work fine.
however I'm not sure why that would give you no procy in all my tests then it just failed entierly to connect as it should

**Comment by bastik-1001** [comment]
Thank you for the quick fix. I informed the user in the forum.

Maybe there will be a follow-up to what happens, when it fails, because, as you said, it should fail hard and the proxy should not be bypassed.

**Comment by love-code-yeyixiao** [comment]
If the proxy address is invalid,will the proxy still work?Or just occur a connecting failing?
At very least,when I use ping.exe with a proxy configruation which have a wrong proxy address,it could connect normally yet.






---Original---
From: "Sebastian ***@***.***&gt;
Date: Sat, Aug 31, 2024 00:14 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [sandboxie-plus/Sandboxie] Internet Proxy not working (Issue#4197)




 
Thank you for the quick fix. I informed the user in the forum.
 
Maybe there will be a follow-up to what happens, when it fails, because, as you said, it should fail hard and the proxy should not be bypassed.

**Comment by bastik-1001** [comment]
This is not my personal issue. I have not set-up a SOCKS5 proxy.

> If the proxy address is invalid,will the proxy still work?
Fresh default box (SandboxieLogon is used), that has network access by default:
With Firefox there will be a network timeout. (It can't use the proxy, since there is none) It fails hard, as my expectation was.
With ping I can do "ping google.de" and get a result, even though I expected it to fail, since there is no proxy.
With tracert I can get a trace from my network to google.de, which I expected to fail.

In case the original reporter gives more insight, I'll copy that into this issue.

**Comment by offhub** [comment]
> At very least,when I use ping.exe with a proxy configruation which have a wrong proxy address,it could connect normally yet.
SOCKS5 only supports TCP and UDP traffic.

**Comment by bastik-1001** [comment]
The user reported back:

> and yes the apps are not blocked which i thought but it just bypasses, any app i try

**Comment by offhub** [comment]
There may be another proxy running on the system. I think the proxy server defined in Sandboxie is not used when a system-wide (or application-wide) proxy server is defined.

1. Run sandboxed CMD
2. Run the following command
```
reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v proxyEnable /t REG_DWORD /d 0 /f
```
3. Run a browser in the same sandbox
4. See if it makes a difference

**Comment by love-code-yeyixiao** [comment]
So&nbsp; maybe we should add a feature which deny all connectings that are not through our socks5 proxy in order to stop unknown privacy losing?



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 4, 2024 02:12 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sandboxie-plus/Sandboxie] Internet Proxy not working (Issue#4197)




 
There may be another proxy running on the system. I think the proxy server defined in Sandboxie is not used when a system-wide (or application-wide) proxy server is defined.
  
Run sandboxed CMD
 
Run the following command
  reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v proxyEnable /t REG_DWORD /d 0 /f   
Run a browser in the same sandbox
 
See if it makes a difference

**Comment by bastik-1001** [comment]
> maybe we should add a feature which deny all connectings that are not through our socks5 proxy

To avoid there being leaks, this seems like a good idea. Since users want to use a proxy, they probably expect it to be used. Users could disable the blocking, but I assume that most prefer a default that is safe.

**Comment by DavidXanatos** [comment]
well the connection should nto be bypassed, if the proxy fails it fails it whould not all back to a direct connection, not sure why that happened for this user

**Comment by bastik-1001** [comment]
Maybe the user can give more insight how his proxy is set up, to warn about or prevent such cases.

**Comment by love-code-yeyixiao** [comment]
And we can also avoid connectings that are not UDP or TCP being sent.



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 5, 2024 01:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sandboxie-plus/Sandboxie] Internet Proxy not working (Issue#4197)




 
well the connection should nto be bypassed, if the proxy fails it fails it whould not all back to a direct connection, not sure why that happened for this user
