### ISSUE TITLE
Add language setting in Menu -> Options

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#432]
So that user needn't open Opions->Global Settings to set it. 
It looks like this: 
![1](https://user-images.githubusercontent.com/56181919/105487482-13b7b600-5ca8-11eb-838a-3468a541195c.PNG)
I think this setting (Language) is better always in English.

**Comment by lufog** [comment]
I think it's not the best approach, better to add to the program, auto-detection of the system language. And enabling it if program have the necessary language files. In the language settings, add the item ```System language``` and use it by default.

**Comment by bastik-1001** [comment]
In most instances one sets the language once, so that any user would have to select his/her language in the options and since the UI requires a restart there would be no benefit in being able to switch the language over the menu.

It is possible to detect the system language and assume that the user would want Sandboxie to be in that language. As Sandboxie is develop in English, I don't see and issue in that being the default language. I prefer if the language selection is a conscious action of the user. At least the user should have the option to choose the language freely and not be restricted by what the system language is set to.

**Comment by DavidXanatos** [comment]
Its really pointless to make this a menu as bastik-1001 pointed out the settings require a restart currently
Also its not something one would change often.

About language auto detection on start, I may add that but only at some later point in time, currently the translations are often out dated, because I'm still to disorganized.
I should make always a Beta release that gives time for translations to be updated and only a week later or so a final release with up o date translations.

**Comment by bastik-1001** [comment]
It seems reasonable to delay final versions until translators had time to update the translations and anyone willing to try the new version can use the beta. Only important security fixes should be released in a final version (without beta) to ensure it being installed quickly even if the translation would be out of date, as this would not be of any importance over something that could escape the sandbox, for example, or a BSOD, as another example.
