### ISSUE TITLE
Canvas: Software only. Hardware acceleration disabled

### ISSUE THREAD

**Issue by 344389541** [sandboxie-plus/Sandboxie#440]
edge run  in sbie， 
Canvas: Software only. Hardware acceleration disabled

![image](https://user-images.githubusercontent.com/26427035/105824786-c7e37480-5ff9-11eb-816b-d7d864929dd7.png)
![image](https://user-images.githubusercontent.com/26427035/105824775-c4e88400-5ff9-11eb-9872-163ae0267eab.png)

edge version:88
![image](https://user-images.githubusercontent.com/26427035/105824795-cade6500-5ff9-11eb-94da-540e1eb33a24.png)

sbie version: 5.45
![image](https://user-images.githubusercontent.com/26427035/105824858-de89cb80-5ff9-11eb-9ba3-62890535f7d4.png)

**Comment by NMHy8C** [comment]
Vivaldi has the same HW issue when sandboxed. Thank you.

Vivaldi 3.6 Build 2165.34 x64
Sandboxie Plus 0.6.0 x64
Windows 10 20H2 x64

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/107700641-12324a00-6cb8-11eb-9fe4-26e4d3a48006.png)
i.e. OpenWinClass=# solves the issue.
the down side is that en edge started on the desktop will see the sandboxed one and tell it to do something instead of spawning a second instance. But two edges in different boxes should work fine.
Not sure whats the exact issue i.e. is we can get away with allowing only a specific window to be not renamed, have to investigate that further

**Comment by DavidXanatos** [comment]
This is a peculiar bug, on my VM once I add the aforementioned setting HW acceleration works just fine, also when I disable a small piece of chrome workaround code in the CreateWindowEx function.
On my real system however when I do the same, chrome fails to start, Its the issue affecting #310 and #547 (which work fine in the VM) as for these the  workaround code wold be always disabled, since they ate not recognized as chromium based, despite being electron apps.

Now it gets even weirder that workaround was for an other old problem that does not seam to be still present and chrome itself seams not to run into the HW acceleration causing crash issue, with said setting or the code disabled, chrome starts on my real system just fine with full HW acceleration active.
