### ISSUE TITLE
Sandboxie and Virtual Memory

### ISSUE THREAD

**Issue by stdedos** [sandboxie-plus/Sandboxie#442]
Is it possible that Sandboxie has something to do with that?
![image](https://user-images.githubusercontent.com/133706/105912247-d6e71880-6033-11eb-9140-95078669470f.png)

I guess it's obvious that I have already checked that I do have Virtual Memory:
![image](https://user-images.githubusercontent.com/133706/105912339-0138d600-6034-11eb-94fe-04cdd0203b3e.png)

**Comment by DavidXanatos** [comment]
I can't imagine how, but than I've seen a few very odd bugs its not impossible.

**Comment by stdedos** [comment]
I checked via unsandboxed Procmon for access to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PagingFiles`, nada

Ofc, I am not familiar with Windows programming, and I cannot know what trickery they have tried to use to do such detection. I tried running "As Admin" and WinXp/Win7 compatibility, nada either

**Comment by DavidXanatos** [comment]
why does this tool require virtual memory yin the first place?
with enough ram that is not needed.

**Comment by stdedos** [comment]
That is my question too 😛

I have 32GB RAM; it shouldn't be a problem.

**Comment by typpos** [comment]
Maybe this helps..
* Found a suggestion that the msg is misleading and it's actually a graphics card compatibility issue.
* I wonder how/if Windows via WOW64 presents (disk-pageable) virtual memory to a 32-bit application when there are already the max 4GB of real RAM?
* Since this is a game from 2003, maybe the query fails because there is more VM/RAM than the developer ever anticipated.
* If all fails, maybe get the PS2/XBOX/GB release and use an emulator :-)

**Comment by stdedos** [comment]
All good guesses/assumptions 😀

**Comment by DavidXanatos** [comment]
soo its not a sanndboxie issue and can be closed?

**Comment by stdedos** [comment]
I don't know that (since I have only tried it inside Sandboxie), but I am fine you ignoring it until I verify it somehow (e.g. inside some VM)
