### ISSUE TITLE
[Sandboxie Plus] No clicked signal in Apply button

### ISSUE THREAD

**Issue by isaak654** [sandboxie-plus/Sandboxie#462]
In Options -> Global Settings, the "Apply" button has no clicked signal when you click on it, while "Cancel" and "OK" button have a better click feedback.

I don't know if it's an expected behavior, but I think it should have the same clicked signal of other buttons.

**Comment by typpos** [comment]
That's because various buttons in the UI currently trigger on "Mouse Down" instead of "Mouse Click" events:
* Global Settings - Apply
* Global Settings - OK
* Snapshot Manager - Take Snapshot
* Snapshot Manager - Go to snapshot
* Snapshot Manager - Remove snapshot
* File Recovery - Add Folder
* File Recovery - Close
* Sandbox options - OK
* Sandbox options - Edit ini - Edit | Save | Cancel
* Sandbox options - Various top-right buttons in various tabs

**Comment by DavidXanatos** [comment]
I have changed all buttons from the pressed to the clicked slot that should improve the behavior

**Comment by typpos** [comment]
Tested & works.  
:thumbsup: for David's patience.
:thumbsdown: for Qt
