### ISSUE TITLE
Questions and suggestions from classic Sanboxie User

### ISSUE THREAD

**Issue by tomasts248** [sandboxie-plus/Sandboxie#466]
Hi, 
I'm so happy to had found about this fork. Right now I haven't migrated from old sandboxie, I read this https://github.com/sandboxie-plus/Sandboxie/issues/259 and perhaps the whole process could be completely automated, with an automatic backup or rollback included? 
First questions: is it possible to select different storage settings per each sandbox? I know in the classic is not possible... that's quite a bug as I don't have enough space to carry everything in my main drive.
Maybe something that would be damn useful is to have a an automated way to compare a sandbox with non-sandboxed files, useful for checking if a software is portable or not among other things or to analyze malware behaviour. I recap there was a sandboxie plugin that this but it wasn't friendly at all. Also another feature may be to be able to release from a sandbox all files, or to not ask but recover all, somethimes I only use Sandboxie for running multiple instances of a software. Also is great to to see forced programs and different colors :) well that would be it..
Have a nice weekend!!!

**Comment by typpos** [comment]
> First questions: is it possible to select different storage settings per each sandbox? I know in the classic is not possible... 

Edit your sandboxie.ini file and add setting "FileRootPath" to your specific sandbox, for example:

`
FileRootPath=D:\My_Drive_D_Sandboxes\%SANDBOX%
`

This applies to that specific sandbox only and works for sandboxie classic and sandboxie plus.

Notes:
* You can use folders on a removable drive (eg, USB key), or on encrypted drives, like VeraCrypt (TrueCrypt).
* Don't select a drive letter without a directory, eg, "F:\". This will throw an error on app start.
* You can but shouldn't use a fixed path without the "%SANDBOX%" wildcard. Otherwise, if you ever create a new sandbox from that sandbox, then both boxes end up pointing at the same base folder. Unlikely that you want that, and it will cause errors if you try to start apps in both boxes at the same time.
* Don't point sandbox folders inside other sandboxes :-)

**Comment by typpos** [comment]
@DavidXanatos 
In this context, why do sandboxes need to be empty when I want to rename them, and can I move a (filled) sandbox from one drive to another?

**Comment by DavidXanatos** [comment]
> 
> 
> @DavidXanatos
> In this context, why do sandboxes need to be empty when I want to rename them, and can I move a (filled) sandbox from one drive to another?

They need to because there is no move routine implemented, so if you rename its folder first and then the box it should work fine.

I should improve this behavior, may be for h next build

Moving to an other location/drive from the UI is however a bit more difficult the move routines I have used for snapshots work only on the same volume/drive, if you want to move a file to an other drive, you have to do that by copy and delete, and than you need a better progress indicator and so on, I'll probably add a relocate box UI command at some point but probably not any time soon.

**Comment by typpos** [comment]
Thanks David. Don't worry about adding special features for this on my behalf. I just needed to know. Moving these by hand is fine.

**Comment by hg421** [comment]
@DavidXanatos Is it really unproblematic to move the files by hand when changing the box name? Since some files such as the `RegHive`s do contain the original box name inside them...

**Comment by DavidXanatos** [comment]
> 
> 
> @DavidXanatos Is it really unproblematic to move the files by hand when renaming a box that is not empty? Just making sure since some files such as the `RegHive`s do contain the original box name inside them...

good question... I shall investigate that and post here later the result...

**Comment by tomasts248** [comment]
Thanks @typpos and @DavidXanatos !!! :)

**Comment by typpos** [comment]
> since some files such as the `RegHive`s do contain the original box name

In case this is what you are referring to: The sandbox name in the registry key name "HKU\Sandbox_user_boxname" does change to the new sandbox name.

**Comment by DavidXanatos** [comment]
I think renaming the folder should be fine i don't anticipate any obvious issues all the apps inside are oblivious to the physical paths anyways.
