### ISSUE TITLE
Sandboxie - Portable Mode (create Sandbox folder in the root folder instead of "C:\Sandbox"/drag drop support/Logging isn't working)

### ISSUE THREAD

**Issue by GunGunGun** [sandboxie-plus/Sandboxie#47]
Hi,

I really liked the new sandboxie plus UI so far, just somehow I can't drag exe file to the main Sandboxie Plus UI to run the exe file like the old Sandboxie UI:

https://i.imgur.com/hIJ1GZd.png

I think drag and drop exe file is very good to have, so I hope you will consider adding this feature.

The logging feature seems to not working too, I couldn't find any log file in the root folder of Sandboxie:

https://i.imgur.com/vW7AWXH.png

And I would love to see a way to create Sandbox folder in the root folder to make the Portable Mode even "more portable". Currently Sandbox folder is created in C:\ (OS drive).

Thank you very much for all the improvements.

**Comment by GunGunGun** [comment]
Sorry, this link https://i.imgur.com/A4VrGtH.png instead of https://i.imgur.com/vW7AWXH.png

**Comment by DavidXanatos** [comment]
Yes because the drag and drop is not added yet, i will put that on my todo.

I wil check the log file issue 
and customizing the config to have the root folder someware else is on my todo already.

**Comment by AndhikaWB** [comment]
Just wanna let you know that some apps may not work correctly if moved to a long path (depends on how long the path is), so moving the Sandbox folder is not a very good idea. For example Python and many LEGO games. I don't know how they may behave when sandboxed since the path is emulated but I expect similar result.

However, there is a trick (used by Python installer) to allow long path on Windows by simply editing registry value under `HKLM\System\CurrentControlSet\Control\FileSystem\LongPathsEnabled` to 1 (DWORD). Note that I haven't personally tested it.
