### ISSUE TITLE
DefaultBox forced recreation

### ISSUE THREAD

**Issue by silvestron** [sandboxie-plus/Sandboxie#487]
Quoting from the changelog:

> when DefaultBox is not found by the SandMan UI, it will be recreated

I have renamed my DefaultBox to Defaultbox, could this cause an issue? If I recall correctly Sandman is part of Sandboxie Plus, so this shouldn't affect me for now, but I'd like to migrate to Plus at some point.

**Comment by LukeSeers** [comment]
If you was to update to the latest version (have not tested it myself) it should not cause any issues. It would only just create a new sandbox with the name "DefaultBox". 

I also just made a post regarding **"when DefaultBox is not found by the SandMan UI, it will be recreated"** https://github.com/sandboxie-plus/Sandboxie/issues/485#issuecomment-770469609 it would be nice to get your thoughts about my idea maybe?

**Comment by typpos** [comment]
>  It would only just create a new sandbox with the name "DefaultBox

Ummm. There are some subtle issues with 0.6.5 because of inconsistent case(in)sensitive matching of sandbox names. I believe/guess they will not actually break anything, but I haven't tested all areas where default boxes are relevant:
0. Install Plus 0.6.5 in a fresh Windows Sandbox.
1. Renaming DefaultBox to Defaultbox makes it revert to "DefaultBox" in the UI, but the ini file now calls it Defaultbox. That's despite the automatic reload of the ini.
2. Now exit Plus and restart. The box is now called "Defaultbox" as per ini.
3. Fortunately, starting an application from outside the sandbox with context menu "run sandboxed" and CTRL held uses the "Defaultbox" to start the application. However, it creates a folder "DefaultBox", not "Defaultbox".
4. If instead you start an application from inside Plus, then the sandbox folder is created as "Defaultbox".
5. etc


> I have renamed my DefaultBox to Defaultbox, could this cause an issue?

I guess you could..

* Exit Sandboxie
* Stop the sandboxie service
* Rename your windows folder to "DefaultBox"
* Edit your ini file to call it "DefaultBox"

and you should be fine.

**Comment by silvestron** [comment]
> If you was to update to the latest version (have not tested it myself) it should not cause any issues.

That is not the case, yet. Sandboxie Classic and Plus have differences. The last time I tried Plus it still didn't support disabling the colored borders in the global settings, in Classic you can do that. While that's a minor thing, I saw other more important differences, like Sandboxie Plus has more issues with electron apps than Classic (or at least it did have the last time I tried Plus).

> I also just made a post regarding "when DefaultBox is not found by the SandMan UI, it will be recreated" #485 (comment) it would be nice to get your thoughts about my idea maybe?

Sometimes I've deleted my DefaultBox. It would be annoying having to have it if I didn't want it. I think that if there's a need for a "default sandbox" a better solution, in my opinion, could be adding a new setting like `DefaultSandbox=DefaultBox` in the global settings and users can modify it if they want to delete their DefaultBox.

> There are some subtle issues with 0.6.5 because of inconsistent case(in)sensitive matching of sandbox names

The problem is Windows more than anything because file path in Windows is case insensitive, and unfortunately this is not going to change because so many things would break otherwise.

> Rename your folder to "DefaultBox"

I've never renamed sandboxes with contents. Is that something safe to do?

**Comment by typpos** [comment]
> I've never renamed sandboxes with contents. Is that something safe to do?

I've done it many times and worked just fine, though the official answer is pending: https://github.com/sandboxie-plus/Sandboxie/issues/466#issuecomment-770225763
