### ISSUE TITLE
For the 0.2/5.4.1 release, both 32-bit and 64-bit .exe's are detected as trojans

### ISSUE THREAD

**Issue by at-xa** [sandboxie-plus/Sandboxie#49]
Windows Security detects :
SandboxieInstall64-v5.41.0.exe (with) Trojan:Win32/Ymacco.AA07
SandboxieInstall32-v5.41.0.exe (with) Trojan:Win32/WacatacC!ml

I'm new to Windows, so I don't know if this is because Sandboxie is seen as suspicious because all of its admin capabilities, or there's something bad going on here.

**Comment by n01337** [comment]
It would load the unsigned driver if Windows is put into "Test mode" by rebooting it appropriately _once_. This works very well for e.g. the Sony Xperia rooting tool "flashtool" - and there would be no virus warnings anymore. This might be the more "approachable" option instead of untrusted certificates.

**Comment by DavidXanatos** [comment]
> 
> 
> It would load the self-signed driver if Windows is put into "Test mode" by rebooting it appropriately once.

Well putting your windows permanently into test mode, gives you a ugly watermark on the bottom of the desktop.
And than your windows will load not only Sbie but any other unsigned driver as well. So at least in principle that would weaken your security. While the use of a leaked certificate does not do that, it only requiters you to assert dominance once over your antivirus tool.
