### ISSUE TITLE
Big Browser Showdown

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [sandboxie-plus/Sandboxie#497]
I tried out a couple of popular browsers in SB Classic 5.47.0
The idea is to install the browser into a sandbox and subsequently run the browser from there to have an alternative at hand whenever you need a second (or third) browser.

### Firefox
Source: https://www.mozilla.org/en-US/firefox/download/thanks/
File: `Firefox Installer.exe` = 0.3 MB
👍 **Success** Although it uses the profile from the regular install outside the sandbox.

Source2: https://www.mozilla.org/de/firefox/all/#product-desktop-release
File: `Firefox Setup 85.0.exe` = 53.6 MB
👍 **Great Success** Properly keeps user profile from the regular install outside the sandbox separated.

### Brave
Source: https://brave.com/
File: `BraveBrowserSetup.exe` = 1.1 MB
👎 **Fail** Can't install.

Source2: https://github.com/portapps/brave-portable
File: `brave-portable-win64-1.18.78-69-setup.exe` = 81.1 MB
👍 **Success** It's not an official version, though.

### Chrome
Source: https://www.google.com/chrome/
File: `ChromeSetup.exe` = 1.2 MB
👎 **Fail** Can't install.

Source2: https://portableapps.com/apps/internet/google_chrome_portable
File: `GoogleChromePortable_88.0.4324.104_online.paf.exe` = 1.5 MB
👍 **Success**

### Vivaldi
Source: https://vivaldi.com/
File: `Vivaldi.3.6.2165.34.x64.exe` = 68.1 MB
👎 **Fail** Can't install.

**Comment by xame-arch** [comment]
Brave Browser : https://www.hybrid-analysis.com/sample/3cc41fa918736a88c59ce882339b2ed1d4bc5e0bbdaa1a092491f15005d9d76e

Chrome : https://www.hybrid-analysis.com/sample/1d6d91ac35420f17bbde03ec6fb8544fb52fa83c0d7fe163c436fa516c9805f8

Vivaldi: https://www.hybrid-analysis.com/sample/e3112776d729ea9819fd26279ee740c9adb6bd30453cdfba14fcdc56ca6e70a9

TOR: https://www.hybrid-analysis.com/sample/59e610eca00e3ce8bf1f584bdfbbce49ac0ace809d9bc09e4e6d214d972e1877

I add TOR because it works every other time. When it doesn't work, the sandboxie icon disappears and I can't open a new tab neither do copy and paste anymore. When I try to access the sandboxie it asks me first for administrator privileges, I say YES and when I click on the Tor window it prompts me to save more files and then each time I get a GUIPROXY error list and then a dangerous crash, and if I let the sandboxie icon clear and close TOR then restart sandbox TOR error access denied.

**Comment by DavidXanatos** [comment]
i think its outdated by now you may want to re do the tests with a new build
