### ISSUE TITLE
TrojanWin32Vigorf.A infected? False alarm or what?

### ISSUE THREAD

**Issue by szymario** [sandboxie-plus/Sandboxie#52]
When I try to DL SandboxieInstall64-v5.41.0.exe file, I get alert from Chrome browser and Win10 Defender Shield, that the file is infected with TrojanWin32Vigorf.A. Is this a false alarm or what?

**Comment by szymario** [comment]
Seems, that all 4 files (SandboxieInstall32-v5.41.0.exe, SandboxieInstall64-v5.41.0.exe, SbiePlus32.zip, SbiePlus64.zip) are marked by Windows 10 Defender Shield as infected with different trojans.

**Comment by deflock** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/49

**Comment by victorca25** [comment]
False alarm

**Comment by szymario** [comment]
Thanks for answers!

**Comment by DavidXanatos** [comment]
Its because the sandboxie driver is signed with a leaked certificate as a genuine one would cost around 1k€/year.

Without a signature windows wont load the driver so not signing is not an option.

And of cause once a certificate is leaked many people use it some of them bad.

But that does not pos any risks.

Its only an inconvenience as then some Antimalware fools wrongfully flag good software as potentially dangerous.

**Comment by Eric898989** [comment]
Since this project is open source => https://www.codenotary.io/with-codenotary-you-never-have-to-pay-for-code-signing-certificates-again/ ?

**Comment by DavidXanatos** [comment]
I somehow doubt very much that your of the shelf anti malware tool would trust something signed in this way.

**Comment by deajan** [comment]
@DavidXanatos the off the self AV tool probably won't, but it can't get worse than the actual leaked certificate, doesn't it ?

**Comment by DavidXanatos** [comment]
What do you mean with worse?
The Antimalware fools complain the educated user clicks on ignore/allow and that's that.
The tools can't do more than block the file.

**Comment by Krzeszny** [comment]
David, Windows 10 now blocks all your releases in such a way that it's impossible to override SmartScreen. It shows 'This app may harm your device' and asks to delete or keep it but when I click 'Keep', it's removed anyway and says 'Couldn't download - Virus detected'. Retrying the download loops the procedure with the same outcome. Are you sure CodeNotary wouldn't work and there's no way to make freeware drivers work? How about reporting it to Microsoft?

There's the option to click 'Report a download' (at least in Microsoft Edge) and select 'I am the owner or representative of this website and I want to report an incorrect warning about it'.

**Comment by DavidXanatos** [comment]
mmh.... that seams as it is a new edge problem.

be a grown up use a browser that does not patronizes you, for example use Firefox and than you can download it once its on your HDD there is no problem anymore.

I for my part couldn't stand using something that does not leave the last decision to me.

Its strange that edge does not allow sandboxie-plus but is perfectly fine with TaskExplorer, its all BS and extortion as simple as that.

If I can finance a certificate form user donation thats fine with me its their money but I wont waste my own money on a certificate.
Some things are a mater of principle!

**Comment by DavidXanatos** [comment]
i added a password protected 7z download that should always work the password is password

**Comment by DavidXanatos** [comment]
Also please try this download: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.2/SandboxieInstall-v5.41.0.exe
it should keep the driver inside obfuscated such as the MSFT stupid screen wont see it.

**Comment by AmyRose1288** [comment]
> Also please try this download: https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.2/SandboxieInstall-v5.41.0.exe
> it should keep the driver inside obfuscated such as the MSFT stupid screen wont see it.

that not works,ESET Internet Security still blocks the installaion

**Comment by DavidXanatos** [comment]
than tell ESET to allow it, without a signature windows will not load that file and wit a signature Antimalware fools will complain.
the only way out is $$ for a own certificate.

**Comment by DavidXanatos** [comment]
In case anyone wants me to get a certificate for $$$ you can donate on my provisional homepage: https://xanasoft.com/
did nto had time to crate much content but the donation button works.

**Comment by DavidXanatos** [comment]
I have made some more changes to the installer https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.2/SandboxieInstall-v5.41.0.exe
now it unpacks the file very late in the installation process.
try it and dont forget once eset complains to create a permanent exemption for c:\profiram files\sandboxie\sbiedrv.sys

**Comment by szymario** [comment]
> I have made some more changes to the installer https://github.com/sandboxie-plus/Sandboxie/releases/download/v0.2/SandboxieInstall-v5.41.0.exe
> now it unpacks the file very late in the installation process.
> try it and dont forget once eset complains to create a permanent exemption for c:\profiram files\sandboxie\sbiedrv.sys

Thanks, I will try. Of course It was also possible to successfuly DL these files with Chrome before, because one can temporarily disable AV protection or not allow to block them.

**Comment by rugabunda** [comment]
Great work, tried and ESET does not detect any issues after removing the sandboxie exemption

**Comment by elonen** [comment]
For me, Windows defender reports **C:\Program Files\Sandboxie\SbieDrv.sys** in th latest release as **Trojan:Win32/Ymacco.AACE**.

**Comment by DavidXanatos** [comment]
if you have the release from github than its just a false positive due to the certificate used

**Comment by n01337** [comment]
This all seems very hacky. Why not instead instruct people to put their Windows machine into Test mode, which circumvents all of this "illegal signing": It would load the unsigned driver if Windows is put into "Test mode" by rebooting it appropriately once. This works very well for e.g. the Sony Xperia rooting tool "flashtool" - and there would be no virus warnings anymore. This might be the more "approachable" option instead of untrusted certificates.

**Comment by DavidXanatos** [comment]
Well its legal enough for windows to accept it only some anti malware fools complain.
It you put your windows into test mode some DRM may not work idk if you can watch 4k netflix with test mode.
It does not sound to me very user friendly to advise users to disable something they may perceive as a security mechanism even if its a buIIshit mechanism. An than there is the ugly watermark.

Look I could make the installer present booth options to the user and make him pick one, with explanations about the security implications of booth.

But than the next problem, you can not enable test mode if you have SecureBoot enabled, now SecureBoot is yet another anti consumer buIIshit mechanism that helps only Corporations and aids DRM but its on by default on standard PCs nowadays and with out you cant enable Test Mode. 

So I couldn't even make the installer succeed on all cases, I would have to tell the users to disable Secure Boot in order to disable driver signature enforcement by enabling Test Mode. That is a terrible user experience.

IMHO its much less trouble to white list the driver with your antivirus fool and be done and continue keeping windows thinking it won while it did not.

**Comment by AndhikaWB** [comment]
In case you don't care about legal issue, you can use a tool like [SigThief](https://github.com/netbiosX/Digital-Signature-Hijack/blob/master/Hijack-Certificates/sigthief.exe) to steal signature from the official `SbieDrv.sys` file and use it on your own driver. However, signature will still appear as invalid when checked from Explorer. Here is the [result](https://www.virustotal.com/gui/file/b62ccc2fad4f3e19dd7ee7b18eec31882c19637058b04bb1b32972061bfe34e4/detection) (4 detections) compared to the [original](https://www.virustotal.com/gui/file/ce700b0601156a00bd0a215190552f43de698750bebec03c24843b07ad98a25a/detection) (20 detections), `SbieDrv.sys` taken from version 5.41.2 x64. I don't use Windows Defender so I don't know how it will react.

Driver files for comparison (pass: 1234):
[Driver.zip](https://github.com/sandboxie-plus/Sandboxie/files/4868405/Driver.zip)

**Comment by Gravityzwell** [comment]
I agree with David. Test mode? That is a significant system level change, with consequences. I have no problem with David's approach, and in fact am very glad he did it as it's far better than nothing, and gets to something workable until something better can be done.

This is open source, so feel free to build your own and run in test mode :)

**Comment by deflock** [comment]
Hi @DavidXanatos! Can you for every release also attach an unsigned version of SbieDrv.sys?

**Comment by DavidXanatos** [comment]
> 
> 
> Hi @DavidXanatos! Can you for every release also attach an unsigned version of SbieDrv.sys?

I could but why? you cant load it without a signature...

**Comment by deflock** [comment]
>I could but why? you cant load it without a signature...
Yes, I know. I want to sign it with that chinese certificate until you sign it with a valid cert (if you still plan it)

**Comment by DavidXanatos** [comment]
do you think the Chinese cert is less bad?

**Comment by deflock** [comment]
I'm using Windows Defender. If it will not complain, it's better for me

**Comment by DavidXanatos** [comment]
well... when you sign it again it will remove the old signature.
you could have a signing only VM without Windows Defender for that task

**Comment by DavidXanatos** [comment]
I am cautiously optimistic that I may find someone to sign the next release, may be, no promises.

**Comment by deflock** [comment]
Can I somehow unsign driver? I want to upload unsigned to virustotal, check the result, sign and then check again

**Comment by DavidXanatos** [comment]
You can create a self signed certificate and sign the driver with it that will overwrite my signature.

**Comment by deflock** [comment]
To unsign: `signtool remove /s SbieDrv.sys`.

Looks much better.

Unsigned: https://www.virustotal.com/gui/file/7ceb5586d87fb8782daa7141c9e4e625b45ce29b7fa012d974033f5a03e7c6f0/detection
Signed: https://www.virustotal.com/gui/file/19ecec355c788ac170fbdecb07054b85576f64d6d8942b72978a7149479f1ec9/detection

**Comment by JReming85** [comment]
Why not use a unsigned driver, there are plenty of guides out on how to enable installing them

**Comment by JReming85** [comment]
Why not do a release with the unsigned driver?

**Comment by AndhikaWB** [comment]
> Why not do a release with the unsigned driver?

Because it's so much easier to just whitelist Sandboxie processes/directory from the antivirus. Most people who worried about safety won't install an unsigned driver either. I personally think it's worser than whitelisting Sandboxie itself.

Also, adding a signature is somewhat harder than removing it (because you also need a certificate file). So.. why not remove it yourself?

**Comment by DavidXanatos** [comment]
we have a properly signed driver now so I'll close this
