### ISSUE TITLE
Add support for NTVDMx64

### ISSUE THREAD

**Issue by kristibektashi** [sandboxie-plus/Sandboxie#520]
https://github.com/leecher1337/ntvdmx64

**Comment by DavidXanatos** [comment]
What is it?
===========
NTVDMx64 is a port of the well-known Windows NTVDM, which is used by windows 
to run DOS-Applications, to 64bit Windows, so that you can run your 
DOS-Applications on 64bit Windows too.
This is a proof-of-concept that it is possible to run the NTVDM on 64bit 
Windows and Microsoft was just too lazy to port it over and have disabled it 
for unknown reasons. **More specifically, it's a set of patches to the 
sourcecode of original Microsoft NTVDM from NT4** in order to work on 64bit 
Windows.


That sounds like it requires leaked windows source code to be build, I think as a standalone project its interesting but its legality is questionable, MSFT has not made NTVDM from NT4 open source, so thank you but no thank you.
