### ISSUE TITLE
How to set the default webrower in the sandbox?

### ISSUE THREAD

**Issue by nictse2013** [sandboxie-plus/Sandboxie#525]
cant find the opiton.
and it can visit my chrome.
can add some option to it?

**Comment by typpos** [comment]
Asking sandboxie to start the "default browser" will start your Windows default browser. You can't change that in Sandboxie settings. 

For custom behaviour, you can create shortcuts using sandboxie's "start.exe" command. Some examples:

Operating system default browser with a specific sandbox:
`"C:\Program Files\Sandboxie-Plus\start.exe" /box:MyBoxName default_browser`

Specific browser in a specific sandbox:
`"C:\Program Files\Sandboxie-Plus\start.exe" /box:MyBoxName "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`

Default browser in specific box with a specific initial website:
`"C:\Program Files\Sandboxie-Plus\start.exe" /box:MyBoxName "https://duckduckgo.com"`


A bit more on "default browser": Subject to some special conditions, on Windows 10 and Windows 8, it's the program associated with "http". For other Windows versions, it's the program associated with ".html". If all fails, and in special cases, sandboxie attempts to use Internet Explorer as the default browser. I assume that's in honour of the application that originally caused someone enough despair to start to write sandboxie :-)

**Comment by nictse2013** [comment]
THX,still a question.
under WIN10 if I want to use edge as default brower.Edge is a ump app,cant find the excat path what it is.
I just type the name,such as ""D:\Program Files\System\Sandboxie-Plus\Start.exe" /box:DefaultBox "D:\Program Files\System\Sandboxie-Plus\Start.exe" /box:DefaultBox Microsoft Edge"
but it doesnt works.
So how to set it?

**Comment by typpos** [comment]
* I don't know if you can run UWP applications in sandboxie: #19
* On my system, Edge is located here: "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe". This doesn't look like UWP, probably because of all the Edge to Chromium shuffle.
* I use Task Manager (Process tab > Right-click on running program > Open File Location) to find normal app executables.
* For UWP you can open "shell:appsFolder" in File Explorer and create and examine a shortcut, or use Powershell command "Get-AppxPackage" to get details. However these won't give you simple executable paths to just run.

**Comment by DavidXanatos** [comment]
the new edge is chromium based and no longer UWP based
