### ISSUE TITLE
Add RestrictedDefaultBox

### ISSUE THREAD

**Issue by bastik-1001** [sandboxie-plus/Sandboxie#555]
By default Sandboxie creates a sandbox in which applications are sandboxed, but have some more abilities compared to sandboxes that are more restricted.

This issue seeks to have two default boxes, the current one and a box with advanced isolation. This should allow users to be able to select the 'Restricted' default box without them having to create it by themselves for being lazy or uninformed.

- DefaultBox (the current default)
- RestrictedDefault (no admin rights, no internet access, no access to printers, bluetooth)

**Comment by ssokolow** [comment]
This *would* be an improvement for a lot of programs (eg. single-player games) but it's a little simplistic. What if you want to sandbox an office suite, which needs access to printers but otherwise matches the proposed RestrictedDefault?

...or what about something like [miniserve](https://github.com/svenstaro/miniserve/) which is a statically linked single-EXE HTTP file server (meaning it'll probably be open to random attackers on the public Internet) that needs the following:

* Read-only access to the folder being shared (or writable if you enable upload support)
* The ability to depend on the Microsoft C runtime for ABI-stable syscalls (The Rust standard library isn't quite as insane as Go in that respect)
* The ability to accept incoming TCP connections over IPv4 or IPv6 but not to initiate outgoing ones or handle UDP.

I think it'd be better to take a page from the book of [Firejail](https://firejail.wordpress.com/) (the closest Linux counterpart to Sandboxie). Firejail has a system where:

1. Profiles can `include` other profiles and, when rules conflict, the rule that was declared before the `include` was encountered wins.
2. Rules can be specified on the command-line and are treated as highest in the precedence chain, allowing a script (i.e. batch file) to dynamically build sandbox rulesets, either in isolation or as a refinement of a predefined profile.

(I did that latter one once. Firejail only knows how to `--whitelist` paths under `/home` and I wanted to be paranoid, so I wrote a launcher script to dynamically build a list of `--blacklist` arguments for unneeded stuff outside `/home`.)

**Comment by bastik-1001** [comment]
> This would be an improvement for a lot of programs (eg. single-player games) but it's a little simplistic. 

That is true as this ticket does only look for two default sandboxes for the current approach of Sandboxie.

> What if you want to sandbox an office suite, which needs access to printers but otherwise matches the proposed RestrictedDefault?

In the current system a user would supposed to create a new box with the desired properties.

> I think it'd be better to take a page from the book of Firejail (the closest Linux counterpart to Sandboxie). Firejail has a system where:  1)  Profiles can include other profiles and, when rules conflict, the rule that was declared before the include was encountered wins.  2)  Rules can be specified on the command-line and are treated as highest in the precedence chain, allowing a script (i.e. batch file) to dynamically build sandbox rulesets, either in isolation or as a refinement of a predefined profile.

It seems like a good idea to be flexible with how the system of sandboxes work, but it appears to require changes in how Sandboxie would work on a technical level, which would take some time.

**Comment by DavidXanatos** [comment]
I think having one box to begin with is enough, i may add some setup wizard in future that wil have the option to add other boxed, but i'll close this request for now
