### ISSUE TITLE
question on service dependency

### ISSUE THREAD

**Issue by boldcompany** [sandboxie-plus/Sandboxie#563]
Question on a particular use case:

Application installed in Sandboxie sandbox is successfully running with plugins (.dlls) in Sandboxie sandbox.

However, some plugins authenticate licenses against a licensing service which runs on the main/native system (not sandboxed), checking a USB key. For a variety of reasons, this licensing service cannot be installed in the sandbox. The plugins which rely on the licensing service fail to load in the sandbox, because they cannot authenticate against the service.

Is there a way to allow the sandboxed plugins to access this specific service, so they can successfully authenticate licenses?

**Comment by DavidXanatos** [comment]
If you know how teh communication works you can open that percicular communication channel eider a pipe or an ipc obejct probably

**Comment by boldcompany** [comment]
David, thank you for responding so quickly.

I do not know how the communication works, other than that the plugins are written to query the service (which is running in Windows all the time). Is there a way to allow a particular sandbox to simply access a service running in the native Windows instance?

**Comment by DavidXanatos** [comment]
Not in this broad way, you need to know how the communication is implemented.
You can not just say, open for service x and figure out how to do that on your own.

If you trust there is no malware in the sandbox you can try adding OpenIpcPath=*
that will unblock all the IPC communication and also disable isolation of COM objects
That may already be enough.

If the communication uses pipes than unfortunately you can not open them all since they are handled like files and opening all would break file system redirection.

You can use the resource monitor to figure out with which resources the plugins try to communicate.
Or you an use a tool like TaskExplorer ad investigate the services to figure out wat means of communication they use.

**Comment by boldcompany** [comment]
David, thank you for your continued help. I greatly appreciate it!!

And thank you for the important work you've done on such a groundbreaking technology.

I used Resource Monitor and TaskExplorer and neither revealed anything obvious enough for me to notice.

I then tried Sysinternals Process Explorer and located a specific licensing process (an .exe) that spikes in CPU when the application and plugins are run in non-sandboxed mode, but which doesn't seem to spike at all when the application and plugins are run in Sandboxie-sandboxed mode. Obviously, the question is how to figure out: How do the application+plugins access this .exe in normal/native Windows mode, and how to unrestrict this communication in Sandboxie mode?

On another note: As I think about the effort required to track down issues like this for all the different use cases I have, it makes me think setting up Sandboxie would require a lot of labor. For this particular use case, what I am most interested in is the "portable app" functionality that Sandboxie offers. Specifically, I would like to set up sandboxes of trusted apps and plugins, with the main benefit that they are self-contained and easily movable, since Sandboxie catches all the installation items and keeps them in one directory. Subsequently, I don't mind if these apps/plugins access system resources, since I'm not concerned about security - in these cases, I'm only concerned about portability. The reason I want to do this is that I have many app/plugin combos and would like a simple, portable way to manage them without having to do manual installs of each; Sandboxie would let me copy/paste them into new environments with ease.

So all that said: Can you envision a version (or mode) of Sandboxie called something like "Trusted Portable App" mode? Basically, in this mode, the user would run any app/plugin installers sandboxed, and Sandboxie would catch all the system changes and keep everything locked down into the sandbox directory. Then, after installation, "trust mode" would be activated and the app/plugins would be able to access requisite resources without the user having to hunt down specific IPC/pipe issues. The main benefit would be a portable-ized app and plugins. This "trust mode" could be disabled at any time for any sandbox. Sandboxie's main job in this mode is to enforce portability of the app(s) sandboxed, but not to enforce security per se.

I believe this would be very useful to a wide range of users who are seeking a straightforward way to make apps portable. There are a number of portable-app-maker tools out there, but they are slow and unreliable. Sandboxie is extremely reliable, except in cases where the sandboxed apps require licensing authentication or other access to system resources.

Please let me know if what I am proposing makes any sense.

**Comment by boldcompany** [comment]
In addition to the previous comment:

Working further with TaskExplorer, it was discovered that when using the app+plugins in native Windows, when they successfully connect to the .exe, handles to the following pipes appear:
\Device\NamedPipe\com_paceap_eden_licensed_authorization
\Device\USBPDO-32
\Device\USBPDO-32\ilok2

Entries in the sandbox .ini were added:
OpenPipePath=\Device\NamedPipe\com_paceap_eden_licensed_authorization
OpenPipePath=\Device\USBPDO-32
OpenPipePath=\Device\USBPDO-32\ilok2
...but this did not rectify the issue. The sandboxed version of app+plugins is unable to authenticate licensing.

**Comment by Rngexile** [comment]
> One issue noticed: After making manual entries in the sandbox .ini, such as adding OpenPipePath= entries, Sandboxie will show the entries under "Resource Access" as "File/Folder" entries. If the user edits the path there, the actual entries in the .ini will change from "OpenPipePath=" to "OpenFilePath=". It would be good if the Resource Access section could handle Pipe Path entries so that the entries aren't inadvertently switched.
> 

Just tested that for one of my box and no problem found (v0.7.0). I can change the path, then apply, then check the .ini and still have the original openPIPEpath.
Make sure you don't change the Access for "Direct". It should remain **"Direct All"**.
Direct = openfilepath
Direct All = openpipepath

**Comment by Rngexile** [comment]
I would say that a lot of usual simple applications already can be installed, ran fully into their sandbox and the sandbox package can even be used in another system (with sandboxie-plus already installed and the box .ini imported).

The difficult applications are mostly the ones that need to install services or drivers, because these would have to be outside the box, in the real filesystem (and you can't just openpipepath=* as David explained file redirection problems). Maybe with some "real time tracking" what the installer tries to install and accept on the fly the installation of these specific services and drivers outside sandboxie, then trace the specific needed calls when the application is used ... then save all of these in "oustide box" in another part of the current box directory and then re-install automatically the stuff when you use the full package on another system.
It would be some high level magic code imho.

**Comment by DavidXanatos** [comment]
Why so complicated, you can create services inside a sandbox and they are than sandboxed to, and run in the sandbox.
So no point installing terrible DRM crap on your real system, that is unless that junk is so unpolite to refuse to run in a nice coasy sandbox.

**Comment by Rngexile** [comment]
Damn, i was sure since many years than we couldn't install and use most services inside a box.
But it was probably a time when drm was a thing for me, game related probably. Now that GoG is a thing (no drm game plateform), i don't use any drm related stuff like steam or epic, i just don't play games not on GoG or packaged with some drm/services. 
But, indeed, if most polite services can install inside the box and properly run only for the applications inside that box, good news for some use cases. :)
