### ISSUE TITLE
SbieDrv.sys causes BSOD when Driver Verifier is launched

### ISSUE THREAD

**Issue by gjf** [sandboxie-plus/Sandboxie#57]
Steps to reproduce:

1. OS should be Windows 10 x64 Pro 1909.
2. Install Sandboxie.
3. Start "verifier" in command prompt. Select normal test for all drivers then reboot.
4. BSOD at the logon screen because of SbieDrv.sys.

**Comment by DavidXanatos** [comment]
hmm... i have tested that and the crash seams to originate in GetThreadTokenOwnerPid,
but I don't see anything obviously wrong with the code in that function, may be some more intricate issue.

**Comment by rugabunda** [comment]
This happened for me as well, back when I was using sophos's version... they did not bother signing the driver

**Comment by rugabunda** [comment]
Here is some of the info I dug up, some of my post from [sysnative](https://www.sysnative.com/forums/threads/windows-10-bsod-paradise-multiple-drivers-and-dumps.27805/)

"[I was told by sandboxie developers](https://forums.sandboxie.com/phpBB3/viewtopic.php?f=11&t=26535&p=136064#p136064) that "driver verifier does not work with sandboxie"... so if you can determine which dump was related to the sandboxie driver, and let me know what the results were, aka memory corruption and the like, that would be appreciated."

**Comment by rugabunda** [comment]
N/M I think this is it: https://github.com/Sandboxie-Website-Archive/sandboxie-website-archive.github.io/blob/c39bd0ffd7aae669cf01a446b195e758b88f1495/www.sandboxie.com/old-forums/search70b370b3.html

**Comment by rugabunda** [comment]
Read "Due to the nature of Sandboxie, MS Driver Verifier will not work with SbieDrv.sys." He goes into extensive detail why, as I grilled him on it quite heavily, you can find the rest if you dig around
https://github.com/Sandboxie-Website-Archive/sandboxie-website-archive.github.io/blob/c39bd0ffd7aae669cf01a446b195e758b88f1495/www.sandboxie.com/old-forums/search70b370b3.html

**Comment by DavidXanatos** [comment]
Various Driver Verifier issues will be fixed in the next build, including the BSOD on boot.
I can't guarantee I find all other minor once on my first go through, but currently everything seams fine, I can start FireFox and windows explorer sand boxed without any BSOD's. 
Yea!!!!!!

Seriously why Invincia never fixed them it wasn't so hard...

**Comment by nefarius** [comment]
😁
