### ISSUE TITLE
Reconsider adding the "Files and Folders" view to Sandboxie-Plus

### ISSUE THREAD

**Issue by darkred** [sandboxie-plus/Sandboxie#578]
@DavidXanatos
As continuation of this [comment](https://www.wilderssecurity.com/threads/released-sandboxie-plus-sbie-fork-versions-with-signed-driver.434924/page-15#post-2978283) you have made in the wilderssecurity forum, 
which I quote below:

> What is "Recover & Explore", do you mean the "Files and Folders" view in SbieCtrl which shows the folder structure of a selected sandbox instead of the processes?
> **No this view is not implemented and I'm not going to ad to sandman some half baked file explorer feature.** You can use the explore content menu option to open an explorer window to the box root folder, isn't that just as good? Plus even better as explorer is much more user friendly?
>
> <details>
> <summary>Screenshot</summary>
> 
> ![jpg](https://user-images.githubusercontent.com/723651/108263661-39cd5a80-716f-11eb-8647-81c35033ef2d.png)
> 
> </details>

I'd like to ask you please to reconsider adding the "Files and Folders" view to Sandboxie Plus.

I found that feature very useful, because I could see at once which files were created/views in the Sandboxie, just by expanding the `+` expander icons. 
Currently (via the content menu option to open an explorer window to the box root folder) I have to manually navigate each folder to see the files, and most importantly I can't see all at once in a single view.

This is the only feature I miss from Sandboxie Classic.

Using Sandboxie-Plus 0.7.0 on Windows 10

Thank you

**Comment by typpos** [comment]
@darkred: 

> I have to manually navigate each folder to see the files, and most importantly I can't see all at once in a single view

I don't have an opinion on your feature proposal, but in case this helps, you can view all files in Windows File Explorer if you enter "*" in the search box.

![image](https://user-images.githubusercontent.com/28550406/108280258-0a036e80-71d2-11eb-8c91-16bc83060fde.png)

**Comment by darkred** [comment]
Yes, I know of that (thanks for replying, though), 
but I'd definitely prefer the `[+]` expanders view, because it displays the files as a tree, each with its parent directory.

**Comment by DavidXanatos** [comment]
I understand that people like their workflows to remain functional, I myself really really don't like braking UI changes, my windows 10 for the most part still looks like windows 7....

But the plus UI is a new tool, and you have the ability to use the old UI of you need to. 

For me this feature is very quaint the way its implemented, its missing an integration of the explorer context menu and while it looks and feels like a file explorer it functional does not allow to really manage files past recovering them some ware.
I don't like the idea of adding a feature that is broken by design (or at least severely limited in functionality) that to be implemented properly takes you 80% of the way to have developed an own file manager, while providing at lest 20% of the functionality of a proper file explorer.

**Comment by darkred** [comment]
I'd rather avoid also installing Sandboxie Classic, just to be able to quickly explore the contents of a sandbox that I created and only use in the new UI. I'd prefer to stick with the UI, I love the tremendous work you have done with it.

&nbsp;
If you have made your decision, feel free to close this issue.
It's just that I find that feature the most useful in Sandboxie Classic, not just a part of my previous workflow.
*And to be frank, as I was trying to find the "Files and Folders" view  in Sandboxie-Plus, I couldn't believe that this feature is not available, I was certain it had to be there somewhere.*

Let me give you an example: 
you run in an empty Sandboxie a random executable you have just downloaded:
while you run it, or after you close it, you could find in the "Files and Folders" view, which files were created/modified in the sandbox (plus be reminded of the existence of RegHive files),
therefore quickly get a first look on how that executable has changed the files of your system.
*(relevant links: [1](https://sandboxie-plus.com/sandboxie/filesandfoldersview/), [2](https://sandboxie-plus.com/sandboxie/filesandfoldersview/SandboxHierarchy) )*

**Comment by DavidXanatos** [comment]
Well its a bit complicated....
You see for a long time I was playing with the thought of creating an own file manager, simply because while there are many great once out there for windows they are are missing some odd features I would really love to have, plus there are non that would be even remotely good for Linux.

So such a feature (properly packed in a reusable DLL) might be the first step towards that...

**Comment by DavidXanatos** [comment]
this feature will be included in the next build, but its a very simple implementation just using QFileSystemModel

**Comment by darkred** [comment]
Thanks a lot for implementing this!
