### ISSUE TITLE
Vivaldi Launch: SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#65]
Sandboxie error when loading Vivaldi (latest) 3.1.1929.40 (Stable channel) (64-bit); Latest Windows 10 x64 1909, with drop rights disabled and allowing vivaldi to call upon BITS and CompPkgSrv.exe.

![Sandboxie 2](https://user-images.githubusercontent.com/38260267/85212982-46ae5b80-b30d-11ea-8534-8818044ee2ca.png)

`SBIE2101 Object name not found: , error ConnectPort (C0000022) access=001F0000 initialized=1`

Not sure what this even means...  should I just ignore it, or would it be wise to dig deeper, and patch this error up?

**Comment by CakeTheLiar** [comment]
I'm experiencing the same issue with multiple Chromium based browsers (tested with Chrome, Vivaldi, Brave) on Windows 10. This error has been persistent over multiple Windows and Sandboxie updates, including multiple of the closed-source ones. Those browsers still launch just fine and I have not found any further problems caused by it; these errors can _probably_ be ignored.

From skipping through the code, I believe the error is a bug in this function Obj_GetName: https://github.com/sandboxie-plus/Sandboxie/blob/a2fa7739fc43c5ac25b36a1c9f14319626ff2cd0/Sandboxie/core/drv/obj.c#L113
When you search for error "2101" and walk through what may cause it, you'll end up there. The function name also lines up with the error message "Object name not found".

The way it tries to load the name by probing ObQueryNameString with different buffer lengths seems _weird_, overly complicated and error prone. By Microsofts documentation you should just be able to pass NULL and 0 for the 2nd and 3rd argument respectively and get the required buffer size written to the 4th argument, then use that size to initiate the buffer and try again:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-obquerynamestring

Take a look at this usage I dug up with a quick Google search for reference:
https://github.com/nsacyber/Driver-Collider/blob/03788d5381e646d21d8c7c38bd1e3e325a065a67/collision/driver.c#L164

The majority of Obj_GetName may be replaced by something along the lines of:
```
ObQueryNameString(Object, NULL, 0, &len);
info = (OBJECT_NAME_INFORMATION *) Mem_Alloc(pool, len); // or len + PAD_LEN?
if (! info)
	return STATUS_INSUFFICIENT_RESOURCES;
status = ObQueryNameString(Object, info, len, &len);
if (NT_SUCCESS(status)) { ...
```

I'd try to fix it myself, but my current setup refuses to compile any usable driver atm.

**Comment by DavidXanatos** [comment]
is this issue still present in the recent builds?

**Comment by NewKidOnTheBlock** [comment]
I've downloaded the latest version from the main website: 
https://downloads.vivaldi.com/stable/Vivaldi.3.6.2165.34.x64.exe
Then tried to install:
![vivaldi install](https://user-images.githubusercontent.com/12411527/106184389-c2c12980-61a1-11eb-8330-ba7052edfe42.png)
But if you click on GO, this happens:
![vivaldi install2](https://user-images.githubusercontent.com/12411527/106184429-cc4a9180-61a1-11eb-90c3-fdddb2a80513.png)

**Comment by rugabunda** [comment]
> 
> 
> is this issue still present in the recent builds?

I haven't noticed any issue running the brower in some time, I will test it for a while tonight and report back

**Comment by rugabunda** [comment]
> 
> 
> I've downloaded the latest version from the main website:
> https://downloads.vivaldi.com/stable/Vivaldi.3.6.2165.34.x64.exe
> Then tried to install in SB 5.46.4:
> ![vivaldi install](https://user-images.githubusercontent.com/12411527/106184389-c2c12980-61a1-11eb-8330-ba7052edfe42.png)
> But then this happens:
> ![vivaldi install2](https://user-images.githubusercontent.com/12411527/106184429-cc4a9180-61a1-11eb-90c3-fdddb2a80513.png)
> 
> Analysis: The installer looks like it comes with all the necessary files `Vivaldi.3.6.2165.34.x64.exe` = 68.1 MB
> There are no files written to `C:\Test\Vivaldi\`
> But a `vivaldi_installer.log` got created:
> 
> > [0128/194709.730:ERROR:setup_main.cc(333)] Failed to find archive to patch.
> > [0128/194713.035:ERROR:persistent_histogram_storage.cc(121)] Could not write "SetupMetrics" persistent histograms to file as the storage directory does not exist.

My problem appears to have been resolved. You may want to start a new issue, it is largely unrelated to the topic at hand here. I'm closing this unless I find the issue resurfacing in the future.
