### ISSUE TITLE
sandboxie causes windows explorer to take a long time to launch

### ISSUE THREAD

**Issue by darchon7** [sandboxie-plus/Sandboxie#662]
with sandboxie plus loaded, it takes my AMD Threadripper 1950x 32gb ram, 42 secs to launch. without it, 1-2 secs.

**Comment by silvestron** [comment]
I've never had that much lag, however adding `OpenWinClass=#` to a sandbox is something that had helped a lot mitigate any lag I had before using explorer and other programs. If you use the UI instead of the ini file, the setting is under *Advanced options ->  Miscellaneous -> Compatibility -> Don't alter window class names created by sandboxed programs*.

**Comment by DavidXanatos** [comment]
I think the issue is a general problem with window creation sandboxie had since a long time, in the next build its fixed by re implementing the window hooking mechanism in a much more sensible manner.
