### ISSUE TITLE
How to run Sandboxie Plus?

### ISSUE THREAD

**Issue by silvestron** [sandboxie-plus/Sandboxie#663]
After upgrading to Sandboxie Plus I've noticed both `SandMan.exe` and `SbieCtrl.exe` running in the background. Is this the expected behavior? I'm asking because I used to run Classic before and I'm wondering if any previous configuration is still launching `SbieCtrl.exe` or this is how it is supposed to work.

Also, is it safe to close SbieCtrl and have only SandMan in the background or do I need both?

**Comment by bjm234** [comment]
Plus and Classic have the same core components this means ALL Security fixes as well as ALL Compatibility improvements always apply to both equaly.
The used UI has no effect on security, compatibility or performance.
https://www.wilderssecurity.com/thr...ith-signed-driver.434924/page-21#post-2980854
Classic is like the old Sophos build version 5.33.6 and Plus is with new features.
If you're long time Sandboxie user....you may feel more comfortable with Classic. If you're new user....I'd urge Plus...since, developer wants users to embrace Plus.
Plus & Classic builds share core components. Sandboxie-Plus (installer) installs shared core components to Sandboxie-Plus folder. SandboxieInstall (installer) installs core components to Sandboxie folder.
Plus users may run Plus UI or Classic UI.
Since the Open Sourcing sandboxie is being released in two flavors the classical build with a MFC based UI and as plusbuild that incorporates new features and an entirely new Q’t based UI. All newly added features target the plus branch but often can be utilized in the classical edition by manually editing the sandboxie.ini file.
https://xanasoft.com/sandboxie-plus/
My practice is to pin Plus UI SandMan &or Classic UI SbieCtrl to Taskbar. Just me.
Users may set Start UI preference.
png_9368.png png_9369.png

**Comment by silvestron** [comment]
Thank you for your answer. I always thought the UI was independent from actual sandboxing, I just wanted a confirmation.
