### ISSUE TITLE
Feature request: block Internet access more transparently through lack of connectivity

### ISSUE THREAD

**Issue by xnoreq** [sandboxie-plus/Sandboxie#665]
Current state:
Currently, it seems like Sandboxie blocks Internet access by _denying_ certain Winsock calls, for example through "operation not permitted" errors.

The problem:
I've seen several applications that either get stuck or crash because of that.

The solution / feature request:
Instead of denying calls, fake allowing calls and generate responses that mimic a lack of network connectivity.

For example, a socket connect to some IP would fail with a "network not available/reachable" error instead of a "operation not permitted".

**Comment by DavidXanatos** [comment]
this is a known issue and there are already a few requests about that, making the requested changes is a lot of work ,
you see we block a couple if pipes that are used to interact with the kernels network stack, at this level we don't have the option to generate a host not found error or alike.
We would need to hook a lo of functions that internal use this interfaces and make them return nice errors instead of trying to use a blocked device.

**Comment by DavidXanatos** [comment]
further discussion on sandboxie's networking aspects please in issue #894
