### ISSUE TITLE
Vivaldi: SBIE2318 DLL initalization failed for 'ole32.dll'

### ISSUE THREAD

**Issue by rugabunda** [sandboxie-plus/Sandboxie#68]
Using latest stable Vivaldi release in windows 10x64 1909

Admin access allowed; but occurs randomly depending on the website I get the aforementioned error. Opening a youtube video triggered this recently.

```
SBIE2303 Could not hook CoGetObject (33, 1655)
SBIE2303 Could not hook RegisterDragDrop (33, 1655)
SBIE2318 DLL initialization failed for 'ole32.dll'
```

>  Message: SBIE2318 DLL initialization failed for library.dll
> 
> Logged To: Popup Message Log.
> 
> Explanation:
> 
> The sandboxed program issued a request to load the system DLL named in the message. Some functionality in some system DLLs does not work "out of the box" when running sandboxed, due to the restrictions placed on the sandboxed program. In these cases, Sandboxie has to alter the DLL in order to assist it in accomplishing its tasks.
> 
> The message indicates Sandboxie could not "fix" the system DLL. 
> 

===

> 
> 
> Message: SBIE2303 Could not hook name(reason)  			 			 				Logged To: Popup Message Log. 			 			 				
> Explanation:  This message indicates that the Sandboxie DLL component, which is  running within the sandboxed program, has failed to intercept and  replace the system function identified by name.  			 			 				
> 
> This message is typically an indication of incompatibility with some third party software.
> --
> 
>

**Comment by DavidXanatos** [comment]
from: https://community.sophos.com/products/sandboxie/f/forum/115348/anyone-seeing-occasional-ole-init-hook-failed-errors-from-sandboxie#pi2151=2

"
This seems to be caused by a new feature of Chrome 79, "Audio Sandbox" (see https://support.google.com/chrome/a/answer/7679408/).

Since I use Windows, I disable this by modifying registry at HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome => Add DWORD value "AudioSandboxEnabled" => Set it to 0
"

Please try of that helps with your issue

**Comment by rugabunda** [comment]
Thanks DavidXanatos, would prefer to have the audio sandbox enabled, is this not feasible to patch?

**Comment by DavidXanatos** [comment]
> 
> 
> Thanks DavidXanatos, would prefer to have the audio sandbox enabled, is this not feasible to patch?

Everything can be patched given enough work but there are so many things to patch that chrome audio sandbox is very very low priority.
