### ISSUE TITLE
Sandboxie Plus Highlights

### ISSUE THREAD

**Issue by TheYarin** [sandboxie-plus/Sandboxie#716]
@DavidXanatos Thank you so much for picking up this amazing project!

As I understand from Sandboxie Plus's website, in the Plus version you intend to make a UI makeover.
Can you give the highlights of the differences between the classic Sandboxie and Sandboxie Plus? While those can probably be found burried in the releases changelog, it's kind of hard to spot the major ones among all the changes.

In addition, would you mind telling us what are your plans for the future of Sandboxie? Any change of direction, significant behavior changes etc.

**Comment by NotepadPlusUser** [comment]
I would like to second this request.  I am a long-time non-techie user of Sandboxie --- most appreciative of @DavidXanatos 's excellent work rescuing this excellent software, and his patience and responsiveness in the Wilders Forum.  

I am still using Classic, mainly because in the midst of all the techie detail I don't really understand what the advantages and disadvantages of Plus are.  But I am most curious, and I have picked up @DavidXanatos 's hints that in the future, Plus may be the only supported version.

Now that things have stabilised, a 'pinned issue' would be helpful containing:
* a dot-pointed list of the extra features and advantages with Plus at present, 
* a list of any disadvantages of Plus compared with Classic,
* clear and concise instructions how to upgrade from Classic to Plus,
* clear updating instructions now that the issues with certificates have been solved,
* any future directions. as best as they are known at this stage.

**Comment by NotepadPlusUser** [comment]
As a partial answer to my first dotpoint above, Ashwin at ghacks has a very appreciative account of Plus, written from the point of view of someone used to Classic:
https://www.ghacks.net/2021/01/29/sandboxie-plus-is-an-open-source-fork-of-sandboxie-with-a-modern-interface/

**Comment by DavidXanatos** [comment]
> 
> 
> As a partial answer to my first dotpoint above, Ashwin at ghacks has a very appreciative account of Plus, written from the point of view of someone used to Classic:
> https://www.ghacks.net/2021/01/29/sandboxie-plus-is-an-open-source-fork-of-sandboxie-with-a-modern-interface/

That looks good enough so i think I don't have anything more to do here ;)
