### ISSUE TITLE
Any way to try the portable version while having an older Classic?

### ISSUE THREAD

**Issue by lwcorp** [sandboxie-plus/Sandboxie#755]
**Describe the bug**
It seems impossible to try the portable version while having the latest Sophos version.
An acquaintance has the latest Sophos version and I wanted to convince them it's time to move to the Plus version.
Sure, I can get them to first try your latest Classic version, but:
1. It requires an installation.
1. One transition is convincing enough.

The point was to show them the future in a simple quick portable way.

**To Reproduce**
1. Install the latest Sophos version
1. Run Sandboxie-Plus-x64-vX.exe
1. Choose Portable Mode
1. Run the program (i.e. SandMan.exe)
1. It complains about an incompatibility

**Expected behavior**
It should run without relation to the latest Sophos version.

**Screenshots**
![image](https://user-images.githubusercontent.com/1773306/113487818-e4e96780-94c2-11eb-8d13-eafe3ed4b94f.png)

**System and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows 10 Pro 20H2). **Windows 10 Home 20H2**
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus 0.7.2). **Sandboxie Classic 5.33.3**
 - Please mention in which version this bug got introduced, because it acts as a guide for testers and developers. **I tried Sandboxie-Plus-x64-v0.7.2.exe**
 - Please mention any security software running in the background, even if the real-time protection is disabled.
**Windows' built-in one.**

**Additional context**
Add any other context about the problem here. **I tried shutting off the Classic Sandboxie Control first but it made no difference**

**Comment by AndhikaWB** [comment]
I don't think it's possible without removing Sandboxie (Sophos) service first. I assume you're familiar with cmd, you can do that by typing these commands on Sandboxie directory (with admin rights):
```
KmdUtil.exe stop SbieSvc
KmdUtil.exe stop SbieDrv
KmdUtil.exe delete SbieSvc
KmdUtil.exe delete SbieDrv
```
But the driver is usually still loaded by Windows even after you remove it (there is no way to unload it from cmd), so you may need to restart Windows completely.

After restart, start Sandboxie-Plus. Don't forget to stop and uninstall Sandboxie-Plus driver completely after that (no restart required, Sandboxie-Plus will unload the driver for you).

Now, the problem is installing Sandboxie (Sophos) driver back to your system. Type these commands on cmd on Sandboxie directory (with admin rights):
```
KmdUtil.exe install SbieDrv "SbieDrv.sys" type=kernel start=demand "msgfile=SbieMsg.dll" altitude=86900
KmdUtil.exe install SbieSvc "SbieSvc.exe" type=own start=auto "display=Sandboxie Service" group=UIGroup "msgfile=SbieMsg.dll"
reg add "HKLM\System\CurrentControlSet\Services\SbieSvc" /v "PreferExternalManifest" /t REG_DWORD /d 1 /f
KmdUtil.exe start SbieDrv
KmdUtil.exe start SbieSvc
```

Start Sandboxie (Sophos), it should work again. Please note that Sandboxie (Sophos) store its settings file (Sandboxie.ini) on system directory (unlike Sandboxie-Plus portable).

If you encounter problems, try to solve it by yourself first. I'm a bit busy, sorry.

**Comment by DavidXanatos** [comment]
Its not possible to run two incompatible versions side by side
