### ISSUE TITLE
windows 10 security "Exploit protection" prevent Sandboxie-Plus from functioning 

### ISSUE THREAD

**Issue by eyaladmin** [sandboxie-plus/Sandboxie#823]
Hi 
I tried the plus edition, but since my windows 10 defender Exploit protection configured "On by default"
I was unable to work with the application, 
even when I tried to exclude all program "exe" files in "C:\Program Files\Sandboxie-Plus" from checking the CFG.

any suggestions?

Thank you very much

![CFG-off](https://user-images.githubusercontent.com/61413950/116976690-29d30a80-acca-11eb-8e8d-4b08afb8a483.PNG)

![error](https://user-images.githubusercontent.com/61413950/116976378-b92bee00-acc9-11eb-9d38-e11ead893572.PNG)
![Exploit protection](https://user-images.githubusercontent.com/61413950/116976380-ba5d1b00-acc9-11eb-9787-0dae1ffc1f07.PNG)

**Comment by sebadamus** [comment]
I got a similar problem days ago here: https://github.com/sandboxie-plus/Sandboxie/issues/815, but I use Bitdefender Free, also detect an exploit.  I closed the issue because it dissappeared as it came.

I dont really know, some other will answer for sure, but I might think its because "the digital signature" of the compilation itself... you can read about it https://github.com/sandboxie-plus/Sandboxie/issues/95

**Comment by DavidXanatos** [comment]
I will look into it but its possible that the compatybility may be unfixable depanding on what MSFT is dong there exactly, Sbie does a lot of hooking and call redirecting...

**Comment by DavidXanatos** [comment]
Ins strange in my test VM with CFG enabled all works still fine,
can you confirm that when you disable CFG globally on your system it starts working again?

**Comment by DavidXanatos** [comment]
since there is no more fead back and also a recent fix fixed issues with CET that may also have upset CFG i'll close this oen now
