### ISSUE TITLE
Firefox doesn't connect to the internet

### ISSUE THREAD

**Issue by Rex000** [sandboxie-plus/Sandboxie#836]
After installing Firefox it opens but doesn't connect to the internet, so no browsing.

 - Windows 10 Pro 20H2
 - Sandboxie Plus 0.7.4
 - Windows Security

**Comment by eneerge** [comment]
If you enter https://1.1.1.1 in Firefox, does it come up? Perhaps the default Cloudflare DNS configuration is blocked on your network - by default instead of connecting to your DNS server, it connects to Cloudflare over TLS to perform lookups. Disabling this feature may help.

Firefox works without issue for me up through v89.0.

**Comment by DavidXanatos** [comment]
does not seam to be a sbie issue
