### ISSUE TITLE
input method is installed inside sandbox

### ISSUE THREAD

**Issue by norelmas** [sandboxie-plus/Sandboxie#892]
Installed an input method inside a sandbox, but can't input another language.

**Comment by isaak654** [comment]
Do you have `FakeAdminRights=y` included in the same sandbox?

**Comment by norelmas** [comment]
> Do you use `FakeAdminRights=y` in the same sandbox?

Some don't ask for elevation, e.g., https://github.com/rime/weasel

**Comment by isaak654** [comment]
> 
> 
> > Do you use `FakeAdminRights=y` in the same sandbox?
> 
> Some don't ask for elevation, e.g., https://github.com/rime/weasel

See issue #801, you will find also a reference about Weasel.

**Comment by norelmas** [comment]
> See issue #801, you will find also a reference about Rime.

Why not release an app template?

**Comment by norelmas** [comment]
> See issue #801, you will find also a reference about Rime.
> 

But my situation is IM is installed inside sandbox, not in host.

**Comment by isaak654** [comment]
Not all programs can be installed inside the sandbox, also please provide the steps you tried in order to allow me to reproduce your issue (screenshots would also help).

> 
> 
> 
> Why not release an app template?

Not everybody has the same user, so I think it's easier to write this at the bottom of the ini file:

```
[Template_Local_Rime]

Tmpl.Title=Rime
Tmpl.Class=Local
OpenPipePath=\Device\NamedPipe\WriteYourOwnUser\WeaselNamedPipe
```

or just copying the OpenPipePath line to the sandbox.

**Comment by xWTF** [comment]
Dear @isaak654,
I can confirm the template works with `%user%` variable. However the IME become extremely laggy when typing.
Further investigation shows that it's trying to load fonts from localappdata and keeps failing, therefore the following `ReadFilePath` rule is required:
```ini
Tmpl.Title=Weasel (Rime)
Tmpl.Class=Local
OpenPipePath=\Device\NamedPipe\%user%\WeaselNamedPipe
ReadFilePath=%localappdata%\Microsoft\Windows\Fonts
```
A simple way to probe rime would be checking the existence of `WeaselServer.exe` process. BTW Rime for Windows should be called "Weasel" instead of "Rime".

**Comment by xWTF** [comment]
Based on the examples, I think I'm supposed to use the following scan config ([reference](https://github.com/rime/weasel/blob/e9010244032be1233729736316bd58ee3fd608b8/WeaselSetup/WeaselSetup.cpp#L67-L69)):

```ini
Tmpl.Scan=s
Tmpl.ScanKey=\REGISTRY\USER\%sid%\Software\Rime\Weasel
```

However I'm not sure how can I test if the scan succeeded. The template does not show up in `App Compatibility` section after I added these keys :(

**Comment by isaak654** [comment]
> Edit: I just checked the code and obviously this will not work since the ScanKey does not expand the variable.

If no other Scan options can be applied for this template, you could open a new feature request and in the meantime open a new pull request with the suggested template.

If anyone wants to know how to check the template detection in App Compatibility:

> If you want to test the template detection in App Compatibility, you should add the template in Templates.ini, remembering to put `[Template_Weasel]` before `Tmpl.Title=Weasel (Rime)` in your code [here](https://github.com/sandboxie-plus/Sandboxie/issues/892#issuecomment-2047423238).
> 
> Please note that to speed up detection, it is recommended to exit/restart Sandboxie. If detection still does not occur, it means that the chosen Scan options are not working.

**Comment by xWTF** [comment]
Since Weasel does not create a key in HKLM (which hindered the key scan cuz it's not easy to access HKCU with `NtOpenKey`), nor does it use a consistent installation path (the path contains version number), I assume the proper way to detect it is to scan the class registration:

```ini
[Template_Weasel]
Tmpl.Title=Weasel (Rime)
Tmpl.Class=Desktop
Tmpl.Scan=s
Tmpl.ScanKey=\REGISTRY\MACHINE\SOFTWARE\Classes\CLSID\{A3F4CDED-B1E9-41EE-9CA6-7B4D0DE6CB0A}
OpenPipePath=\Device\NamedPipe\%user%\WeaselNamedPipe
ReadFilePath=%localappdata%\Microsoft\Windows\Fonts
```

![image](https://github.com/sandboxie-plus/Sandboxie/assets/31540475/e39f33e1-8fc0-41bc-89d4-6d58064a16e4)

I used the same technique found in the 7z template, since I can't get `Tmpl.ScanWinClass` wowking (not really familiar with these APIs):

https://github.com/sandboxie-plus/Sandboxie/blob/7fc005f70a492e6ea356148c67056114638bce01/Sandboxie/install/Templates.ini#L2810-L2817

Since it's a relatively small change, would you please commit this directly, or should I open a PR for it?
