### ISSUE TITLE
Program unable to change system account password in Sandboxie even BlockPassword=n was defined

### ISSUE THREAD

**Issue by GoldJohnKing** [sandboxie-plus/Sandboxie#938]
**Describe the bug**

Programs used to be able to change system account password inside Sandboxie at a very early version (v5.33.1).

However, after some Sandboxie-Plus version, programs are unable to change the password in Sandboxie even with [BlockPassword=n](https://sandboxie-plus.com/sandboxie/blockpassword/) defined.

I've wrote a test program which changes `user0`'s password to `AbXy1366768`.

The programs runs well outside Sandboxie or inside Sandboxie v5.33.1, but it fails and returns [Error 1783: The stub received bad data](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1700-3999-) in latest Sandboxie-Plus (v0.8.2/5.50.2) with [BlockPassword=n](https://sandboxie-plus.com/sandboxie/blockpassword/) defined.

**To Reproduce**
1. Install Sandboxie-Plus v0.8.2/5.50.2.
2. Run `ChangePasswordTest` outside Sandboxie-Plus, it shows "Password Change Success".
3. Run the program inside Sandboxie-Plus, it shows "Password Change Failed" with error code.
4. Install Sandboxie v5.33.1, reset configuration file and run the program in Sandboxie, it shows "Password Change Success".

**Expected behavior**
The [BlockPassword=n](https://sandboxie-plus.com/sandboxie/blockpassword/) or some other config should allow program in Sandboxie-Plus change system account password.

**System details and installed software (please provide the following information):**
 - What is your Windows edition and version? (i.e. Windows Server 2019).
 - What is your current Sandboxie edition and version? (i.e. Sandboxie Plus v0.8.2/5.50.2).
 - A clean installed OS without any security softwares (MS Defender was disabled).

**Additional context**
The program used to test the issue:
[ChangePasswordTest.zip](https://github.com/sandboxie-plus/Sandboxie/files/6706803/ChangePasswordTest.zip)

**Sandboxie configuration**

I've tried with default configs generated by Sandboxie-Plus, the issue still exists, so I guess it has nothing to do with the configs.

<details>
 
<summary>My initial sandboxie.ini settings</summary>
 
```

[GlobalSettings]

OpenIpcPath=\BaseNamedObjects\__ComCatalogCache__
OpenIpcPath=\RPC Control\seclogon

Template=WindowsRasMan
Template=LingerPrograms
Template=AutoRecoverIgnore
Template=WindowsLive
Template=OfficeLicensing

[box00]
Enabled=y
ConfigLevel=7
FileRootPath=D:\Sandbox\%USER%\%SANDBOX%
AutoDelete=y
NeverDelete=n
CopyLimitKb=49152
CopyLimitSilent=y
AutoRecover=n
BorderColor=#00FFFF,off
BoxNameTitle=y

</details>

**Comment by onigumo69** [comment]
Me here having the exact same issue,
Unable to change user account's password with sandboxed programs on Windows 10/2016/2019.
According to the sandboxie docs that "Hardware Access has been removed from Sandboxie v4 and up."
However I think this is something that crucially needed since Windows forces you to pass the username and password of system account when trying to creat process in a specific system account.
Hopefull this will get fixed sooner, unspeakable appreciated.

**Comment by onigumo69** [comment]
Me here having the exact same issue,
Unable to change user account's password with sandboxed programs on Windows 10/2016/2019.
According to the sandboxie docs that "Hardware Access has been removed from Sandboxie v4 and up."
However I think this is something that crucially needed since Windows forces you to pass the username and password when creating processes in that specific system account.
Hopefull this will get fixed sooner, unspeakable appreciated.

**Comment by onigumo69** [comment]
Me here having the exact same issue.
Unable to change user account's password with sandboxed programs on Windows 10/2016/2019.
According to the sandboxie docs that "Hardware Access has been removed from Sandboxie v4 and up."
However I think this is something that crucially needed since Windows forces you to pass the username and password when creating processes in that specific system account.
Hopefull this will get fixed sooner, unspeakable appreciated.

**Comment by isaak654** [comment]
The script above fails to me for any plus version I tried (0.2 portable, 0.4.4, 0.5.3, 0.7.2, 0.8.2) with `BlockPassword=n` defined.

**Comment by DavidXanatos** [comment]
that is interesting, MSFT must have changed something someware along the road.

on windows 10 you need ```OpenSamEndpoint=y``` to be able to change passwords
the old ```BlockPassword=n``` option controlls a different endpoint.

strangely i cant get password change to work on any windows with ```BlockPassword=n``` 
being that xp, 7, 8.1 or 10, So not sure whats up with that.
On xp, 7 and 8.1 it seams  ```OpenSamEndpoint=y```  also does not work, that said strangely v5.33 also doe snot allow for password change on 7 and xp

To me it looks liek these setting was always ineffective and on 10 you could change passwords irregardless of the ```BlockPassword=n```  value before i added the necessary filtering for the sam endpoint.

**Comment by isaak654** [comment]
Windows 10 and Plus 0.4.4:  I was able to change the password successfully with and without `BlockPassword=n`.
The only condition to make it work is to enable the option "Run as UAC administrator".

Windows 10 starting from 0.7.0 / 5.48.0:  you need to check option "Run as UAC administrator" and having `OpenSamEndpoint=y` in the sandbox.

**Comment by onigumo69** [comment]
So far seems like "OpenSamEndpoint=y" did the trick.
Will keep you guys informed if they were any updates.
Thanks and keep up the amazing work.

**Comment by onigumo69** [comment]
So far seems like "OpenSamEndpoint=y" did the trick.
Will keep you guys informed if they were any new updates.
Thanks and keep up the amazing work.

**Comment by GoldJohnKing** [comment]
> on windows 10 you need OpenSamEndpoint=y to be able to change passwords

Ah, this solves my issue.
This config seems never appears in the docs so...

Great!

**Comment by isaak654** [comment]
> 
> This config seems never appears in the docs so...
> 

New parameters are mentioned in the changelog, a good way to find them is to search the equal sign here:
https://github.com/sandboxie-plus/Sandboxie/blob/master/CHANGELOG.md

You can also contribute to the GitHub version of the docs with new updates:
https://github.com/DavidXanatos/sandboxie-docs
