### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [sandboxie-plus/Sandboxie#977]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by DavidXanatos** [comment]
i have added the requested file with my email:
https://github.com/sandboxie-plus/Sandboxie/blob/master/SECURITY.md
please not that the address has a [at] in it instead of an @ to avoid automated spam

**Comment by DavidXanatos** [comment]
The issue reported states that sandboxie does not protect its user mode hooks in any way, this is a known behavior.

This is fine since Sandboxie is not relying on any user mode hooks to enforce security boundary's, most of the hooks are used to make the application work in the heavily restricted environment its put in by the driver, by redirecting accesses to locations that the application actually can access. Some non security critical convenience functions require the hooks to be in place, but these are things like process hiding, window title modification, etc... unhooking those does not constitute a problem, as they are not security critical.

I see how people may relay on the window title but than there are windows without a title where there would be no indication to begin with.
The session agent (sandman.exe or sbiectrl.exe) there for also provides the colorful border around windows when enabled as this mode of indication can not be tempered with by the sandboxed application itself.


Thanks for looking into Sandboxie and checking it for possible security issues, I appreciate the afford very much.
